/**
 * Type definitions for the WorkerBus -- centralised, promise-based
 * Web Worker communication layer.
 *
 * Workers that opt into the WorkerBus protocol MUST include `messageId`
 * in every response so the bus can correlate it with the original request.
 */

// ---------------------------------------------------------------------------
// Wire protocol -- main thread -> worker
// ---------------------------------------------------------------------------

/** Envelope sent from the main thread to a worker via WorkerBus.dispatch(). */
export interface WorkerRequest<TPayload = unknown> {
    /** Unique correlation ID generated by the bus. */
    messageId: string
    /** Command / action type the worker should execute. */
    type: string
    /** Arbitrary payload; shape depends on `type`. */
    payload?: TPayload
}

// ---------------------------------------------------------------------------
// Wire protocol -- worker -> main thread
// ---------------------------------------------------------------------------

/** Envelope sent from a worker back to the main thread. */
export interface WorkerResponse<TData = unknown> {
    /** Must echo the `messageId` from the originating request. */
    messageId: string
    /** `true` when the operation completed without error. */
    success: boolean
    /** Result data on success. */
    data?: TData
    /** Human-readable error string on failure. */
    error?: string
    /** Typed error code for programmatic handling (K-04). */
    errorCode?: WorkerErrorCode
}

// ---------------------------------------------------------------------------
// Typed Worker Error Codes (K-04)
// ---------------------------------------------------------------------------

/** Exhaustive error codes for worker failures. Enables typed error handling. */
export enum WorkerErrorCode {
    /** Generic / uncategorised failure. */
    UNKNOWN = 'UNKNOWN',
    /** Request exceeded the configured timeout. */
    TIMEOUT = 'TIMEOUT',
    /** Worker is not registered with the bus. */
    NOT_REGISTERED = 'NOT_REGISTERED',
    /** Bus or worker has been disposed / torn down. */
    DISPOSED = 'DISPOSED',
    /** Backpressure queue is full. */
    QUEUE_FULL = 'QUEUE_FULL',
    /** Worker threw during execution. */
    EXECUTION_ERROR = 'EXECUTION_ERROR',
    /** Invalid payload or message format. */
    INVALID_PAYLOAD = 'INVALID_PAYLOAD',
    /** Model or resource not available. */
    RESOURCE_UNAVAILABLE = 'RESOURCE_UNAVAILABLE',
    /** Out of memory / allocation failure. */
    OUT_OF_MEMORY = 'OUT_OF_MEMORY',
    /** Operation was cancelled (e.g. AbortController). */
    CANCELLED = 'CANCELLED',
    /** Per-worker rate limit exceeded (W-01). */
    RATE_LIMITED = 'RATE_LIMITED',
    /** Job was preempted by a higher-priority dispatch (W-02). */
    PREEMPTED = 'PREEMPTED',
}

/**
 * Structured error thrown by WorkerBus dispatch.
 * Carries a typed `code` for programmatic error handling.
 */
export class WorkerBusError extends Error {
    readonly code: WorkerErrorCode
    readonly workerName: string

    constructor(message: string, code: WorkerErrorCode, workerName: string) {
        super(message)
        this.name = 'WorkerBusError'
        this.code = code
        this.workerName = workerName
    }
}

// ---------------------------------------------------------------------------
// Convenience helper (worker-side)
// ---------------------------------------------------------------------------

/**
 * Build a success response that satisfies `WorkerResponse`.
 */
export function workerOk<T>(messageId: string, data: T): WorkerResponse<T> {
    return { messageId, success: true, data }
}

/**
 * Build an error response that satisfies `WorkerResponse`.
 */
export function workerErr(
    messageId: string,
    error: string,
    errorCode: WorkerErrorCode = WorkerErrorCode.EXECUTION_ERROR,
): WorkerResponse<never> {
    return { messageId, success: false, error, errorCode }
}
