/**
 * Type definitions for the WorkerBus -- centralised, promise-based
 * Web Worker communication layer.
 *
 * Workers that opt into the WorkerBus protocol MUST include `messageId`
 * in every response so the bus can correlate it with the original request.
 */

// ---------------------------------------------------------------------------
// Wire protocol -- main thread -> worker
// ---------------------------------------------------------------------------

/** Envelope sent from the main thread to a worker via WorkerBus.dispatch(). */
export interface WorkerRequest<TPayload = unknown> {
    /** Unique correlation ID generated by the bus. */
    messageId: string
    /** Command / action type the worker should execute. */
    type: string
    /** Arbitrary payload; shape depends on `type`. */
    payload?: TPayload
}

// ---------------------------------------------------------------------------
// Wire protocol -- worker -> main thread
// ---------------------------------------------------------------------------

/** Envelope sent from a worker back to the main thread. */
export interface WorkerResponse<TData = unknown> {
    /** Must echo the `messageId` from the originating request. */
    messageId: string
    /** `true` when the operation completed without error. */
    success: boolean
    /** Result data on success. */
    data?: TData
    /** Human-readable error string on failure. */
    error?: string
    /** Typed error code for programmatic handling (K-04). */
    errorCode?: WorkerErrorCode
}

// ---------------------------------------------------------------------------
// Typed Worker Error Codes (K-04)
// ---------------------------------------------------------------------------

/** Exhaustive error codes for worker failures. Enables typed error handling. */
export enum WorkerErrorCode {
    /** Generic / uncategorised failure. */
    UNKNOWN = 'UNKNOWN',
    /** Request exceeded the configured timeout. */
    TIMEOUT = 'TIMEOUT',
    /** Worker is not registered with the bus. */
    NOT_REGISTERED = 'NOT_REGISTERED',
    /** Bus or worker has been disposed / torn down. */
    DISPOSED = 'DISPOSED',
    /** Backpressure queue is full. */
    QUEUE_FULL = 'QUEUE_FULL',
    /** Worker threw during execution. */
    EXECUTION_ERROR = 'EXECUTION_ERROR',
    /** Invalid payload or message format. */
    INVALID_PAYLOAD = 'INVALID_PAYLOAD',
    /** Model or resource not available. */
    RESOURCE_UNAVAILABLE = 'RESOURCE_UNAVAILABLE',
    /** Out of memory / allocation failure. */
    OUT_OF_MEMORY = 'OUT_OF_MEMORY',
    /** Operation was cancelled (e.g. AbortController). */
    CANCELLED = 'CANCELLED',
    /** Per-worker rate limit exceeded (W-01). */
    RATE_LIMITED = 'RATE_LIMITED',
    /** Job was preempted by a higher-priority dispatch (W-02). */
    PREEMPTED = 'PREEMPTED',
}

/**
 * Structured error thrown by WorkerBus dispatch.
 * Carries a typed `code` for programmatic error handling.
 */
export class WorkerBusError extends Error {
    readonly code: WorkerErrorCode
    readonly workerName: string

    constructor(message: string, code: WorkerErrorCode, workerName: string) {
        super(message)
        this.name = 'WorkerBusError'
        this.code = code
        this.workerName = workerName
    }
}

// ---------------------------------------------------------------------------
// Convenience helper (worker-side)
// ---------------------------------------------------------------------------

/**
 * Build a success response that satisfies `WorkerResponse`.
 */
export function workerOk<T>(messageId: string, data: T): WorkerResponse<T> {
    return { messageId, success: true, data }
}

/**
 * Build an error response that satisfies `WorkerResponse`.
 */
export function workerErr(
    messageId: string,
    error: string,
    errorCode: WorkerErrorCode = WorkerErrorCode.EXECUTION_ERROR,
): WorkerResponse<never> {
    return { messageId, success: false, error, errorCode }
}

// ---------------------------------------------------------------------------
// W-04: Generic WorkerMessageMap -- typed dispatch per worker
// ---------------------------------------------------------------------------

/**
 * Per-message-type mapping: message type string -> { payload, response }.
 * Workers that are NOT listed here fall back to `unknown` (no type error).
 */

/** VPD simulation worker messages (`simulation`). */
export interface SimulationMessages {
    SIMULATE: {
        payload: { points: number; params: Record<string, number> }
        response: { results: unknown[] }
    }
}

/** Vision inference worker messages (`visionInference`). */
export interface VisionInferenceMessages {
    INIT: { payload: undefined; response: { ready: boolean } }
    CLASSIFY: {
        payload: { imageData: ArrayBuffer; width: number; height: number }
        response: { label: string; confidence: number; leafLabel: string }
    }
    TERMINATE: { payload: undefined; response: { terminated: boolean } }
}

/** Hydroponic forecast worker messages (`hydroForecast`). */
export interface HydroForecastMessages {
    INIT: { payload: undefined; response: { ready: boolean } }
    FORECAST: {
        payload: { metric: string; readings: number[]; timestamps: number[] }
        response: { predicted: number; trend: string; confidence: number }
    }
}

/** Serializable voice command definition for worker-side matching. */
export interface SerializedVoiceCommand {
    id: string
    aliases: string[]
    keywords: string
}

/** Voice processing worker messages (`voice`). */
export interface VoiceWorkerMessages {
    PARSE_COMMAND: {
        payload: { transcript: string; commands: SerializedVoiceCommand[] }
        response: {
            commandId: string | null
            confidence: number
            matchType: 'exact' | 'fuzzy' | 'keyword' | 'none'
        }
    }
    PROCESS_TRANSCRIPT: {
        payload: { transcript: string; lang: string }
        response: { cleaned: string; detectedLang: string }
    }
    COMPUTE_WAVEFORM: {
        payload: { samples: Float32Array; barCount: number }
        response: { amplitudes: Uint8Array }
    }
}

/**
 * Map from registered worker name to its typed message definitions.
 * Workers not listed here are still callable via the generic `dispatch`
 * overload -- they fall back to `unknown` payload/response.
 */
export interface WorkerMessageMap {
    simulation: SimulationMessages
    visionInference: VisionInferenceMessages
    hydroForecast: HydroForecastMessages
    voice: VoiceWorkerMessages
}

/**
 * Extract the valid message types for a given worker.
 */
export type WorkerTypes<W extends keyof WorkerMessageMap> = string & keyof WorkerMessageMap[W]

/**
 * Extract the payload type for a specific worker + message type.
 */
export type WorkerPayload<
    W extends keyof WorkerMessageMap,
    T extends WorkerTypes<W>,
> = WorkerMessageMap[W][T] extends { payload: infer P } ? P : unknown

/**
 * Extract the response type for a specific worker + message type.
 */
export type WorkerResponseData<
    W extends keyof WorkerMessageMap,
    T extends WorkerTypes<W>,
> = WorkerMessageMap[W][T] extends { response: infer R } ? R : unknown
