/**
 * Type definitions for the WorkerBus -- centralised, promise-based
 * Web Worker communication layer.
 *
 * Workers that opt into the WorkerBus protocol MUST include `messageId`
 * in every response so the bus can correlate it with the original request.
 */

// ---------------------------------------------------------------------------
// Wire protocol -- main thread -> worker
// ---------------------------------------------------------------------------

/** Envelope sent from the main thread to a worker via WorkerBus.dispatch(). */
export interface WorkerRequest<TPayload = unknown> {
    /** Unique correlation ID generated by the bus. */
    messageId: string
    /** Command / action type the worker should execute. */
    type: string
    /** Arbitrary payload; shape depends on `type`. */
    payload?: TPayload
}

// ---------------------------------------------------------------------------
// Wire protocol -- worker -> main thread
// ---------------------------------------------------------------------------

/** Envelope sent from a worker back to the main thread. */
export interface WorkerResponse<TData = unknown> {
    /** Must echo the `messageId` from the originating request. */
    messageId: string
    /** `true` when the operation completed without error. */
    success: boolean
    /** Result data on success. */
    data?: TData
    /** Human-readable error string on failure. */
    error?: string
}

// ---------------------------------------------------------------------------
// Convenience helper (worker-side)
// ---------------------------------------------------------------------------

/**
 * Build a success response that satisfies `WorkerResponse`.
 */
export function workerOk<T>(messageId: string, data: T): WorkerResponse<T> {
    return { messageId, success: true, data }
}

/**
 * Build an error response that satisfies `WorkerResponse`.
 */
export function workerErr(messageId: string, error: string): WorkerResponse<never> {
    return { messageId, success: false, error }
}
