sonar.organization=qnbs
sonar.projectKey=qnbs_CannaGuide-2025

sonar.sources=apps/web
sonar.tests=apps/web
sonar.typescript.tsconfigPath=apps/web/tsconfig.json

sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.min.js,**/locales/**,**/data/**
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,**/tests/**
