// This file is generated by the translation script. Do not edit manually.
export const strainsData = {
  "acdc": {
    "description": "A famous CBD-dominant strain, bred for therapeutic purposes without strong psychoactive effects. The name stands for 'Alternative Cannabinoid Dietary Cannabis'. It has a relaxing and anxiety-relieving effect while keeping the mind clear. Ideal for pain and anxiety.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Cannatonic x Ruderalis",
    "aromas": [
      "Earthy",
      "Sweet",
      "Woody",
      "Pine",
      "Spicy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Pinene",
      "Caryophyllene"
    ]
  },
  "acapulco-gold": {
    "description": "A legendary landrace strain from Acapulco, Mexico, famous since the 1960s. Known for its golden-brown buds and an energizing, euphoric, and motivating effect. The taste is reminiscent of sweet, earthy toffee. A classic 'wake-and-bake' strain.",
    "typeDetails": "Sativa 80% / Indica 20%",
    "genetics": "Mexican Landrace",
    "aromas": [
      "Earthy",
      "Sweet",
      "Citrus",
      "Pine",
      "Spicy"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Myrcene",
      "Limonene"
    ]
  },
  "acid-dough": {
    "description": "An award-winning sativa-dominant strain from Ripper Seeds. It offers a fast-acting, euphoric, and giggly high that uplifts the mind and slightly relaxes the body. The buds are dense, dark green with orange hairs and purple trichomes.",
    "typeDetails": "Sativa 80% / Indica 20%",
    "genetics": "Lilly (Queen Mother x Congo) x OG Badazz",
    "aromas": [
      "Sweet-sour",
      "Tropical",
      "Pineapple",
      "Earthy",
      "Candy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Limonene"
    ]
  },
  "afghan-kush": {
    "description": "An Indica landrace from the Hindu Kush mountains. Known for its strong, almost narcotic body effect and high resin production, making it ideal for hashish production. It has a deeply relaxing and sedating effect. Ideal for the evening and for pain or insomnia.",
    "typeDetails": "Indica 100%",
    "genetics": "Hindu Kush Landrace",
    "aromas": [
      "Earthy",
      "Spicy",
      "Pine",
      "Woody",
      "Sweet"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Pinene"
    ]
  },
  "afghan-skunk": {
    "description": "A classic indica-dominant hybrid that combines the robust nature and relaxing effect of Afghani with the high yield and pungent aroma of Skunk #1. It provides a deeply relaxing body effect and is known for its ease of handling and resilience.",
    "typeDetails": "Indica 85% / Sativa 15%",
    "genetics": "Afghani x Skunk #1",
    "aromas": [
      "Skunk",
      "Earthy",
      "Sweet",
      "Pungent"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Pinene"
    ]
  },
  "afghani": {
    "description": "A fundamental landrace from Afghanistan that forms the genetic basis for many modern Indicas. It provides a deeply relaxing and sedating effect that relieves stress and helps with insomnia. The aroma is earthy, sweet, and skunky.",
    "typeDetails": "Indica 100%",
    "genetics": "Afghan Landrace",
    "aromas": [
      "Earthy",
      "Sweet",
      "Skunk",
      "Spicy",
      "Pine"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Pinene",
      "Caryophyllene"
    ]
  },
  "afgoo": {
    "description": "Also known as Afgooey. A potent indica-dominant strain known for its extremely resinous, sticky buds. The effect is strongly physically relaxing, almost sedating, and leads to a euphoric, happy state. Ideal for evening use for stress and insomnia.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Afghani x Maui Haze",
    "aromas": [
      "Earthy",
      "Pine",
      "Sweet",
      "Spicy",
      "Woody"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Pinene",
      "Ocimene"
    ]
  },
  "agent-orange": {
    "description": "Bred by MzJill Genetics. Known for its intense citrus and orange aroma. The effect is energizing, uplifting, and creative, making it an excellent choice for daytime and social occasions. Helps with fatigue and depression.",
    "typeDetails": "Sativa 75% / Indica 25%",
    "genetics": "Orange Velvet x Jack The Ripper",
    "aromas": [
      "Orange",
      "Citrus",
      "Sweet",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Terpinolene",
      "Caryophyllene"
    ]
  },
  "agent-x": {
    "description": "A modern, balanced hybrid from Alien Labs (2022). It offers a complex aroma of apple, cheese, and asphalt with floral notes. The effect is strong but balanced, with an uplifting head high and a relaxed body feel. Ideal for experienced consumers.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Atomic Apple x Xeno #1",
    "aromas": [
      "Apple",
      "Cheese",
      "Diesel",
      "Floral",
      "Mint"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Limonene",
      "Linalool"
    ]
  },
  "ak-47": {
    "description": "A legendary, award-winning strain from Serious Seeds (1992). Despite its name, the effect is gentle, uplifting, and cerebral, followed by a mild body relaxation. Ideal for creative and social activities. The aroma is earthy, sweet, and floral.",
    "typeDetails": "Sativa 65% / Indica 35%",
    "genetics": "Colombian x Mexican x Thai x Afghani",
    "aromas": [
      "Earthy",
      "Sweet",
      "Floral",
      "Woody",
      "Spicy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Pinene",
      "Caryophyllene"
    ]
  },
  "alaskan-ice": {
    "description": "An extremely potent sativa-dominant strain from Greenhouse Seed Co. It offers an immediate, uplifting, and euphoric high that slowly transitions into a relaxing body effect. Known for its high resin production, ideal for extracts.",
    "typeDetails": "Sativa 70% / Indica 30%",
    "genetics": "White Widow x Haze",
    "aromas": [
      "Spicy",
      "Woody",
      "Earthy",
      "Pepper",
      "Sandalwood"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Limonene",
      "Pinene"
    ]
  },
  "alaskan-purple": {
    "description": "A robust and high-yielding strain that develops beautiful purple colors in cooler temperatures. The indica-dominant effect is physically relaxing (Kush influence) with a cerebral, uplifting note (Sativa influence). The aroma is sweet and berry-like with floral notes.",
    "typeDetails": "Indica 70% / Sativa 30%",
    "genetics": "(Purple Alaskan x Kush) x Brazilian Sativa",
    "aromas": [
      "Berry",
      "Sweet",
      "Floral",
      "Earthy",
      "Spicy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Linalool"
    ]
  },
  "alaskan-thunder-fuck": {
    "description": "Alias: ATF. A legendary Sativa from the Matanuska Valley in Alaska. Known for an intense, euphoric, and energizing high that boosts creativity. The aroma is a complex mix of pine, lemon, menthol, and skunk.",
    "typeDetails": "Sativa 70% / Indica 30%",
    "genetics": "(Northern Californian Sativa x Russian Ruderalis) x Afghani",
    "aromas": [
      "Pine",
      "Lemon",
      "Menthol",
      "Earthy",
      "Skunk"
    ],
    "dominantTerpenes": [
      "Pinene",
      "Linalool",
      "Myrcene",
      "Caryophyllene"
    ]
  },
  "alien-dawg": {
    "description": "A pure Indica known for its sour, diesel-like aroma and potent, relaxing effects. It's one of the parent strains of Alien Kush and provides a strong cerebral effect that transitions into deep body relaxation.",
    "typeDetails": "Indica 100%",
    "genetics": "Chemdawg x Alien Technology",
    "aromas": [
      "Sour",
      "Diesel",
      "Earthy",
      "Pungent",
      "Pine"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Limonene",
      "Caryophyllene"
    ]
  },
  "alien-kush": {
    "description": "A balanced hybrid with a spicy, earthy, and piney aroma. It offers a clear, cerebral effect that transitions into a gentle body relaxation. Known for its 'alien-like' effect that can slightly alter perception.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Las Vegas Purple Kush x Alien Dawg",
    "aromas": [
      "Spicy",
      "Earthy",
      "Pine",
      "Sweet"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Pinene"
    ]
  },
  "alien-og": {
    "description": "Also known as Alien OG Kush. A highly potent hybrid known for its intense, almost psychedelic cerebral high combined with a heavy body effect. Ideal for experienced consumers. The aroma is a classic OG mix of lemon, pine, and earth.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Tahoe OG x Alien Kush",
    "aromas": [
      "Pine",
      "Lemon",
      "Earthy",
      "Sweet",
      "Spicy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Limonene",
      "Caryophyllene",
      "Pinene"
    ]
  },
  "alien-rock-candy": {
    "description": "A potent indica-dominant strain with a sweet, candy-like flavor profile complemented by sour and earthy notes. The effect is deeply relaxing and sedating, ideal for relieving pain, stress, and insomnia at the end of the day.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Sour Dubble x Tahoe Alien",
    "aromas": [
      "Sweet",
      "Berry",
      "Citrus",
      "Sour",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Limonene",
      "Caryophyllene",
      "Nerolidol"
    ]
  },
  "american-dream": {
    "description": "A fast-flowering, high-yielding strain from Sensi Seeds. It offers a euphoric, social, and relaxing effect without a strong 'couch-lock'. The aroma is earthy and skunky with fresh, tropical-fruity notes. Ideal for commercial growers and beginners.",
    "typeDetails": "Indica 75% / Sativa 25%",
    "genetics": "Afghan Skunk x (Jamaican x Hawaiian)",
    "aromas": [
      "Earthy",
      "Skunk",
      "Pine",
      "Fruity",
      "Sweet"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Pinene",
      "Caryophyllene",
      "Limonene"
    ]
  },
  "amnesia": {
    "description": "A legendary strain made famous in Amsterdam coffee shops. Known for a strong, cerebral, euphoric, and energizing high. Despite the name, it promotes creativity and sociability. The aroma is earthy with sweet citrus notes.",
    "typeDetails": "Sativa 70% / Indica 30%",
    "genetics": "Unknown (often associated with Skunk, Cinderella 99, Jack Herer)",
    "aromas": [
      "Citrus",
      "Earthy",
      "Sweet",
      "Floral",
      "Spicy"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Humulene",
      "Ocimene",
      "Terpinolene"
    ]
  },
  "amnesia-haze": {
    "description": "A multiple Cannabis Cup winner, famous for its potent, long-lasting, and almost psychedelic cerebral effect. Promotes energy, euphoria, and creativity. The aroma is a complex mix of lemon, citrus, earth, and spices.",
    "typeDetails": "Sativa 80% / Indica 20%",
    "genetics": "Various Landraces (South Asian, Jamaican, etc.)",
    "aromas": [
      "Citrus",
      "Lemon",
      "Earthy",
      "Spicy",
      "Sweet"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Limonene",
      "Caryophyllene"
    ]
  },
  "amnesia-lemon": {
    "description": "An award-winning strain (Cannabis Cup 2004) known for its intense citrus and lemon flavor. The effect is uplifting, cerebral, and energizing, typical of a Sativa, but with a relaxing physical component. Ideal for daytime use.",
    "typeDetails": "Sativa 60% / Indica 40%",
    "genetics": "Amnesia Haze x Lemon Skunk",
    "aromas": [
      "Lemon",
      "Citrus",
      "Sweet",
      "Spicy",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Ocimene",
      "Terpinolene",
      "Limonene"
    ]
  },
  "animal-cookies": {
    "description": "A potent, indica-dominant hybrid that provides heavy full-body relaxation, ideal for relieving pain and insomnia. It has a sweet, sour aroma with heavy, earthy notes.",
    "typeDetails": "Indica 75% / Sativa 25%",
    "genetics": "GSC x Fire OG",
    "aromas": [
      "Sweet",
      "Sour",
      "Earthy",
      "Nutty"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Limonene",
      "Myrcene"
    ]
  },
  "animal-mints": {
    "description": "Bred by Seed Junky Genetics. A highly potent hybrid with a complex aroma of mint, cookie dough, vanilla, and a hint of diesel. The effect is strong and balanced, starting with a euphoric head high that transitions into a deep, sedating body relaxation.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Animal Cookies x SinMint Cookies (or other GSC crosses)",
    "aromas": [
      "Mint",
      "Sweet",
      "Cookie Dough",
      "Earthy",
      "Diesel"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Limonene",
      "Myrcene",
      "Pinene"
    ]
  },
  "appalachian-kush": {
    "description": "A potent hybrid with an earthy, sweet, and slightly spicy aroma. It provides a balanced effect that starts with a cerebral, energetic boost and transitions into a relaxing body effect. Ideal for relieving stress and pain without being completely sedating.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Green Crack x Tres Dawg",
    "aromas": [
      "Earthy",
      "Sweet",
      "Spicy",
      "Pine"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Limonene"
    ]
  },
  "apple-betty": {
    "description": "A potent hybrid with a delicious flavor profile reminiscent of baked apple pie with notes of cinnamon and chocolate. The effect is fast-acting, euphoric, and giggly, almost psychedelic, followed by a deep body relaxation.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Sour Apple x Animal Cookies (or Chem's Sister x Sour Apple x Chocolate Diesel)",
    "aromas": [
      "Apple",
      "Sweet",
      "Earthy",
      "Pastry",
      "Spicy"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Limonene",
      "Humulene"
    ]
  },
  "apple-cobbler": {
    "description": "A balanced hybrid with a fruity, tart flavor profile of apple and earth. The effect sets in slowly, starting with a cerebral lift that boosts mood and creativity, and transitions into a calming body relaxation. Ideal for stress and pain relief.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Blueberry Moonshine x Sour Apple (or Sour Apple x Animal Cookies)",
    "aromas": [
      "Apple",
      "Sweet",
      "Earthy",
      "Pine",
      "Spicy"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Limonene",
      "Linalool"
    ]
  },
  "apple-fritter": {
    "description": "An extremely potent hybrid known for its high THC content and delicious taste of sweet apple pastry. The effect is strong and balanced, starting with a euphoric and creative high that transitions into a deeply relaxing body effect.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Sour Apple x Animal Cookies",
    "aromas": [
      "Apple",
      "Sweet",
      "Earthy",
      "Pastry",
      "Vanilla"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Limonene",
      "Humulene",
      "Pinene"
    ]
  },
  "apple-jack": {
    "description": "A potent hybrid that offers uplifting and soothing effects. Ideal for treating chronic pain or nausea. The flavor profile is skunky and earthy with undertones of sliced apple. The sativa-dominant effect is energizing and creative.",
    "typeDetails": "Sativa 70% / Indica 30%",
    "genetics": "Jack Herer x White Widow",
    "aromas": [
      "Apple",
      "Sweet",
      "Earthy",
      "Skunk",
      "Spicy"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Myrcene",
      "Limonene",
      "Pinene"
    ]
  },
  "apples-and-bananas": {
    "description": "Bred by Compound Genetics & Cookies. It offers a complex fruit aroma of apples, bananas, cherries, and spices. The effect is balanced and potent, providing a happy and relaxed feeling that soothes the body but keeps the mind active. Perfect for the afternoon.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "[(Platinum Cookies x Granddaddy Purple) x Blue Power] x Gelatti",
    "aromas": [
      "Apple",
      "Banana",
      "Fruity",
      "Sweet",
      "Spicy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Limonene",
      "Caryophyllene",
      "Linalool"
    ]
  },
  "atomic-apple": {
    "description": "A balanced hybrid from Alien Labs. It combines the minty, earthy flavor of Triangle Mints with the sweet apple pastry of Apple Fritter. The effect is strong, euphoric, and relaxing, suitable for all-day use.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Triangle Mints x Apple Fritter",
    "aromas": [
      "Apple",
      "Sweet",
      "Mint",
      "Earthy",
      "Vanilla"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Limonene",
      "Myrcene"
    ]
  },
  "aurora-indica": {
    "description": "Bred by Nirvana Seeds. A potent F1 hybrid that produces heavy full-body effects and a sedating cerebral calm. Ideal for evening treatment of insomnia and pain. The plants are short, robust, and produce dense, resinous buds.",
    "typeDetails": "Indica 90% / Sativa 10%",
    "genetics": "Afghan x Northern Lights",
    "aromas": [
      "Earthy",
      "Spicy",
      "Woody",
      "Sweet",
      "Floral"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Pinene"
    ]
  },
  "auto-duck": {
    "description": "A unique 'stealth' strain from Dutch Passion with a natural leaf mutation (duck's foot shape) that makes it inconspicuous. The smell is subtle. The effect is balanced and moderate, ideal for daytime use. Very robust and easy to grow.",
    "typeDetails": "Sativa 50% / Indica 50% (Autoflower)",
    "genetics": "Frisian Duck x Auto White Widow",
    "aromas": [
      "Earthy",
      "Floral",
      "Fruity",
      "Mint",
      "Pine"
    ],
    "dominantTerpenes": [
      "Terpinolene",
      "Caryophyllene",
      "Myrcene"
    ]
  },
  "auto-white-widow": {
    "description": "The autoflowering version of the legendary White Widow. It retains the potent, balanced effect and spicy-earthy aroma of the original but grows faster and easier. Ideal for beginners.",
    "typeDetails": "Hybrid 50% / 50% (Autoflower)",
    "genetics": "White Widow x Ruderalis",
    "aromas": [
      "Earthy",
      "Spicy",
      "Pine",
      "Sweet"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Pinene"
    ]
  },
  "ayahuasca-purple": {
    "description": "A pure Indica from Barney's Farm, known for its stunning purple and ruby red colors. The effect is deeply relaxing, calming, and can have psychedelic qualities. The aroma is exotic with notes of hazelnut and papaya. Very high-yielding.",
    "typeDetails": "Indica 100%",
    "genetics": "Red River Delta x Master Kush",
    "aromas": [
      "Papaya",
      "Hazelnut",
      "Tropical",
      "Earthy",
      "Sweet"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Limonene",
      "Caryophyllene",
      "Pinene"
    ]
  },
  "b-52": {
    "description": "An indica-dominant hybrid known for its relaxing yet uplifting effects. It provides gentle cerebral stimulation that relieves stress, followed by a warm, soothing body effect. Ideal for late afternoon or evening use.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Skunk #1 x Big Bud",
    "aromas": [
      "Sweet",
      "Earthy",
      "Skunk",
      "Floral"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Pinene"
    ]
  },
  "banana-kush": {
    "description": "An indica-dominant hybrid famous for its strong banana aroma and flavor. It delivers a mellow, euphoric buzz that promotes creativity and social interaction while providing deep physical relaxation. Excellent for stress relief.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Ghost OG x Skunk Haze",
    "aromas": [
      "Banana",
      "Sweet",
      "Tropical",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Limonene",
      "Myrcene",
      "Caryophyllene"
    ]
  },
  "banana-og": {
    "description": "A potent indica-dominant hybrid with a pronounced aroma of overripe bananas. The effect is creeping and powerful, leading to deep relaxation and often sleepiness. Best suited for evening use to combat insomnia and pain.",
    "typeDetails": "Indica 70% / Sativa 30%",
    "genetics": "OG Kush x Banana",
    "aromas": [
      "Banana",
      "Sweet",
      "Earthy",
      "Pungent"
    ],
    "dominantTerpenes": [
      "Limonene",
      "Myrcene",
      "Caryophyllene"
    ]
  },
  "bay-platinum-cookies": {
    "description": "A hybrid strain that's a phenotype of Girl Scout Cookies. It offers a balanced high that starts with a cerebral rush and settles into a comfortable body relaxation. The aroma is sweet and earthy with spicy notes.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Bay 11 x Platinum Cookies",
    "aromas": [
      "Sweet",
      "Earthy",
      "Spicy",
      "Herbal"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Limonene",
      "Myrcene"
    ]
  },
  "bc-bud": {
    "description": "A general term for high-quality cannabis from British Columbia, Canada. When referring to a specific strain, it's often a potent indica-dominant hybrid known for delivering a strong, relaxing body high. The aroma is typically skunky and earthy.",
    "typeDetails": "Indica-dominant Hybrid",
    "genetics": "Varies, often a Skunk phenotype",
    "aromas": [
      "Earthy",
      "Skunk",
      "Sweet",
      "Pine"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Pinene",
      "Caryophyllene"
    ]
  },
  "bedica-talea": {
    "description": "A medicinal cannabis strain from Bedrocan, standardized for consistency. It's a strong indica known for its sedating and pain-relieving properties, commonly used for sleep disorders, chronic pain, and nausea.",
    "typeDetails": "Indica-dominant Hybrid",
    "genetics": "Proprietary",
    "aromas": [
      "Earthy",
      "Spicy",
      "Herbal"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene"
    ]
  },
  "bediol-elida": {
    "description": "A balanced THC:CBD medicinal strain from Bedrocan. The high CBD content mitigates the psychoactive effects of THC, making it suitable for patients seeking relief from inflammation, anxiety, and pain without a strong 'high'.",
    "typeDetails": "Sativa-dominant Hybrid",
    "genetics": "Proprietary",
    "aromas": [
      "Earthy",
      "Sweet",
      "Citrus"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Terpinolene"
    ]
  },
  "bedrocan-afina": {
    "description": "The flagship medicinal sativa strain from Bedrocan, known for its high THC content and standardized quality. It provides an uplifting, energetic, and clear-headed effect, often used for ADHD, depression, and fatigue.",
    "typeDetails": "Sativa-dominant Hybrid",
    "genetics": "Jack Herer phenotype",
    "aromas": [
      "Spicy",
      "Haze",
      "Earthy",
      "Citrus"
    ],
    "dominantTerpenes": [
      "Terpinolene",
      "Myrcene"
    ]
  },
  "bedrolite-rensina": {
    "description": "A CBD-dominant medicinal strain from Bedrocan with minimal THC. It's designed for patients, including children, who need the therapeutic benefits of CBD for conditions like epilepsy and inflammation without any psychoactive effects.",
    "typeDetails": "CBD-dominant Hybrid",
    "genetics": "Proprietary",
    "aromas": [
      "Earthy",
      "Herbal",
      "Subtle"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Bisabolol"
    ]
  },
  "big-bud": {
    "description": "An indica-dominant hybrid famous for its massive yields. As the name suggests, it produces exceptionally large and heavy buds. The effect is deeply relaxing and sedating, perfect for combating stress and insomnia.",
    "typeDetails": "Indica 85% / Sativa 15%",
    "genetics": "Afghani x Northern Lights x Skunk #1",
    "aromas": [
      "Sweet",
      "Earthy",
      "Skunk",
      "Fruity"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Pinene"
    ]
  },
  "birthday-cake-kush": {
    "description": "An indica-dominant hybrid with a delicious sweet, cake-like flavor. It provides a strong body high that is deeply relaxing and euphoric, making it ideal for celebrating the end of a long day. Helps with pain, anxiety, and insomnia.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Girl Scout Cookies x Cherry Pie",
    "aromas": [
      "Sweet",
      "Vanilla",
      "Earthy",
      "Nutty"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Limonene",
      "Myrcene"
    ]
  },
  "biscotti": {
    "description": "A potent indica-dominant hybrid known for its delicious flavor profile of sweet cookies with diesel undertones. The high is cerebral and blissful, quickly followed by a relaxing body buzz that spreads from head to toe.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Gelato #25 x Girl Scout Cookies x South Florida OG",
    "aromas": [
      "Sweet",
      "Cookie",
      "Diesel",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Limonene",
      "Myrcene"
    ]
  },
  "biscotti-mintz": {
    "description": "A visually striking, potent indica-dominant strain from Barney's Farm. It features deep purple hues and a complex aroma of mint chocolate chip cookies and spice. The effect is creative and focused initially, settling into a calming and relaxing body high.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Biscotti x Kush Mints",
    "aromas": [
      "Mint",
      "Chocolate",
      "Spicy",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Limonene",
      "Caryophyllene",
      "Eucalyptol"
    ]
  },
  "black-beauty": {
    "description": "A rare sativa strain known for its exceptionally dark, almost black foliage and buds. It contains THCV, which is known to produce a clear-headed, stimulating, and shorter-lasting high compared to THC. The aroma is floral and sweet.",
    "typeDetails": "Sativa-dominant Hybrid",
    "genetics": "Undisclosed",
    "aromas": [
      "Floral",
      "Sweet",
      "Herbal"
    ],
    "dominantTerpenes": [
      "Terpinolene"
    ]
  },
  "black-cherry-soda": {
    "description": "A well-balanced hybrid named for its dark coloration and fruity, soda-like flavor. It provides a balanced effect that starts with cerebral stimulation and settles into a calm, relaxed state, making it suitable for daytime use.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Undisclosed",
    "aromas": [
      "Cherry",
      "Berry",
      "Sweet",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Limonene"
    ]
  },
  "black-dahlia": {
    "description": "An indica-dominant hybrid with beautiful dark purple buds. The aroma is sweet and floral with earthy undertones. It offers a relaxing and euphoric high that is perfect for unwinding without heavy sedation.",
    "typeDetails": "Indica-dominant Hybrid",
    "genetics": "Black Cherry Soda x Querkle",
    "aromas": [
      "Floral",
      "Sweet",
      "Berry",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Pinene",
      "Caryophyllene"
    ]
  },
  "black-domina": {
    "description": "A potent, fast-flowering indica-dominant hybrid. It produces dark, dense, and resinous buds. The effect is heavily sedating and narcotic, making it a favorite for nighttime use to combat pain and insomnia. The aroma is peppery and earthy.",
    "typeDetails": "Indica 95% / Sativa 5%",
    "genetics": "Afghani x Ortega x Northern Lights x Hash Plant",
    "aromas": [
      "Pepper",
      "Earthy",
      "Spicy",
      "Pine"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Pinene"
    ]
  },
  "black-jack": {
    "description": "A hybrid strain that combines the uplifting effects of Jack Herer with the heavy resin production of Black Domina. It provides a long-lasting, blissful, and creative high that is both cerebrally stimulating and physically relaxing.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Black Domina x Jack Herer",
    "aromas": [
      "Earthy",
      "Pine",
      "Woody",
      "Sweet"
    ],
    "dominantTerpenes": [
      "Terpinolene",
      "Myrcene",
      "Ocimene"
    ]
  },
  "black-runtz": {
    "description": "A phenotype of the famous Runtz strain, distinguished by its exceptionally dark, almost black buds. It shares the same sweet, candy-like flavor profile and provides a euphoric, long-lasting high that relaxes the body and uplifts the mind.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Zkittlez x Gelato",
    "aromas": [
      "Sweet",
      "Fruity",
      "Candy",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Limonene",
      "Myrcene"
    ]
  },
  "black-tuna": {
    "description": "A potent indica-dominant hybrid created by Canadian breeders. It's known for its extremely pungent, fishy, and skunky aroma. The high is powerful and sedating, often leading to couch-lock, making it ideal for severe pain and insomnia.",
    "typeDetails": "Indica-dominant Hybrid",
    "genetics": "Herijuana x Lamb's Bread",
    "aromas": [
      "Pungent",
      "Skunk",
      "Earthy",
      "Diesel"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene"
    ]
  },
  "blackberry": {
    "description": "A well-balanced hybrid known for its delicious flavor of fresh blackberries. The high is relaxing and euphoric, providing a sense of happiness and well-being. It's effective for managing pain and stress while keeping the user functional.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Black Domina x Raspberry Cough",
    "aromas": [
      "Blackberry",
      "Sweet",
      "Fruity",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Limonene"
    ]
  },
  "blackberry-kush": {
    "description": "A strong indica-dominant strain with a sweet blackberry aroma mixed with Kush's classic fuel scent. It provides a potent, relaxing body high that is great for pain relief, stress reduction, and sleep.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Afghani x Blackberry",
    "aromas": [
      "Blackberry",
      "Sweet",
      "Earthy",
      "Diesel"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Limonene"
    ]
  },
  "blackwater": {
    "description": "An indica strain with deep purple buds and a sweet grape aroma. It starts with a euphoric head rush that melts into a calming, full-body buzz. It's highly effective for pain, appetite stimulation, and sleep.",
    "typeDetails": "Indica-dominant Hybrid",
    "genetics": "Mendo Purps x San Fernando Valley OG Kush",
    "aromas": [
      "Grape",
      "Sweet",
      "Earthy",
      "Pine"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Pinene"
    ]
  },
  "blue-cheese": {
    "description": "An indica-dominant hybrid famous for its unique flavor profile that combines the sweet, fruity notes of Blueberry with the savory, cheesy aroma of UK Cheese. The effect is deeply relaxing and calming, perfect for unwinding at the end of the day.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Blueberry x UK Cheese",
    "aromas": [
      "Cheese",
      "Blueberry",
      "Sweet",
      "Pungent"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Myrcene",
      "Limonene"
    ]
  },
  "blue-cookies": {
    "description": "A potent indica-dominant hybrid that delivers a crushing wave of euphoria followed by deep body relaxation. It has a sweet berry and cherry flavor with earthy undertones. Excellent for pain relief and relaxation.",
    "typeDetails": "Indica-dominant Hybrid",
    "genetics": "Girl Scout Cookies x Blueberry",
    "aromas": [
      "Berry",
      "Cherry",
      "Sweet",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Limonene",
      "Humulene"
    ]
  },
  "blue-diamond": {
    "description": "A potent indica-dominant hybrid that shines with a thick coat of trichomes. It provides a strong, long-lasting high that is both cerebrally uplifting and physically relaxing. The aroma is a mix of earthy pine and sweet berry.",
    "typeDetails": "Indica-dominant Hybrid",
    "genetics": "Diamond OG x Blue Dream",
    "aromas": [
      "Earthy",
      "Pine",
      "Berry",
      "Sweet"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Pinene",
      "Caryophyllene"
    ]
  },
  "blue-dream": {
    "description": "A legendary sativa-dominant hybrid from California. It offers a balanced high with gentle cerebral stimulation and full-body relaxation. Its sweet berry aroma makes it a favorite for both novice and experienced users. Great for daytime pain relief.",
    "typeDetails": "Sativa 60% / Indica 40%",
    "genetics": "Blueberry x Haze",
    "aromas": [
      "Blueberry",
      "Sweet",
      "Earthy",
      "Herbal"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Pinene",
      "Caryophyllene"
    ]
  },
  "blue-dream-cbd": {
    "description": "A CBD-rich version of the classic Blue Dream. It provides the same sweet berry aroma and gentle uplift but with significantly reduced psychoactivity due to the balanced 1:1 THC:CBD ratio. Ideal for therapeutic users seeking relief without a strong high.",
    "typeDetails": "Sativa-dominant Hybrid",
    "genetics": "Blue Dream x California Orange CBD",
    "aromas": [
      "Blueberry",
      "Sweet",
      "Citrus",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Pinene",
      "Caryophyllene"
    ]
  },
  "blue-dream-matic": {
    "description": "An autoflowering version of Blue Dream that offers the same beloved effects and flavors but in a faster, easier-to-grow package. The high is euphoric and uplifting, perfect for creative pursuits and daytime use.",
    "typeDetails": "Sativa-dominant Hybrid (Autoflower)",
    "genetics": "Blue Dream x Ruderalis",
    "aromas": [
      "Berry",
      "Sweet",
      "Earthy",
      "Citrus"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Pinene",
      "Caryophyllene"
    ]
  },
  "blue-gelato-41": {
    "description": "A potent indica-dominant hybrid from Barney's Farm. It combines the fruity flavors of Blueberry with the creamy sweetness of Gelato. The effect is clear-headed and energetic at first, followed by a comfortable body relaxation. Exceptionally high yielder outdoors.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Blueberry x Thin Mint GSC x Sunset Sherbet",
    "aromas": [
      "Berry",
      "Citrus",
      "Sweet",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Limonene",
      "Myrcene",
      "Caryophyllene"
    ]
  },
  "blue-hawaiian": {
    "description": "A sativa-dominant hybrid with a tropical, fruity flavor reminiscent of pineapple and berries. It provides a happy, euphoric high that is perfect for social situations and creative endeavors. The high is balanced with a light body relaxation.",
    "typeDetails": "Sativa-dominant Hybrid",
    "genetics": "Blueberry x Hawaiian Sativa",
    "aromas": [
      "Tropical",
      "Pineapple",
      "Berry",
      "Sweet"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Pinene",
      "Terpinolene"
    ]
  },
  "blue-magoo": {
    "description": "An indica-dominant hybrid known for its complex flavor profile of berry, fruit, and floral notes. It delivers a relaxing and euphoric high that is functional enough for daytime use but can be sedative in larger doses.",
    "typeDetails": "Indica-dominant Hybrid",
    "genetics": "DJ Short Blueberry x Major League Bud (Williams Wonder)",
    "aromas": [
      "Berry",
      "Fruity",
      "Floral",
      "Sweet"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Pinene"
    ]
  },
  "blue-power": {
    "description": "A potent indica-dominant hybrid that produces dense, trichome-covered buds. The aroma is a sweet and sour mix of berry and lemon. The high is powerful, starting with a euphoric lift and ending in deep relaxation.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "The Power x Master Kush x Blue Moonshine x Sour Double",
    "aromas": [
      "Berry",
      "Lemon",
      "Sweet",
      "Sour"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Limonene",
      "Caryophyllene"
    ]
  },
  "blue-walker": {
    "description": "A potent sativa-dominant hybrid with a unique fruity, sweet, and earthy aroma. It delivers a powerful, fast-acting cerebral high that is energetic and motivating, making it great for productivity and creative tasks.",
    "typeDetails": "Sativa 90% / Indica 10%",
    "genetics": "Blue Dream x Skywalker",
    "aromas": [
      "Fruity",
      "Sweet",
      "Earthy",
      "Berry"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Pinene",
      "Caryophyllene"
    ]
  },
  "blue-zushi": {
    "description": "A potent indica-dominant hybrid known for its beautiful appearance and complex flavor. It combines the fruity notes of Zkittlez with the kushy earthiness of Kush Mints. The high is relaxing and euphoric, perfect for unwinding.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Zkittlez x Kush Mints",
    "aromas": [
      "Fruity",
      "Earthy",
      "Spicy",
      "Sweet"
    ],
    "dominantTerpenes": [
      "Limonene",
      "Caryophyllene",
      "Linalool"
    ]
  },
  "blueberry": {
    "description": "A classic indica-dominant strain that won the High Times Cannabis Cup in 2000. It's famous for its unmistakable fresh blueberry aroma and flavor. The high is long-lasting, euphoric, and deeply relaxing.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Purple Thai x Afghani",
    "aromas": [
      "Blueberry",
      "Sweet",
      "Fruity",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Pinene"
    ]
  },
  "blueberry-haze": {
    "description": "A sativa-dominant hybrid that combines the sweet flavor of Blueberry with the cerebral effects of Haze. The high is uplifting, creative, and energetic, making it a great choice for daytime use and social activities.",
    "typeDetails": "Sativa 80% / Indica 20%",
    "genetics": "Blueberry x Haze",
    "aromas": [
      "Blueberry",
      "Sweet",
      "Haze",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Terpinolene",
      "Pinene"
    ]
  },
  "blueberry-og": {
    "description": "An indica-dominant hybrid that blends the sweet berry flavors of Blueberry with the classic earthy pine of OG Kush. It provides a balanced high that is both cerebrally uplifting and physically relaxing, effective for stress and pain.",
    "typeDetails": "Indica 70% / Sativa 30%",
    "genetics": "Blueberry x OG Kush",
    "aromas": [
      "Blueberry",
      "Earthy",
      "Pine",
      "Sweet"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Pinene",
      "Caryophyllene"
    ]
  },
  "booger": {
    "description": "A very potent indica-dominant hybrid with a funky, pungent aroma of skunk and diesel. The high is heavy and sedating, often leading to couch-lock and a strong case of the munchies. Best for experienced users and nighttime use.",
    "typeDetails": "Indica-dominant Hybrid",
    "genetics": "Bubba Kush x Strawberry Cough",
    "aromas": [
      "Pungent",
      "Skunk",
      "Diesel",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene"
    ]
  },
  "bruce-banger": {
    "description": "A potent sativa-dominant hybrid that combines the power of Bruce Banner with the classic flavor of OG Kush. The high is fast-acting, euphoric, and energetic, sparking creativity and focus. The flavor is a mix of diesel and sweet citrus.",
    "typeDetails": "Sativa-dominant Hybrid",
    "genetics": "Bruce Banner x OG Kush",
    "aromas": [
      "Diesel",
      "Sweet",
      "Citrus",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Limonene",
      "Caryophyllene"
    ]
  },
  "bruce-banner": {
    "description": "Named after the Hulk's alter ego, this is a powerhouse sativa-dominant hybrid. It's known for its incredibly high THC content and a fast-acting, euphoric, and creative high that eventually settles into a state of relaxation. The aroma is a strong mix of diesel and sweet berry.",
    "typeDetails": "Sativa 60% / Indica 40%",
    "genetics": "OG Kush x Strawberry Diesel",
    "aromas": [
      "Diesel",
      "Sweet",
      "Berry",
      "Pungent"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Limonene",
      "Caryophyllene"
    ]
  },
  "bubba-fett": {
    "description": "A potent indica-dominant hybrid named after the Star Wars bounty hunter. It provides a heavy, relaxing body high that can 'trap' you in carbonite-like relaxation. The aroma is earthy and pungent with sweet undertones.",
    "typeDetails": "Indica-dominant Hybrid",
    "genetics": "Stardawg x Pre-98 Bubba Kush",
    "aromas": [
      "Earthy",
      "Pungent",
      "Sweet",
      "Diesel"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Limonene",
      "Caryophyllene"
    ]
  },
  "bubba-kush": {
    "description": "A classic indica strain known for its heavy tranquilizing effects. It has a sweet, hashy flavor with notes of chocolate and coffee. The high is deeply relaxing, often leading to sleepiness. A favorite for pain and insomnia relief.",
    "typeDetails": "Indica 90% / Sativa 10%",
    "genetics": "Possibly OG Kush x Northern Lights",
    "aromas": [
      "Earthy",
      "Sweet",
      "Coffee",
      "Chocolate"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Limonene",
      "Myrcene"
    ]
  },
  "bubble-gum": {
    "description": "An award-winning hybrid famous for its distinct sweet smell and flavor, just like classic bubble gum. It provides a balanced high that is euphoric and uplifting, followed by a gentle body relaxation. Great for creative tasks and stress relief.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Indiana Bubblegum",
    "aromas": [
      "Sweet",
      "Bubble Gum",
      "Fruity",
      "Floral"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Pinene"
    ]
  },
  "cactus-breath": {
    "description": "A potent indica-dominant hybrid with a unique pungent aroma combining diesel, spice, and earth. The high is powerfully relaxing and euphoric, often leading to a heavy body sensation and deep calm. Best for experienced users.",
    "typeDetails": "Indica-dominant Hybrid",
    "genetics": "Cactus x Mendo Breath",
    "aromas": [
      "Pungent",
      "Diesel",
      "Spicy",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene"
    ]
  },
  "cactus-cooler": {
    "description": "A sativa-dominant hybrid with a bright, refreshing flavor profile of citrus and tropical fruit. The high is energetic and uplifting, perfect for daytime activities, boosting creativity, and enhancing mood.",
    "typeDetails": "Sativa-dominant Hybrid",
    "genetics": "Blue Dream x OG Kush",
    "aromas": [
      "Citrus",
      "Tropical",
      "Pineapple",
      "Sweet"
    ],
    "dominantTerpenes": [
      "Terpinolene",
      "Myrcene"
    ]
  },
  "cake-bomb": {
    "description": "An indica-dominant hybrid that produces dense, frosty buds with a sweet, cake-like aroma. The high is deeply relaxing and calming, making it an excellent choice for evening use to relieve stress and pain.",
    "typeDetails": "Indica-dominant Hybrid",
    "genetics": "Do-Si-Dos x PCS1",
    "aromas": [
      "Sweet",
      "Cake",
      "Earthy",
      "Vanilla"
    ],
    "dominantTerpenes": [
      "Limonene",
      "Caryophyllene",
      "Myrcene"
    ]
  },
  "cali-o": {
    "description": "A classic 50/50 hybrid, also known as California Orange. It's famous for its strong, sweet orange aroma. The high is clear-headed, uplifting, and happy, making it a great strain for social settings and creative work.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "California Landrace",
    "aromas": [
      "Orange",
      "Citrus",
      "Sweet",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Pinene",
      "Caryophyllene"
    ]
  },
  "candy-jack": {
    "description": "A sativa-dominant hybrid that combines the best of two legendary strains. It has a sweet, citrusy aroma and provides a powerful, uplifting cerebral high that is energetic and creative. Great for combating fatigue and depression.",
    "typeDetails": "Sativa 80% / Indica 20%",
    "genetics": "Jack Herer x Skunk #1",
    "aromas": [
      "Sweet",
      "Citrus",
      "Earthy",
      "Skunk"
    ],
    "dominantTerpenes": [
      "Terpinolene",
      "Myrcene",
      "Pinene"
    ]
  },
  "candyland": {
    "description": "A sativa-dominant hybrid with a sweet candy flavor and earthy undertones. The high is uplifting and stimulating, perfect for social gatherings and creative activities. It can also provide effective pain relief without heavy sedation.",
    "typeDetails": "Sativa 70% / Indica 30%",
    "genetics": "Granddaddy Purple x Bay Platinum Cookies",
    "aromas": [
      "Sweet",
      "Candy",
      "Earthy",
      "Spicy"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Limonene",
      "Humulene"
    ]
  },
  "cannatonic": {
    "description": "A famous CBD-rich hybrid strain, often with a near 1:1 THC to CBD ratio. It provides a mellow, relaxing high that is short-lived and primarily physical, making it excellent for treating pain, anxiety, and muscle spasms without intense psychoactivity.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "MK Ultra x G13 Haze",
    "aromas": [
      "Earthy",
      "Woody",
      "Citrus",
      "Sweet"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Pinene",
      "Caryophyllene"
    ]
  },
  "cap-junky": {
    "description": "A highly potent hybrid known for its intense, pungent aroma of sour fruit and gasoline. The high is strong and long-lasting, delivering a wave of euphoria and creativity that eventually settles into a state of deep relaxation. For experienced users.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Alien Cookies x Kush Mints #11",
    "aromas": [
      "Pungent",
      "Diesel",
      "Sour",
      "Fruity"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Limonene",
      "Myrcene"
    ]
  },
  "captains-cake": {
    "description": "A sativa-dominant hybrid with a sweet, fruity, and slightly sour aroma. The high is uplifting and energetic, providing a burst of creativity and focus that makes it a great choice for daytime use.",
    "typeDetails": "Sativa-dominant Hybrid",
    "genetics": "Girl Scout Cookies x White Fire Alien OG",
    "aromas": [
      "Sweet",
      "Fruity",
      "Sour",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Limonene",
      "Caryophyllene",
      "Myrcene"
    ]
  },
  "carbon-fiber": {
    "description": "A potent and rare indica-dominant hybrid. It has a complex aroma profile combining notes of grape, citrus, and diesel. The high is deeply relaxing and sedating, often leading to a blissful couch-lock.",
    "typeDetails": "Indica-dominant Hybrid",
    "genetics": "Grape Pie x Biscotti x Cookies and Cream",
    "aromas": [
      "Grape",
      "Diesel",
      "Citrus",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Limonene",
      "Caryophyllene"
    ]
  },
  "casey-jones": {
    "description": "A sativa-dominant hybrid named after the famous train engineer. It's known for its fast-acting, uplifting, and creative high. The aroma is earthy and sweet with notes of citrus. A great strain for productivity and daytime enjoyment.",
    "typeDetails": "Sativa 80% / Indica 20%",
    "genetics": "Trainwreck x Sour Diesel x Thai",
    "aromas": [
      "Earthy",
      "Sweet",
      "Citrus",
      "Diesel"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Limonene"
    ]
  },
  "cat-piss": {
    "description": "Despite its unfortunate name, this is a classic sativa-dominant strain with a pungent, skunky, and ammonia-like aroma. The high is energetic, euphoric, and very cerebral, making it a favorite among sativa lovers for its clear-headed effects.",
    "typeDetails": "Sativa-dominant Hybrid",
    "genetics": "Super Silver Haze phenotype",
    "aromas": [
      "Pungent",
      "Ammonia",
      "Skunk",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Terpinolene",
      "Myrcene"
    ]
  },
  "cataract-kush": {
    "description": "A potent indica-dominant hybrid known for its heavy, sedating effects. The high is a creeper, slowly building into a powerful full-body relaxation that can be overwhelming for novices. It has a pungent, fruity, and skunky aroma.",
    "typeDetails": "Indica-dominant Hybrid",
    "genetics": "LA Confidential x OG Kush",
    "aromas": [
      "Pungent",
      "Fruity",
      "Skunk",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Limonene",
      "Caryophyllene"
    ]
  },
  "cbd-critical-cure": {
    "description": "A CBD-rich indica-dominant strain bred for therapeutic use. It has a sweet, earthy flavor and provides a gentle, calming effect with minimal psychoactivity. It's highly effective for treating pain, inflammation, and anxiety.",
    "typeDetails": "Indica-dominant Hybrid",
    "genetics": "Critical Kush x Shanti Baba's CBD-enhanced strain",
    "aromas": [
      "Earthy",
      "Sweet",
      "Woody"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Pinene",
      "Caryophyllene"
    ]
  },
  "cbd-therapy": {
    "description": "A groundbreaking strain bred specifically for high CBD and low THC content. It's ideal for patients who need the medical benefits of cannabis without the high. The effect is clear-headed and calming. The aroma is a mix of fruity and earthy notes.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Undisclosed",
    "aromas": [
      "Fruity",
      "Earthy",
      "Sweet"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene"
    ]
  },
  "cereal-a-la-mode": {
    "description": "A potent and flavorful hybrid from the Cookies family. It has a sweet, creamy, and fruity aroma reminiscent of a bowl of cereal. The high is well-balanced, providing a euphoric and creative head high alongside a relaxing body buzz.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Cereal Milk x Georgia Pie",
    "aromas": [
      "Sweet",
      "Creamy",
      "Fruity",
      "Vanilla"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Limonene"
    ]
  },
  "cereal-milk": {
    "description": "A balanced hybrid strain from Cookies known for its unique creamy and fruity flavor, like the milk at the bottom of a bowl of sugary cereal. The high is blissful and creative, making it great for a relaxed yet productive day.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "(Y Life x Snowman) x GSC",
    "aromas": [
      "Sweet",
      "Creamy",
      "Berry",
      "Vanilla"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Limonene"
    ]
  },
  "charlottes-web": {
    "description": "A world-famous high-CBD, low-THC strain. It gained prominence for its effectiveness in treating severe epilepsy. It produces no psychoactive high, making it a purely medicinal strain for a wide range of conditions.",
    "typeDetails": "Sativa-dominant Hybrid",
    "genetics": "Hemp x Unknown strain",
    "aromas": [
      "Earthy",
      "Pine",
      "Floral"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Pinene",
      "Caryophyllene"
    ]
  },
  "cheese": {
    "description": "A legendary indica-dominant hybrid that originated in the UK. It's famous for its pungent, cheesy, and skunky aroma. The high is powerful, providing a happy, relaxing feeling that can also be quite euphoric and uplifting.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Skunk #1 phenotype",
    "aromas": [
      "Cheese",
      "Pungent",
      "Skunk",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Myrcene",
      "Limonene"
    ]
  },
  "cheesecake": {
    "description": "An indica-dominant hybrid with a sweet, cheesy, and creamy flavor profile. The high is relaxing and euphoric, perfect for unwinding after a long day and stimulating the appetite. It's effective for stress, pain, and lack of appetite.",
    "typeDetails": "Indica-dominant Hybrid",
    "genetics": "Cheese x an unknown indica",
    "aromas": [
      "Cheese",
      "Sweet",
      "Creamy",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Limonene",
      "Myrcene"
    ]
  },
  "cheetah-piss": {
    "description": "A potent hybrid with a very pungent, ammonia-like aroma similar to Cat Piss, but with added citrus and diesel notes. The high is fast-acting and giggly, providing a wave of euphoria and creativity that's great for social settings.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Lemonnade x Gelato 42 x London Poundcake 97",
    "aromas": [
      "Pungent",
      "Ammonia",
      "Citrus",
      "Diesel"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Limonene"
    ]
  },
  "chem-sis": {
    "description": "A sativa-dominant phenotype of the legendary Chemdawg. It's known for its pungent diesel and chemical aroma. The high is powerfully cerebral, energetic, and creative, making it a favorite among experienced sativa lovers.",
    "typeDetails": "Sativa-dominant Hybrid",
    "genetics": "Chemdawg phenotype",
    "aromas": [
      "Diesel",
      "Chemical",
      "Pungent",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Limonene",
      "Myrcene"
    ]
  },
  "chemdawg": {
    "description": "A legendary strain of mysterious origin, Chemdawg is the parent of many famous strains like OG Kush and Sour Diesel. It's known for its distinct, pungent diesel aroma and a very potent, cerebral high that is creative and uplifting.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Unknown",
    "aromas": [
      "Diesel",
      "Chemical",
      "Pungent",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Myrcene",
      "Limonene"
    ]
  },
  "chemdog-millionaire": {
    "description": "A potent indica-dominant hybrid with a complex aroma of earth, fuel, and citrus. It delivers a powerful, long-lasting high that is both cerebrally euphoric and deeply relaxing physically. Great for pain and stress relief.",
    "typeDetails": "Indica-dominant Hybrid",
    "genetics": "Chemdawg x Gupta Kush",
    "aromas": [
      "Earthy",
      "Diesel",
      "Citrus",
      "Pungent"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Limonene",
      "Caryophyllene"
    ]
  },
  "cherry-ak-47": {
    "description": "A phenotype of the classic AK-47, selected for its distinct cherry aroma. It retains the balanced, uplifting high of the original but adds a sweet, fruity twist. The effect is creative, happy, and relaxing.",
    "typeDetails": "Sativa-dominant Hybrid",
    "genetics": "AK-47 phenotype",
    "aromas": [
      "Cherry",
      "Sweet",
      "Earthy",
      "Skunk"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Pinene",
      "Caryophyllene"
    ]
  },
  "cherry-pie": {
    "description": "An indica-dominant hybrid with a delightful aroma of sweet and sour cherry pie. The high is well-balanced, starting with an uplifting cerebral buzz that gently fades into a state of happy relaxation. Great for stress relief.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Granddaddy Purple x Durban Poison",
    "aromas": [
      "Cherry",
      "Sweet",
      "Earthy",
      "Berry"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Pinene"
    ]
  },
  "chiquita-banana": {
    "description": "A potent hybrid known for its incredibly high THC levels and a strong banana flavor. The high is powerful and euphoric, starting with a cerebral rush that gives way to deep physical relaxation. Best for experienced users.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "OG Kush x Banana",
    "aromas": [
      "Banana",
      "Sweet",
      "Tropical",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Limonene",
      "Myrcene",
      "Caryophyllene"
    ]
  },
  "cinderella-99": {
    "description": "Also known as Cindy 99. A sativa-dominant hybrid famous for its fast flowering time and a dreamy, euphoric, and uplifting high. It has a sweet, fruity flavor with tropical notes. An excellent daytime strain for creativity and mood enhancement.",
    "typeDetails": "Sativa 85% / Indica 15%",
    "genetics": "Jack Herer x Shiva Skunk",
    "aromas": [
      "Sweet",
      "Fruity",
      "Tropical",
      "Citrus"
    ],
    "dominantTerpenes": [
      "Limonene",
      "Myrcene",
      "Caryophyllene"
    ]
  },
  "citradelic-sunset": {
    "description": "A sativa-dominant hybrid with a vibrant citrus and sour aroma. It delivers a powerful, uplifting, and energetic high that is perfect for daytime use. It's known to spark creativity and provide a long-lasting euphoric experience.",
    "typeDetails": "Sativa-dominant Hybrid",
    "genetics": "Ghost Train Haze x Mandarin Sunset",
    "aromas": [
      "Citrus",
      "Sour",
      "Sweet",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Terpinolene",
      "Myrcene"
    ]
  },
  "colt-45": {
    "description": "A potent sativa-dominant hybrid with a complex aroma combining gassy, earthy, and floral notes. The high is powerful and cerebral, providing a surge of energy and euphoria that is great for creative projects and social settings.",
    "typeDetails": "Sativa-dominant Hybrid",
    "genetics": "Gelato 45 x Slurricane",
    "aromas": [
      "Gassy",
      "Earthy",
      "Floral",
      "Pungent"
    ],
    "dominantTerpenes": [
      "Limonene",
      "Caryophyllene"
    ]
  },
  "congo": {
    "description": "A pure sativa landrace strain known for its clear, energetic, and long-lasting high. It provides a stimulating and creative buzz without the anxiety sometimes associated with strong sativas. The aroma is a sweet and fruity mix.",
    "typeDetails": "Sativa 100%",
    "genetics": "Congo Landrace",
    "aromas": [
      "Sweet",
      "Fruity",
      "Spicy",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Terpinolene"
    ]
  },
  "cookies-and-cream": {
    "description": "A well-balanced hybrid that won the Hybrid category of the 2014 Denver Cannabis Cup. It has a sweet vanilla and nutty flavor. The high is happy and relaxing, providing long-lasting relief from stress and pain.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Starfighter x an unknown GSC phenotype",
    "aromas": [
      "Sweet",
      "Vanilla",
      "Nutty",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Limonene",
      "Myrcene"
    ]
  },
  "1024": {
    "description": "A very potent and high-yielding Sativa from Medical Seeds with a complex sweet-sour, fruity aroma. The effect is strongly cerebral, almost psychedelic, and very long-lasting. Promotes creativity and euphoria.",
    "typeDetails": "Sativa 70% / Indica 30%",
    "genetics": "Secret genetics",
    "aromas": [
      "Sweet",
      "Fruity",
      "Spicy",
      "Incense"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Pinene",
      "Caryophyllene"
    ]
  },
  "24k-gold": {
    "description": "Also known as Kosher Tangie. An indica-dominant hybrid that combines the sweet citrus flavor of Tangie with the relaxing power of Kosher Kush. Has a cheerful and relaxing effect, ideal for stress and pain. The plants often develop beautiful golden hues.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Kosher Kush x Tangie",
    "aromas": [
      "Citrus",
      "Orange",
      "Skunk",
      "Sweet"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Limonene",
      "Caryophyllene"
    ]
  },
  "303-og": {
    "description": "A Colorado favorite, 303 OG delivers a classic OG experience with a potent, sour diesel aroma. Its effects are balanced, starting with a strong cerebral rush that melts into a gentle, relaxing body buzz. Ideal for unwinding in the afternoon or evening without complete sedation.",
    "typeDetails": "Indica 70% / Sativa 30%",
    "genetics": "Pre-98 Bubba Kush x Chemdawg",
    "aromas": [
      "Diesel",
      "Sour",
      "Earthy",
      "Pungent"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Limonene"
    ]
  },
  "501st-og": {
    "description": "A potent Indica hybrid with an earthy, piney aroma and notes of grape. The effect is strongly physical and cerebrally relaxing, almost sedating. Ideal for relieving pain, stress, and insomnia.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Skywalker OG x Rare Dankness #1",
    "aromas": [
      "Grape",
      "Earthy",
      "Pine",
      "Sweet"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Pinene",
      "Caryophyllene"
    ]
  },
  "707-headband": {
    "description": "A popular Californian hybrid with a sour, lemony aroma and earthy undertones. The effect is fast-acting, cerebral, and euphoric, often accompanied by a noticeable pressure around the head, hence the name 'Headband'. Very effective for pain and stress.",
    "typeDetails": "Sativa 70% / Indica 30%",
    "genetics": "Sour Diesel x OG Kush x Master Kush",
    "aromas": [
      "Lemon",
      "Diesel",
      "Earthy",
      "Sour",
      "Pine"
    ],
    "dominantTerpenes": [
      "Caryophyllene",
      "Limonene",
      "Myrcene"
    ]
  },
  "8-ball-kush": {
    "description": "A pure Indica from the Hindu Kush mountains, bred by Barney's Farm. It offers a deeply relaxing, almost narcotic effect. The aroma is earthy and spicy. Ideal for evening use and pain relief.",
    "typeDetails": "Indica 100%",
    "genetics": "Afghani Landrace",
    "aromas": [
      "Earthy",
      "Spicy",
      "Herbal",
      "Woody"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Caryophyllene",
      "Pinene"
    ]
  },
  "9-pound-hammer": {
    "description": "A heavy Indica hybrid with a fruity, lime-like taste. The effect is very potent and long-lasting, leading to deep physical relaxation and often sleepiness. Well-suited for pain and insomnia.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Gooberry x Hells OG x Jack the Ripper",
    "aromas": [
      "Grape",
      "Lime",
      "Sweet",
      "Earthy"
    ],
    "dominantTerpenes": [
      "Myrcene",
      "Pinene",
      "Caryophyllene"
    ]
  }
}
