// This file is generated by the translation script. Do not edit manually.
export const strainsData = {
  "acdc": {
    "description": "Eine berühmte CBD-dominante Sorte, gezüchtet für therapeutische Zwecke ohne starke psychoaktive Wirkung. Der Name steht für 'Alternative Cannabinoid Dietary Cannabis'. Wirkt entspannend und angstlösend, während der Geist klar bleibt. Ideal bei Schmerzen und Angstzuständen.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Cannatonic x Ruderalis",
    "aromas": [
      "Erdig",
      "Süß",
      "Holzig",
      "Kiefer",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "acapulco-gold": {
    "description": "Eine legendäre Landrassen-Sorte aus Acapulco, Mexiko, berühmt seit den 1960ern. Bekannt für ihre gold-braunen Knospen und eine energetisierende, euphorische und motivierende Wirkung. Der Geschmack erinnert an süßes, erdiges Toffee. Eine klassische 'Wake-and-Bake'-Sorte.",
    "typeDetails": "Sativa 80% / Indica 20%",
    "genetics": "Mexikanische Landrasse",
    "aromas": [
      "Erdig",
      "Süß",
      "Zitrus",
      "Kiefer",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Myrcen",
      "Limonen"
    ]
  },
  "acid-dough": {
    "description": "Eine preisgekrönte sativa-dominante Sorte von Ripper Seeds. Bietet einen schnell einsetzenden, euphorischen und kichernden Rausch, der den Geist beflügelt und den Körper leicht entspannt. Die Knospen sind dicht, dunkelgrün mit orangefarbenen Haaren und violetten Trichomen.",
    "typeDetails": "Sativa 80% / Indica 20%",
    "genetics": "Lilly (Queen Mother x Congo) x OG Badazz",
    "aromas": [
      "Süß-sauer",
      "Tropisch",
      "Ananas",
      "Erdig",
      "Bonbon"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Limonen"
    ]
  },
  "afghan-kush": {
    "description": "Eine Indica-Landrasse aus dem Hindukusch-Gebirge. Bekannt für ihre starke, fast narkotische Körperwirkung und hohe Harzproduktion, was sie ideal für die Haschischherstellung macht. Wirkt tief entspannend und sedierend. Ideal für den Abend und bei Schmerzen oder Schlaflosigkeit.",
    "typeDetails": "Indica 100%",
    "genetics": "Hindukusch Landrasse",
    "aromas": [
      "Erdig",
      "Würzig",
      "Kiefer",
      "Holzig",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "afghan-skunk": {
    "description": "Eine klassische indica-dominante Hybride, die die robuste Natur und die entspannende Wirkung von Afghani mit dem hohen Ertrag und dem scharfen Aroma von Skunk #1 kombiniert. Sie bietet eine tief entspannende Körperwirkung und ist bekannt für ihre einfache Handhabung und Widerstandsfähigkeit.",
    "typeDetails": "Indica 85% / Sativa 15%",
    "genetics": "Afghani x Skunk #1",
    "aromas": [
      "Skunk",
      "Erdig",
      "Süß",
      "Scharf"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "afghani": {
    "description": "Eine fundamentale Landrasse aus Afghanistan, die die genetische Grundlage für viele moderne Indicas bildet. Bietet eine tief entspannende und sedierende Wirkung, die Stress abbaut und bei Schlaflosigkeit hilft. Das Aroma ist erdig, süß und skunkig.",
    "typeDetails": "Indica 100%",
    "genetics": "Afghanische Landrasse",
    "aromas": [
      "Erdig",
      "Süß",
      "Skunk",
      "Würzig",
      "Kiefer"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "afgoo": {
    "description": "Auch bekannt als Afgooey. Eine potente indica-dominante Sorte, die für ihre extrem harzigen, klebrigen Knospen bekannt ist. Die Wirkung ist stark körperlich entspannend, fast sedierend, und führt zu einem euphorischen, glücklichen Zustand. Ideal für den Abendgebrauch bei Stress und Schlaflosigkeit.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Afghani x Maui Haze",
    "aromas": [
      "Erdig",
      "Kiefer",
      "Süß",
      "Würzig",
      "Holzig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen",
      "Ocimen"
    ]
  },
  "agent-orange": {
    "description": "Gezüchtet von MzJill Genetics. Bekannt für ihr intensives Zitrus- und Orangenaroma. Die Wirkung ist energetisierend, erhebend und kreativ, was sie zu einer ausgezeichneten Wahl für den Tag und soziale Anlässe macht. Hilft bei Müdigkeit und Depressionen.",
    "typeDetails": "Sativa 75% / Indica 25%",
    "genetics": "Orange Velvet x Jack The Ripper",
    "aromas": [
      "Orange",
      "Zitrus",
      "Süß",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Terpinolen",
      "Caryophyllen"
    ]
  },
  "agent-x": {
    "description": "Eine moderne, ausgewogene Hybride von Alien Labs (2022). Bietet ein komplexes Aroma von Apfel, Käse und Asphalt mit blumigen Noten. Die Wirkung ist stark, aber ausgewogen, mit einem erhebenden Kopf-High und einem entspannten Körpergefühl. Ideal für erfahrene Konsumenten.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Atomic Apple x Xeno #1",
    "aromas": [
      "Apfel",
      "Käse",
      "Diesel",
      "Blumig",
      "Minze"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Linalool"
    ]
  },
  "ak-47": {
    "description": "Eine legendäre, preisgekrönte Sorte von Serious Seeds (1992). Trotz des Namens ist die Wirkung sanft, erhebend und zerebral, gefolgt von einer milden Körperentspannung. Ideal für kreative und soziale Aktivitäten. Das Aroma ist erdig, süß und blumig.",
    "typeDetails": "Sativa 65% / Indica 35%",
    "genetics": "Kolumbianisch x Mexikanisch x Thailändisch x Afghanisch",
    "aromas": [
      "Erdig",
      "Süß",
      "Blumig",
      "Holzig",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "alaskan-ice": {
    "description": "Eine extrem potente sativa-dominante Sorte von Greenhouse Seed Co. Bietet einen sofortigen, erhebenden und euphorischen Rausch, der langsam in eine entspannende Körperwirkung übergeht. Bekannt für ihre hohe Harzproduktion, ideal für Extrakte.",
    "typeDetails": "Sativa 70% / Indica 30%",
    "genetics": "White Widow x Haze",
    "aromas": [
      "Würzig",
      "Holzig",
      "Erdig",
      "Pfeffer",
      "Sandelholz"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Limonen",
      "Pinen"
    ]
  },
  "alaskan-purple": {
    "description": "Eine robuste und ertragreiche Sorte, die bei kühleren Temperaturen schöne violette Farben entwickelt. Die indica-dominante Wirkung ist körperlich entspannend (Kush-Einfluss) mit einer zerebralen, erhebenden Note (Sativa-Einfluss). Das Aroma ist süß und beerig mit blumigen Noten.",
    "typeDetails": "Indica 70% / Sativa 30%",
    "genetics": "(Purple Alaskan x Kush) x Brasilianische Sativa",
    "aromas": [
      "Beere",
      "Süß",
      "Blumig",
      "Erdig",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Linalool"
    ]
  },
  "alaskan-thunder-fuck": {
    "description": "Alias: ATF. Eine legendäre Sativa aus dem Matanuska Valley in Alaska. Bekannt für einen intensiven, euphorischen und energetisierenden Rausch, der die Kreativität fördert. Das Aroma ist eine komplexe Mischung aus Kiefer, Zitrone, Menthol und Skunk.",
    "typeDetails": "Sativa 70% / Indica 30%",
    "genetics": "(Nordkalifornische Sativa x Russische Ruderalis) x Afghanisch",
    "aromas": [
      "Kiefer",
      "Zitrone",
      "Menthol",
      "Erdig",
      "Skunk"
    ],
    "dominantTerpenes": [
      "Pinen",
      "Linalool",
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "alien-dawg": {
    "description": "Eine reine Indica, die für ihr saures, dieselartiges Aroma und ihre potente, entspannende Wirkung bekannt ist. Sie ist eine der Elternsorten von Alien Kush und bietet eine starke zerebrale Wirkung, die in eine tiefe Körperentspannung übergeht.",
    "typeDetails": "Indica 100%",
    "genetics": "Chemdawg x Alien Technology",
    "aromas": [
      "Sauer",
      "Diesel",
      "Erdig",
      "Scharf",
      "Kiefer"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "alien-kush": {
    "description": "Eine ausgewogene Hybride mit einem würzigen, erdigen und kiefernartigen Aroma. Sie bietet eine klare, zerebrale Wirkung, die in eine sanfte Körperentspannung übergeht. Bekannt für ihre 'außerirdische' anmutende Wirkung, die die Wahrnehmung leicht verändern kann.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Las Vegas Purple Kush x Alien Dawg",
    "aromas": [
      "Würzig",
      "Erdig",
      "Kiefer",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "alien-og": {
    "description": "Auch bekannt als Alien OG Kush. Eine hochpotente Hybride, die für ihren intensiven, fast psychedelischen zerebralen Rausch in Kombination mit einer schweren Körperwirkung bekannt ist. Ideal für erfahrene Konsumenten. Das Aroma ist eine klassische OG-Mischung aus Zitrone, Kiefer und Erde.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Tahoe OG x Alien Kush",
    "aromas": [
      "Kiefer",
      "Zitrone",
      "Erdig",
      "Süß",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "alien-rock-candy": {
    "description": "Eine potente indica-dominante Sorte mit einem süßen, bonbonartigen Geschmacksprofil, das durch saure und erdige Noten ergänzt wird. Die Wirkung ist stark entspannend und sedierend, ideal zur Linderung von Schmerzen, Stress und Schlaflosigkeit am Ende des Tages.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Sour Dubble x Tahoe Alien",
    "aromas": [
      "Süß",
      "Beere",
      "Zitrus",
      "Sauer",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen",
      "Nerolidol"
    ]
  },
  "american-dream": {
    "description": "Eine schnell blühende, ertragreiche Sorte von Sensi Seeds. Bietet eine euphorische, gesellige und entspannende Wirkung ohne starken 'Couch-Lock'. Das Aroma ist erdig und skunkig mit frischen, tropisch-fruchtigen Noten. Ideal für kommerzielle Züchter und Anfänger.",
    "typeDetails": "Indica 75% / Sativa 25%",
    "genetics": "Afghan Skunk x (Jamaikanisch x Hawaiianisch)",
    "aromas": [
      "Erdig",
      "Skunk",
      "Kiefer",
      "Fruchtig",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen",
      "Limonen"
    ]
  },
  "amnesia": {
    "description": "Eine legendäre Sorte, die in den Amsterdamer Coffeeshops berühmt wurde. Bekannt für einen starken, zerebralen, euphorischen und energetisierenden Rausch. Trotz des Namens fördert sie die Kreativität und Geselligkeit. Das Aroma ist erdig mit süßen Zitrusnoten.",
    "typeDetails": "Sativa 70% / Indica 30%",
    "genetics": "Unbekannt (oft mit Skunk, Cinderella 99, Jack Herer assoziiert)",
    "aromas": [
      "Zitrus",
      "Erdig",
      "Süß",
      "Blumig",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Humulen",
      "Ocimen",
      "Terpinolen"
    ]
  },
  "amnesia-haze": {
    "description": "Eine mehrfache Cannabis-Cup-Gewinnerin, berühmt für ihre potente, langanhaltende und fast psychedelische zerebrale Wirkung. Fördert Energie, Euphorie und Kreativität. Das Aroma ist eine komplexe Mischung aus Zitrone, Zitrusfrüchten, Erde und Gewürzen.",
    "typeDetails": "Sativa 80% / Indica 20%",
    "genetics": "Diverse Landrassen (Südasiatisch, Jamaikanisch, etc.)",
    "aromas": [
      "Zitrus",
      "Zitrone",
      "Erdig",
      "Würzig",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "amnesia-lemon": {
    "description": "Eine preisgekrönte Sorte (Cannabis Cup 2004), die für ihren intensiven Zitrus- und Zitronengeschmack bekannt ist. Die Wirkung ist erhebend, zerebral und energetisierend, typisch für eine Sativa, aber mit einer entspannenden körperlichen Komponente. Ideal für den Tagesgebrauch.",
    "typeDetails": "Sativa 60% / Indica 40%",
    "genetics": "Amnesia Haze x Lemon Skunk",
    "aromas": [
      "Zitrone",
      "Zitrus",
      "Süß",
      "Würzig",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Ocimen",
      "Terpinolen",
      "Limonen"
    ]
  },
  "animal-cookies": {
    "description": "Eine potente, indica-dominante Hybride, die eine schwere Ganzkörperentspannung bietet, die ideal zur Linderung von Schmerzen und Schlaflosigkeit ist. Sie hat ein süßes, saures Aroma mit schweren, erdigen Noten.",
    "typeDetails": "Indica 75% / Sativa 25%",
    "genetics": "GSC x Fire OG",
    "aromas": [
      "Süß",
      "Sauer",
      "Erdig",
      "Nussig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "animal-mints": {
    "description": "Gezüchtet von Seed Junky Genetics. Eine hochpotente Hybride mit einem komplexen Aroma von Minze, Keksteig, Vanille und einem Hauch Diesel. Die Wirkung ist stark und ausgewogen, beginnend mit einem euphorischen Kopf-High, das in eine tiefe, sedierende Körperentspannung übergeht.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Animal Cookies x SinMint Cookies (oder andere GSC-Kreuzungen)",
    "aromas": [
      "Minze",
      "Süß",
      "Keksteig",
      "Erdig",
      "Diesel"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen",
      "Pinen"
    ]
  },
  "appalachian-kush": {
    "description": "Eine potente Hybride mit einem erdigen, süßen und leicht würzigen Aroma. Sie bietet eine ausgewogene Wirkung, die mit einem zerebralen, energetischen Schub beginnt und in eine entspannende Körperwirkung übergeht. Ideal zur Linderung von Stress und Schmerzen, ohne völlig zu sedieren.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Green Crack x Tres Dawg",
    "aromas": [
      "Erdig",
      "Süß",
      "Würzig",
      "Kiefer"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Limonen"
    ]
  },
  "apple-betty": {
    "description": "Eine potente Hybride mit einem köstlichen Geschmacksprofil, das an gebackenen Apfelkuchen mit Zimt- und Schokoladennoten erinnert. Die Wirkung ist schnell einsetzend, euphorisch und kichernd, fast psychedelisch, gefolgt von einer tiefen Körperentspannung.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Sour Apple x Animal Cookies (oder Chem's Sister x Sour Apple x Chocolate Diesel)",
    "aromas": [
      "Apfel",
      "Süß",
      "Erdig",
      "Gebäck",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Humulen"
    ]
  },
  "apple-cobbler": {
    "description": "Eine ausgewogene Hybride mit einem fruchtigen, säuerlichen Geschmacksprofil von Apfel und Erde. Die Wirkung setzt langsam ein, beginnend mit einem zerebralen Auftrieb, der die Stimmung und Kreativität fördert, und geht in eine beruhigende Körperentspannung über. Ideal für Stress- und Schmerzabbau.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Blueberry Moonshine x Sour Apple (oder Sour Apple x Animal Cookies)",
    "aromas": [
      "Apfel",
      "Süß",
      "Erdig",
      "Kiefer",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Linalool"
    ]
  },
  "apple-fritter": {
    "description": "Eine extrem potente Hybride, die für ihren hohen THC-Gehalt und ihren köstlichen Geschmack nach süßem Apfelgebäck bekannt ist. Die Wirkung ist stark und ausgewogen, beginnend mit einem euphorischen und kreativen Rausch, der in eine tief entspannende Körperwirkung übergeht.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Sour Apple x Animal Cookies",
    "aromas": [
      "Apfel",
      "Süß",
      "Erdig",
      "Gebäck",
      "Vanille"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Humulen",
      "Pinen"
    ]
  },
  "apple-jack": {
    "description": "Eine potente Hybride, die erhebende und beruhigende Effekte bietet. Ideal zur Behandlung von chronischen Schmerzen oder Übelkeit. Das Geschmacksprofil ist skunkig und erdig mit Untertönen von geschnittenem Apfel. Die sativa-dominante Wirkung ist energetisierend und kreativ.",
    "typeDetails": "Sativa 70% / Indica 30%",
    "genetics": "Jack Herer x White Widow",
    "aromas": [
      "Apfel",
      "Süß",
      "Erdig",
      "Skunk",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Myrcen",
      "Limonen",
      "Pinen"
    ]
  },
  "apples-and-bananas": {
    "description": "Gezüchtet von Compound Genetics & Cookies. Bietet ein komplexes Fruchtaroma von Äpfeln, Bananen, Kirschen und Gewürzen. Die Wirkung ist ausgewogen und potent, was zu einem glücklichen und entspannten Gefühl führt, das den Körper beruhigt, aber den Geist aktiv hält. Perfekt für den Nachmittag.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "[(Platinum Cookies x Granddaddy Purple) x Blue Power] x Gelatti",
    "aromas": [
      "Apfel",
      "Banane",
      "Fruchtig",
      "Süß",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen",
      "Linalool"
    ]
  },
  "atomic-apple": {
    "description": "Eine ausgewogene Hybride von Alien Labs. Sie kombiniert den minzigen, erdigen Geschmack von Triangle Mints mit dem süßen Apfelgebäck von Apple Fritter. Die Wirkung ist stark, euphorisch und entspannend, geeignet für den ganzen Tag.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Triangle Mints x Apple Fritter",
    "aromas": [
      "Apfel",
      "Süß",
      "Minze",
      "Erdig",
      "Vanille"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "aurora-indica": {
    "description": "Gezüchtet von Nirvana Seeds. Eine potente F1-Hybride, die schwere Ganzkörpereffekte und eine sedierende zerebrale Ruhe erzeugt. Ideal für die abendliche Behandlung von Schlaflosigkeit und Schmerzen. Die Pflanzen sind kurz, robust und produzieren dichte, harzige Knospen.",
    "typeDetails": "Indica 90% / Sativa 10%",
    "genetics": "Afghan x Northern Lights",
    "aromas": [
      "Erdig",
      "Würzig",
      "Holzig",
      "Süß",
      "Blumig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "auto-duck": {
    "description": "Eine einzigartige 'Stealth'-Sorte von Dutch Passion mit einer natürlichen Blattmutation (Entenfußform), die sie unauffällig macht. Der Geruch ist subtil. Die Wirkung ist ausgewogen und moderat, ideal für den Tagesgebrauch. Sehr robust und einfach anzubauen.",
    "typeDetails": "Sativa 50% / Indica 50% (Autoflower)",
    "genetics": "Frisian Duck x Auto White Widow",
    "aromas": [
      "Erdig",
      "Blumig",
      "Fruchtig",
      "Minze",
      "Kiefer"
    ],
    "dominantTerpenes": [
      "Terpinolen",
      "Caryophyllen",
      "Myrcen"
    ]
  },
  "auto-white-widow": {
    "description": "Die autoflowering Version der legendären White Widow. Sie behält die potente, ausgewogene Wirkung und das würzig-erdige Aroma des Originals bei, wächst aber schneller und einfacher. Ideal für Anfänger.",
    "typeDetails": "Hybrid 50% / 50% (Autoflower)",
    "genetics": "White Widow x Ruderalis",
    "aromas": [
      "Erdig",
      "Würzig",
      "Kiefer",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "ayahuasca-purple": {
    "description": "Eine reine Indica von Barney's Farm, bekannt für ihre atemberaubenden violetten und rubinroten Farben. Die Wirkung ist tief entspannend, beruhigend und kann psychedelische Züge annehmen. Das Aroma ist exotisch mit Noten von Haselnuss und Papaya. Sehr ertragreich.",
    "typeDetails": "Indica 100%",
    "genetics": "Red River Delta x Master Kush",
    "aromas": [
      "Papaya",
      "Haselnuss",
      "Tropisch",
      "Erdig",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "b-52": {
    "description": "Eine indica-dominante Hybride, die für ihre entspannende und dennoch erhebende Wirkung bekannt ist. Sie sorgt für eine sanfte zerebrale Stimulation, die Stress abbaut, gefolgt von einer warmen, beruhigenden Körperwirkung. Ideal für den späten Nachmittag oder Abend.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Skunk #1 x Big Bud",
    "aromas": [
      "Süß",
      "Erdig",
      "Skunk",
      "Blumig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "banana-kush": {
    "description": "Eine indica-dominante Hybride, berühmt für ihr starkes Bananenaroma und ihren Geschmack. Sie liefert einen sanften, euphorischen Rausch, der Kreativität und soziale Interaktion fördert und gleichzeitig eine tiefe körperliche Entspannung bietet. Hervorragend zum Stressabbau.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Ghost OG x Skunk Haze",
    "aromas": [
      "Banane",
      "Süß",
      "Tropisch",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "banana-og": {
    "description": "Eine potente indica-dominante Hybride mit einem ausgeprägten Aroma von überreifen Bananen. Die Wirkung ist schleichend und stark, was zu tiefer Entspannung und oft zu Schläfrigkeit führt. Am besten für den Abendgebrauch geeignet, um Schlaflosigkeit und Schmerzen zu bekämpfen.",
    "typeDetails": "Indica 70% / Sativa 30%",
    "genetics": "OG Kush x Banana",
    "aromas": [
      "Banane",
      "Süß",
      "Erdig",
      "Scharf"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "bay-platinum-cookies": {
    "description": "Eine Hybridsorte, die ein Phänotyp von Girl Scout Cookies ist. Sie bietet ein ausgewogenes High, das mit einem zerebralen Rausch beginnt und in eine angenehme Körperentspannung übergeht. Das Aroma ist süß und erdig mit würzigen Noten.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Bay 11 x Platinum Cookies",
    "aromas": [
      "Süß",
      "Erdig",
      "Würzig",
      "Kräuterartig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "bc-bud": {
    "description": "Ein allgemeiner Begriff für hochwertiges Cannabis aus British Columbia, Kanada. Wenn er sich auf eine bestimmte Sorte bezieht, handelt es sich oft um eine potente indica-dominante Hybride, die für ein starkes, entspannendes Körper-High bekannt ist. Das Aroma ist typischerweise skunkig und erdig.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Variiert, oft ein Skunk-Phänotyp",
    "aromas": [
      "Erdig",
      "Skunk",
      "Süß",
      "Kiefer"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "bedica-talea": {
    "description": "Eine medizinische Cannabissorte von Bedrocan, standardisiert für Konsistenz. Es ist eine starke Indica, die für ihre sedierenden und schmerzlindernden Eigenschaften bekannt ist und häufig bei Schlafstörungen, chronischen Schmerzen und Übelkeit eingesetzt wird.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Proprietär",
    "aromas": [
      "Erdig",
      "Würzig",
      "Kräuterartig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "bediol-elida": {
    "description": "Eine ausgewogene THC:CBD-Medizinalsorte von Bedrocan. Der hohe CBD-Gehalt mildert die psychoaktiven Effekte von THC, was sie für Patienten geeignet macht, die Linderung bei Entzündungen, Angst und Schmerzen ohne ein starkes 'High' suchen.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Proprietär",
    "aromas": [
      "Erdig",
      "Süß",
      "Zitrus"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Terpinolen"
    ]
  },
  "bedrocan-afina": {
    "description": "Die Flaggschiff-Medizinal-Sativa von Bedrocan, bekannt für ihren hohen THC-Gehalt und ihre standardisierte Qualität. Sie bietet eine erhebende, energetische und klar-köpfige Wirkung, die oft bei ADHS, Depressionen und Müdigkeit eingesetzt wird.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Jack Herer Phänotyp",
    "aromas": [
      "Würzig",
      "Haze",
      "Erdig",
      "Zitrus"
    ],
    "dominantTerpenes": [
      "Terpinolen",
      "Myrcen"
    ]
  },
  "bedrolite-rensina": {
    "description": "Eine CBD-dominante Medizinalsorte von Bedrocan mit minimalem THC. Sie ist für Patienten, einschließlich Kindern, konzipiert, die die therapeutischen Vorteile von CBD für Erkrankungen wie Epilepsie und Entzündungen ohne psychoaktive Effekte benötigen.",
    "typeDetails": "CBD-dominante Hybride",
    "genetics": "Proprietär",
    "aromas": [
      "Erdig",
      "Kräuterartig",
      "Dezent"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Bisabolol"
    ]
  },
  "big-bud": {
    "description": "Eine indica-dominante Hybride, berühmt für ihre massiven Erträge. Wie der Name schon sagt, produziert sie außergewöhnlich große und schwere Blüten. Die Wirkung ist tief entspannend und sedierend, perfekt zur Bekämpfung von Stress und Schlaflosigkeit.",
    "typeDetails": "Indica 85% / Sativa 15%",
    "genetics": "Afghani x Northern Lights x Skunk #1",
    "aromas": [
      "Süß",
      "Erdig",
      "Skunk",
      "Fruchtig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "birthday-cake-kush": {
    "description": "Eine indica-dominante Hybride mit einem köstlichen süßen, kuchenartigen Geschmack. Sie bietet ein starkes Körper-High, das tief entspannend und euphorisch ist, was sie ideal macht, um das Ende eines langen Tages zu feiern. Hilft bei Schmerzen, Angst und Schlaflosigkeit.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Girl Scout Cookies x Cherry Pie",
    "aromas": [
      "Süß",
      "Vanille",
      "Erdig",
      "Nussig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "biscotti": {
    "description": "Eine potente indica-dominante Hybride, bekannt für ihr köstliches Geschmacksprofil aus süßen Keksen mit Diesel-Untertönen. Das High ist zerebral und glückselig, schnell gefolgt von einem entspannenden Körper-Buzz, der sich von Kopf bis Fuß ausbreitet.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Gelato #25 x Girl Scout Cookies x South Florida OG",
    "aromas": [
      "Süß",
      "Keks",
      "Diesel",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "biscotti-mintz": {
    "description": "Eine optisch auffällige, potente indica-dominante Sorte von Barney's Farm. Sie zeichnet sich durch tiefviolette Farbtöne und ein komplexes Aroma von Minz-Schokoladenkeksen und Gewürzen aus. Die Wirkung ist anfangs kreativ und fokussiert und geht dann in ein beruhigendes und entspannendes Körper-High über.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Biscotti x Kush Mints",
    "aromas": [
      "Minze",
      "Schokolade",
      "Würzig",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Caryophyllen",
      "Eukalyptol"
    ]
  },
  "black-beauty": {
    "description": "Eine seltene Sativa-Sorte, die für ihr außergewöhnlich dunkles, fast schwarzes Laub und ihre Blüten bekannt ist. Sie enthält THCV, das dafür bekannt ist, ein klar-köpfiges, anregendes und kürzer anhaltendes High im Vergleich zu THC zu erzeugen. Das Aroma ist blumig und süß.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Unbekannt",
    "aromas": [
      "Blumig",
      "Süß",
      "Kräuterartig"
    ],
    "dominantTerpenes": [
      "Terpinolen"
    ]
  },
  "black-cherry-soda": {
    "description": "Eine gut ausbalancierte Hybride, benannt nach ihrer dunklen Färbung und ihrem fruchtigen, soda-artigen Geschmack. Sie bietet eine ausgewogene Wirkung, die mit zerebraler Stimulation beginnt und in einen ruhigen, entspannten Zustand übergeht, was sie für den Tagesgebrauch geeignet macht.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Unbekannt",
    "aromas": [
      "Kirsche",
      "Beere",
      "Süß",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Limonen"
    ]
  },
  "black-dahlia": {
    "description": "Eine indica-dominante Hybride mit schönen dunklen violetten Knospen. Das Aroma ist süß und blumig mit erdigen Untertönen. Sie bietet ein entspannendes und euphorisches High, das perfekt zum Entspannen ohne starke Sedierung ist.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Black Cherry Soda x Querkle",
    "aromas": [
      "Blumig",
      "Süß",
      "Beere",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "black-domina": {
    "description": "Eine potente, schnell blühende indica-dominante Hybride. Sie produziert dunkle, dichte und harzige Knospen. Die Wirkung ist stark sedierend und narkotisch, was sie zu einem Favoriten für den nächtlichen Gebrauch zur Bekämpfung von Schmerzen und Schlaflosigkeit macht. Das Aroma ist pfeffrig und erdig.",
    "typeDetails": "Indica 95% / Sativa 5%",
    "genetics": "Afghani x Ortega x Northern Lights x Hash Plant",
    "aromas": [
      "Pfeffer",
      "Erdig",
      "Würzig",
      "Kiefer"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "black-jack": {
    "description": "Eine Hybridsorte, die die erhebenden Effekte von Jack Herer mit der starken Harzproduktion von Black Domina kombiniert. Sie bietet ein langanhaltendes, glückseliges und kreatives High, das sowohl zerebral stimulierend als auch körperlich entspannend ist.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Black Domina x Jack Herer",
    "aromas": [
      "Erdig",
      "Kiefer",
      "Holzig",
      "Süß"
    ],
    "dominantTerpenes": [
      "Terpinolen",
      "Myrcen",
      "Ocimen"
    ]
  },
  "black-runtz": {
    "description": "Ein Phänotyp der berühmten Runtz-Sorte, der sich durch seine außergewöhnlich dunklen, fast schwarzen Knospen auszeichnet. Er teilt das gleiche süße, bonbonartige Geschmacksprofil und bietet ein euphorisches, langanhaltendes High, das den Körper entspannt und den Geist erhebt.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Zkittlez x Gelato",
    "aromas": [
      "Süß",
      "Fruchtig",
      "Bonbon",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "black-tuna": {
    "description": "Eine potente indica-dominante Hybride, die von kanadischen Züchtern geschaffen wurde. Sie ist bekannt für ihr extrem scharfes, fischiges und skunkiges Aroma. Das High ist stark und sedierend, führt oft zum Couch-Lock und ist ideal bei starken Schmerzen und Schlaflosigkeit.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Herijuana x Lamb's Bread",
    "aromas": [
      "Scharf",
      "Skunk",
      "Erdig",
      "Diesel"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "blackberry": {
    "description": "Eine gut ausbalancierte Hybride, bekannt für ihren köstlichen Geschmack nach frischen Brombeeren. Das High ist entspannend und euphorisch und vermittelt ein Gefühl von Glück und Wohlbefinden. Sie ist wirksam bei der Behandlung von Schmerzen und Stress, während der Konsument funktionsfähig bleibt.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Black Domina x Raspberry Cough",
    "aromas": [
      "Brombeere",
      "Süß",
      "Fruchtig",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Limonen"
    ]
  },
  "blackberry-kush": {
    "description": "Eine starke indica-dominante Sorte mit einem süßen Brombeeraroma, gemischt mit dem klassischen Kraftstoffgeruch von Kush. Sie bietet ein potentes, entspannendes Körper-High, das sich hervorragend zur Schmerzlinderung, zum Stressabbau und zum Schlafen eignet.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Afghani x Blackberry",
    "aromas": [
      "Brombeere",
      "Süß",
      "Erdig",
      "Diesel"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Limonen"
    ]
  },
  "blackwater": {
    "description": "Eine Indica-Sorte mit tiefvioletten Knospen und einem süßen Traubenaroma. Es beginnt mit einem euphorischen Kopfeffekt, der in ein beruhigendes, Ganzkörper-Buzz übergeht. Sie ist sehr wirksam bei Schmerzen, Appetitanregung und Schlaf.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Mendo Purps x San Fernando Valley OG Kush",
    "aromas": [
      "Traube",
      "Süß",
      "Erdig",
      "Kiefer"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "blue-cheese": {
    "description": "Eine indica-dominante Hybride, berühmt für ihr einzigartiges Geschmacksprofil, das die süßen, fruchtigen Noten von Blueberry mit dem herzhaften, käsigen Aroma von UK Cheese kombiniert. Die Wirkung ist tief entspannend und beruhigend, perfekt zum Entspannen am Ende des Tages.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Blueberry x UK Cheese",
    "aromas": [
      "Käse",
      "Blaubeere",
      "Süß",
      "Scharf"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Myrcen",
      "Limonen"
    ]
  },
  "blue-cookies": {
    "description": "Eine potente indica-dominante Hybride, die eine erdrückende Welle der Euphorie liefert, gefolgt von tiefer Körperentspannung. Sie hat einen süßen Beeren- und Kirschgeschmack mit erdigen Untertönen. Hervorragend zur Schmerzlinderung und Entspannung.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Girl Scout Cookies x Blueberry",
    "aromas": [
      "Beere",
      "Kirsche",
      "Süß",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Humulen"
    ]
  },
  "blue-diamond": {
    "description": "Eine potente indica-dominante Hybride, die mit einer dicken Schicht Trichome glänzt. Sie bietet ein starkes, langanhaltendes High, das sowohl zerebral erhebend als auch körperlich entspannend ist. Das Aroma ist eine Mischung aus erdigem Kiefer und süßer Beere.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Diamond OG x Blue Dream",
    "aromas": [
      "Erdig",
      "Kiefer",
      "Beere",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "blue-dream": {
    "description": "Eine legendäre sativa-dominante Hybride aus Kalifornien. Sie bietet ein ausgewogenes High mit sanfter zerebraler Stimulation und Ganzkörperentspannung. Ihr süßes Beerenaroma macht sie zu einem Favoriten für Anfänger und erfahrene Konsumenten. Ideal für die Schmerzlinderung tagsüber.",
    "typeDetails": "Sativa 60% / Indica 40%",
    "genetics": "Blueberry x Haze",
    "aromas": [
      "Blaubeere",
      "Süß",
      "Erdig",
      "Kräuterartig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "blue-dream-cbd": {
    "description": "Eine CBD-reiche Version des klassischen Blue Dream. Sie bietet das gleiche süße Beerenaroma und den sanften Auftrieb, aber mit deutlich reduzierter Psychoaktivität aufgrund des ausgewogenen 1:1 THC:CBD-Verhältnisses. Ideal für therapeutische Anwender, die Linderung ohne ein starkes High suchen.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Blue Dream x California Orange CBD",
    "aromas": [
      "Blaubeere",
      "Süß",
      "Zitrus",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "blue-dream-matic": {
    "description": "Eine autoflowering Version von Blue Dream, die die gleichen beliebten Effekte und Geschmäcker bietet, aber in einem schnelleren, einfacher anzubauenden Paket. Das High ist euphorisch und erhebend, perfekt für kreative Beschäftigungen und den Tagesgebrauch.",
    "typeDetails": "Sativa-dominante Hybride (Autoflower)",
    "genetics": "Blue Dream x Ruderalis",
    "aromas": [
      "Beere",
      "Süß",
      "Erdig",
      "Zitrus"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "blue-gelato-41": {
    "description": "Eine potente indica-dominante Hybride von Barney's Farm. Sie kombiniert die fruchtigen Aromen von Blueberry mit der cremigen Süße von Gelato. Die Wirkung ist anfangs klar-köpfig und energetisch, gefolgt von einer angenehmen Körperentspannung. Außergewöhnlich ertragreich im Freien.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Blueberry x Thin Mint GSC x Sunset Sherbet",
    "aromas": [
      "Beere",
      "Zitrus",
      "Süß",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "blue-hawaiian": {
    "description": "Eine sativa-dominante Hybride mit einem tropischen, fruchtigen Geschmack, der an Ananas und Beeren erinnert. Sie bietet ein glückliches, euphorisches High, das perfekt für soziale Situationen und kreative Unternehmungen ist. Das High ist ausgewogen mit einer leichten Körperentspannung.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Blueberry x Hawaiian Sativa",
    "aromas": [
      "Tropisch",
      "Ananas",
      "Beere",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Terpinolen"
    ]
  },
  "blue-magoo": {
    "description": "Eine indica-dominante Hybride, bekannt für ihr komplexes Geschmacksprofil aus Beeren, Früchten und blumigen Noten. Sie liefert ein entspannendes und euphorisches High, das funktional genug für den Tagesgebrauch ist, aber in größeren Dosen sedierend sein kann.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "DJ Short Blueberry x Major League Bud (Williams Wonder)",
    "aromas": [
      "Beere",
      "Fruchtig",
      "Blumig",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "blue-power": {
    "description": "Eine potente indica-dominante Hybride, die dichte, trichom-bedeckte Knospen produziert. Das Aroma ist eine süß-saure Mischung aus Beere und Zitrone. Das High ist stark, beginnt mit einem euphorischen Auftrieb und endet in tiefer Entspannung.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "The Power x Master Kush x Blue Moonshine x Sour Double",
    "aromas": [
      "Beere",
      "Zitrone",
      "Süß",
      "Sauer"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "blue-walker": {
    "description": "Eine potente sativa-dominante Hybride mit einem einzigartigen fruchtigen, süßen und erdigen Aroma. Sie liefert ein starkes, schnell wirkendes zerebrales High, das energetisch und motivierend ist, ideal für Produktivität und kreative Aufgaben.",
    "typeDetails": "Sativa 90% / Indica 10%",
    "genetics": "Blue Dream x Skywalker",
    "aromas": [
      "Fruchtig",
      "Süß",
      "Erdig",
      "Beere"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "blue-zushi": {
    "description": "Eine potente indica-dominante Hybride, bekannt für ihr schönes Aussehen und ihren komplexen Geschmack. Sie kombiniert die fruchtigen Noten von Zkittlez mit der kushigen Erdigkeit von Kush Mints. Das High ist entspannend und euphorisch, perfekt zum Entspannen.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Zkittlez x Kush Mints",
    "aromas": [
      "Fruchtig",
      "Erdig",
      "Würzig",
      "Süß"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Caryophyllen",
      "Linalool"
    ]
  },
  "blueberry": {
    "description": "Eine klassische indica-dominante Sorte, die 2000 den High Times Cannabis Cup gewann. Sie ist berühmt für ihr unverkennbares Aroma und ihren Geschmack nach frischen Blaubeeren. Das High ist langanhaltend, euphorisch und tief entspannend.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Purple Thai x Afghani",
    "aromas": [
      "Blaubeere",
      "Süß",
      "Fruchtig",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "blueberry-haze": {
    "description": "Eine sativa-dominante Hybride, die den süßen Geschmack von Blueberry mit den zerebralen Effekten von Haze kombiniert. Das High ist erhebend, kreativ und energetisch, was sie zu einer großartigen Wahl für den Tagesgebrauch und soziale Aktivitäten macht.",
    "typeDetails": "Sativa 80% / Indica 20%",
    "genetics": "Blueberry x Haze",
    "aromas": [
      "Blaubeere",
      "Süß",
      "Haze",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Terpinolen",
      "Pinen"
    ]
  },
  "blueberry-og": {
    "description": "Eine indica-dominante Hybride, die die süßen Beerenaromen von Blueberry mit dem klassischen erdigen Kiefer von OG Kush verbindet. Sie bietet ein ausgewogenes High, das sowohl zerebral erhebend als auch körperlich entspannend ist und bei Stress und Schmerzen wirksam ist.",
    "typeDetails": "Indica 70% / Sativa 30%",
    "genetics": "Blueberry x OG Kush",
    "aromas": [
      "Blaubeere",
      "Erdig",
      "Kiefer",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "booger": {
    "description": "Eine sehr potente indica-dominante Hybride mit einem funky, scharfen Aroma von Skunk und Diesel. Das High ist schwer und sedierend, führt oft zum Couch-Lock und einem starken Heißhunger. Am besten für erfahrene Konsumenten und den nächtlichen Gebrauch geeignet.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Bubba Kush x Strawberry Cough",
    "aromas": [
      "Scharf",
      "Skunk",
      "Diesel",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "bruce-banger": {
    "description": "Eine potente sativa-dominante Hybride, die die Kraft von Bruce Banner mit dem klassischen Geschmack von OG Kush kombiniert. Das High ist schnell wirkend, euphorisch und energetisch und regt Kreativität und Konzentration an. Der Geschmack ist eine Mischung aus Diesel und süßer Zitrusfrucht.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Bruce Banner x OG Kush",
    "aromas": [
      "Diesel",
      "Süß",
      "Zitrus",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "bruce-banner": {
    "description": "Benannt nach dem Alter Ego des Hulk, ist dies eine kraftvolle sativa-dominante Hybride. Sie ist bekannt für ihren unglaublich hohen THC-Gehalt und ein schnell wirkendes, euphorisches und kreatives High, das schließlich in einen Zustand der Entspannung übergeht. Das Aroma ist eine starke Mischung aus Diesel und süßer Beere.",
    "typeDetails": "Sativa 60% / Indica 40%",
    "genetics": "OG Kush x Strawberry Diesel",
    "aromas": [
      "Diesel",
      "Süß",
      "Beere",
      "Scharf"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "bubba-fett": {
    "description": "Eine potente indica-dominante Hybride, benannt nach dem Star Wars-Kopfgeldjäger. Sie bietet ein schweres, entspannendes Körper-High, das dich in einer 'karbonitartigen' Entspannung 'gefangen' nehmen kann. Das Aroma ist erdig und scharf mit süßen Untertönen.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Stardawg x Pre-98 Bubba Kush",
    "aromas": [
      "Erdig",
      "Scharf",
      "Süß",
      "Diesel"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "bubba-kush": {
    "description": "Eine klassische Indica-Sorte, bekannt für ihre schweren, beruhigenden Effekte. Sie hat einen süßen, haschähnlichen Geschmack mit Noten von Schokolade und Kaffee. Das High ist tief entspannend und führt oft zu Schläfrigkeit. Ein Favorit zur Linderung von Schmerzen und Schlaflosigkeit.",
    "typeDetails": "Indica 90% / Sativa 10%",
    "genetics": "Möglicherweise OG Kush x Northern Lights",
    "aromas": [
      "Erdig",
      "Süß",
      "Kaffee",
      "Schokolade"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "bubble-gum": {
    "description": "Eine preisgekrönte Hybride, berühmt für ihren ausgeprägten süßen Geruch und Geschmack, genau wie klassischer Kaugummi. Sie bietet ein ausgewogenes High, das euphorisch und erhebend ist, gefolgt von einer sanften Körperentspannung. Ideal für kreative Aufgaben und Stressabbau.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Indiana Bubblegum",
    "aromas": [
      "Süß",
      "Kaugummi",
      "Fruchtig",
      "Blumig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "cactus-breath": {
    "description": "Eine potente indica-dominante Hybride mit einem einzigartigen scharfen Aroma, das Diesel, Gewürze und Erde kombiniert. Das High ist stark entspannend und euphorisch, führt oft zu einem schweren Körpergefühl und tiefer Ruhe. Am besten für erfahrene Konsumenten.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Cactus x Mendo Breath",
    "aromas": [
      "Scharf",
      "Diesel",
      "Würzig",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "cactus-cooler": {
    "description": "Eine sativa-dominante Hybride mit einem hellen, erfrischenden Geschmacksprofil aus Zitrusfrüchten und tropischen Früchten. Das High ist energetisch und erhebend, perfekt für Tagesaktivitäten, zur Steigerung der Kreativität und zur Verbesserung der Stimmung.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Blue Dream x OG Kush",
    "aromas": [
      "Zitrus",
      "Tropisch",
      "Ananas",
      "Süß"
    ],
    "dominantTerpenes": [
      "Terpinolen",
      "Myrcen"
    ]
  },
  "cake-bomb": {
    "description": "Eine indica-dominante Hybride, die dichte, frostige Knospen mit einem süßen, kuchenartigen Aroma produziert. Das High ist tief entspannend und beruhigend, was sie zu einer ausgezeichneten Wahl für den Abendgebrauch zur Linderung von Stress und Schmerzen macht.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Do-Si-Dos x PCS1",
    "aromas": [
      "Süß",
      "Kuchen",
      "Erdig",
      "Vanille"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Caryophyllen",
      "Myrcen"
    ]
  },
  "cali-o": {
    "description": "Eine klassische 50/50 Hybride, auch bekannt als California Orange. Sie ist berühmt für ihr starkes, süßes Orangenaroma. Das High ist klar-köpfig, erhebend und glücklich, was sie zu einer großartigen Sorte für soziale Anlässe und kreative Arbeit macht.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Kalifornische Landrasse",
    "aromas": [
      "Orange",
      "Zitrus",
      "Süß",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "candy-jack": {
    "description": "Eine sativa-dominante Hybride, die das Beste aus zwei legendären Sorten kombiniert. Sie hat ein süßes, zitrusartiges Aroma und bietet ein starkes, erhebendes zerebrales High, das energetisch und kreativ ist. Ideal zur Bekämpfung von Müdigkeit und Depressionen.",
    "typeDetails": "Sativa 80% / Indica 20%",
    "genetics": "Jack Herer x Skunk #1",
    "aromas": [
      "Süß",
      "Zitrus",
      "Erdig",
      "Skunk"
    ],
    "dominantTerpenes": [
      "Terpinolen",
      "Myrcen",
      "Pinen"
    ]
  },
  "candyland": {
    "description": "Eine sativa-dominante Hybride mit einem süßen Bonbongeschmack und erdigen Untertönen. Das High ist erhebend und anregend, perfekt für soziale Zusammenkünfte und kreative Aktivitäten. Sie kann auch wirksame Schmerzlinderung ohne starke Sedierung bieten.",
    "typeDetails": "Sativa 70% / Indica 30%",
    "genetics": "Granddaddy Purple x Bay Platinum Cookies",
    "aromas": [
      "Süß",
      "Bonbon",
      "Erdig",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Humulen"
    ]
  },
  "cannatonic": {
    "description": "Eine berühmte CBD-reiche Hybridsorte, oft mit einem fast 1:1 THC- zu CBD-Verhältnis. Sie bietet ein mildes, entspannendes High, das kurzlebig und hauptsächlich körperlich ist, was sie hervorragend zur Behandlung von Schmerzen, Angst und Muskelkrämpfen ohne intensive Psychoaktivität macht.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "MK Ultra x G13 Haze",
    "aromas": [
      "Erdig",
      "Holzig",
      "Zitrus",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "cap-junky": {
    "description": "Eine hochpotente Hybride, bekannt für ihr intensives, scharfes Aroma von sauren Früchten und Benzin. Das High ist stark und langanhaltend, liefert eine Welle der Euphorie und Kreativität, die schließlich in einen Zustand tiefer Entspannung übergeht. Für erfahrene Konsumenten.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Alien Cookies x Kush Mints #11",
    "aromas": [
      "Scharf",
      "Diesel",
      "Sauer",
      "Fruchtig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "captains-cake": {
    "description": "Eine sativa-dominante Hybride mit einem süßen, fruchtigen und leicht sauren Aroma. Das High ist erhebend und energetisch und bietet einen Schub an Kreativität und Konzentration, was sie zu einer großartigen Wahl für den Tagesgebrauch macht.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Girl Scout Cookies x White Fire Alien OG",
    "aromas": [
      "Süß",
      "Fruchtig",
      "Sauer",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Caryophyllen",
      "Myrcen"
    ]
  },
  "carbon-fiber": {
    "description": "Eine potente und seltene indica-dominante Hybride. Sie hat ein komplexes Aromaprofil, das Noten von Traube, Zitrus und Diesel kombiniert. Das High ist tief entspannend und sedierend und führt oft zu einem glückseligen Couch-Lock.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Grape Pie x Biscotti x Cookies and Cream",
    "aromas": [
      "Traube",
      "Diesel",
      "Zitrus",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "casey-jones": {
    "description": "Eine sativa-dominante Hybride, benannt nach dem berühmten Lokführer. Sie ist bekannt für ihr schnell wirkendes, erhebendes und kreatives High. Das Aroma ist erdig und süß mit Noten von Zitrus. Eine großartige Sorte für Produktivität und Tagesgenuss.",
    "typeDetails": "Sativa 80% / Indica 20%",
    "genetics": "Trainwreck x Sour Diesel x Thai",
    "aromas": [
      "Erdig",
      "Süß",
      "Zitrus",
      "Diesel"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Limonen"
    ]
  },
  "cat-piss": {
    "description": "Trotz ihres unglücklichen Namens ist dies eine klassische sativa-dominante Sorte mit einem scharfen, skunkigen und ammoniakähnlichen Aroma. Das High ist energetisch, euphorisch und sehr zerebral, was sie bei Sativa-Liebhabern für ihre klar-köpfigen Effekte beliebt macht.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Super Silver Haze Phänotyp",
    "aromas": [
      "Scharf",
      "Ammoniak",
      "Skunk",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Terpinolen",
      "Myrcen"
    ]
  },
  "cataract-kush": {
    "description": "Eine potente indica-dominante Hybride, bekannt für ihre schweren, sedierenden Effekte. Das High ist ein 'Creeper', der sich langsam zu einer starken Ganzkörperentspannung aufbaut, die für Anfänger überwältigend sein kann. Sie hat ein scharfes, fruchtiges und skunkiges Aroma.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "LA Confidential x OG Kush",
    "aromas": [
      "Scharf",
      "Fruchtig",
      "Skunk",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "cbd-critical-cure": {
    "description": "Eine CBD-reiche indica-dominante Sorte, die für den therapeutischen Gebrauch gezüchtet wurde. Sie hat einen süßen, erdigen Geschmack und bietet eine sanfte, beruhigende Wirkung mit minimaler Psychoaktivität. Sie ist sehr wirksam bei der Behandlung von Schmerzen, Entzündungen und Angst.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Critical Kush x Shanti Babas CBD-angereicherte Sorte",
    "aromas": [
      "Erdig",
      "Süß",
      "Holzig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "cbd-therapy": {
    "description": "Eine bahnbrechende Sorte, die speziell für einen hohen CBD- und niedrigen THC-Gehalt gezüchtet wurde. Sie ist ideal für Patienten, die die medizinischen Vorteile von Cannabis ohne das High benötigen. Die Wirkung ist klar-köpfig und beruhigend. Das Aroma ist eine Mischung aus fruchtigen und erdigen Noten.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Unbekannt",
    "aromas": [
      "Fruchtig",
      "Erdig",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "cereal-a-la-mode": {
    "description": "Eine potente und geschmackvolle Hybride aus der Cookies-Familie. Sie hat ein süßes, cremiges und fruchtiges Aroma, das an eine Schüssel Müsli erinnert. Das High ist gut ausbalanciert und bietet ein euphorisches und kreatives Kopf-High neben einem entspannenden Körper-Buzz.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Cereal Milk x Georgia Pie",
    "aromas": [
      "Süß",
      "Cremig",
      "Fruchtig",
      "Vanille"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen"
    ]
  },
  "cereal-milk": {
    "description": "Eine ausgewogene Hybridsorte von Cookies, bekannt für ihren einzigartigen cremigen und fruchtigen Geschmack, wie die Milch am Boden einer Schüssel mit zuckerhaltigem Müsli. Das High ist glückselig und kreativ, ideal für einen entspannten und dennoch produktiven Tag.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "(Y Life x Snowman) x GSC",
    "aromas": [
      "Süß",
      "Cremig",
      "Beere",
      "Vanille"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen"
    ]
  },
  "charlottes-web": {
    "description": "Eine weltberühmte Sorte mit hohem CBD- und niedrigem THC-Gehalt. Sie erlangte Berühmtheit durch ihre Wirksamkeit bei der Behandlung schwerer Epilepsie. Sie erzeugt kein psychoaktives High, was sie zu einer rein medizinischen Sorte für eine Vielzahl von Erkrankungen macht.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Hanf x Unbekannte Sorte",
    "aromas": [
      "Erdig",
      "Kiefer",
      "Blumig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "cheese": {
    "description": "Eine legendäre indica-dominante Hybride, die in Großbritannien entstanden ist. Sie ist berühmt für ihr scharfes, käsiges und skunkiges Aroma. Das High ist stark und vermittelt ein glückliches, entspannendes Gefühl, das auch sehr euphorisch und erhebend sein kann.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Skunk #1 Phänotyp",
    "aromas": [
      "Käse",
      "Scharf",
      "Skunk",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Myrcen",
      "Limonen"
    ]
  },
  "cheesecake": {
    "description": "Eine indica-dominante Hybride mit einem süßen, käsigen und cremigen Geschmacksprofil. Das High ist entspannend und euphorisch, perfekt zum Entspannen nach einem langen Tag und zur Appetitanregung. Sie ist wirksam bei Stress, Schmerzen und Appetitlosigkeit.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Cheese x eine unbekannte Indica",
    "aromas": [
      "Käse",
      "Süß",
      "Cremig",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "cheetah-piss": {
    "description": "Eine potente Hybride mit einem sehr scharfen, ammoniakähnlichen Aroma, ähnlich wie Cat Piss, aber mit zusätzlichen Zitrus- und Dieselnoten. Das High ist schnell wirkend und kichernd und bietet eine Welle der Euphorie und Kreativität, die sich hervorragend für soziale Anlässe eignet.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Lemonnade x Gelato 42 x London Poundcake 97",
    "aromas": [
      "Scharf",
      "Ammoniak",
      "Zitrus",
      "Diesel"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen"
    ]
  },
  "chem-sis": {
    "description": "Ein sativa-dominanter Phänotyp des legendären Chemdawg. Er ist bekannt für sein scharfes Diesel- und chemisches Aroma. Das High ist stark zerebral, energetisch und kreativ, was ihn zu einem Favoriten unter erfahrenen Sativa-Liebhabern macht.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Chemdawg Phänotyp",
    "aromas": [
      "Diesel",
      "Chemisch",
      "Scharf",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "chemdawg": {
    "description": "Eine legendäre Sorte mit mysteriösem Ursprung, Chemdawg ist die Mutter vieler berühmter Sorten wie OG Kush und Sour Diesel. Sie ist bekannt für ihr ausgeprägtes, scharfes Dieselaroma und ein sehr potentes, zerebrales High, das kreativ und erhebend ist.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Unbekannt",
    "aromas": [
      "Diesel",
      "Chemisch",
      "Scharf",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Myrcen",
      "Limonen"
    ]
  },
  "chemdog-millionaire": {
    "description": "Eine potente indica-dominante Hybride mit einem komplexen Aroma von Erde, Kraftstoff und Zitrus. Sie liefert ein starkes, langanhaltendes High, das sowohl zerebral euphorisch als auch tief körperlich entspannend ist. Ideal zur Linderung von Schmerzen und Stress.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Chemdawg x Gupta Kush",
    "aromas": [
      "Erdig",
      "Diesel",
      "Zitrus",
      "Scharf"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "cherry-ak-47": {
    "description": "Ein Phänotyp des klassischen AK-47, der für sein ausgeprägtes Kirscharoma ausgewählt wurde. Er behält das ausgewogene, erhebende High des Originals bei, fügt aber eine süße, fruchtige Note hinzu. Die Wirkung ist kreativ, glücklich und entspannend.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "AK-47 Phänotyp",
    "aromas": [
      "Kirsche",
      "Süß",
      "Erdig",
      "Skunk"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "cherry-pie": {
    "description": "Eine indica-dominante Hybride mit einem köstlichen Aroma von süß-saurem Kirschkuchen. Das High ist gut ausbalanciert, beginnt mit einem erhebenden zerebralen Buzz, der sanft in einen Zustand glücklicher Entspannung übergeht. Ideal zum Stressabbau.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Granddaddy Purple x Durban Poison",
    "aromas": [
      "Kirsche",
      "Süß",
      "Erdig",
      "Beere"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "chiquita-banana": {
    "description": "Eine potente Hybride, bekannt für ihren unglaublich hohen THC-Gehalt und einen starken Bananengeschmack. Das High ist stark und euphorisch, beginnt mit einem zerebralen Rausch, der in tiefe körperliche Entspannung übergeht. Am besten für erfahrene Konsumenten.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "OG Kush x Banana",
    "aromas": [
      "Banane",
      "Süß",
      "Tropisch",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "cinderella-99": {
    "description": "Auch bekannt als Cindy 99. Eine sativa-dominante Hybride, berühmt für ihre schnelle Blütezeit und ein verträumtes, euphorisches und erhebendes High. Sie hat einen süßen, fruchtigen Geschmack mit tropischen Noten. Eine ausgezeichnete Tagessorte für Kreativität und Stimmungsaufhellung.",
    "typeDetails": "Sativa 85% / Indica 15%",
    "genetics": "Jack Herer x Shiva Skunk",
    "aromas": [
      "Süß",
      "Fruchtig",
      "Tropisch",
      "Zitrus"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "citradelic-sunset": {
    "description": "Eine sativa-dominante Hybride mit einem lebhaften Zitrus- und sauren Aroma. Sie liefert ein starkes, erhebendes und energetisches High, das perfekt für den Tagesgebrauch ist. Sie ist bekannt dafür, Kreativität zu entfachen und ein langanhaltendes euphorisches Erlebnis zu bieten.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Ghost Train Haze x Mandarin Sunset",
    "aromas": [
      "Zitrus",
      "Sauer",
      "Süß",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Terpinolen",
      "Myrcen"
    ]
  },
  "colt-45": {
    "description": "Eine potente sativa-dominante Hybride mit einem komplexen Aroma, das gasige, erdige und blumige Noten kombiniert. Das High ist stark und zerebral und bietet einen Energieschub und Euphorie, die sich hervorragend für kreative Projekte und soziale Anlässe eignen.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Gelato 45 x Slurricane",
    "aromas": [
      "Gasig",
      "Erdig",
      "Blumig",
      "Scharf"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Caryophyllen"
    ]
  },
  "congo": {
    "description": "Eine reine Sativa-Landrassensorte, bekannt für ihr klares, energetisches und langanhaltendes High. Sie bietet einen anregenden und kreativen Buzz ohne die Angst, die manchmal mit starken Sativas verbunden ist. Das Aroma ist eine süße und fruchtige Mischung.",
    "typeDetails": "Sativa 100%",
    "genetics": "Kongo Landrasse",
    "aromas": [
      "Süß",
      "Fruchtig",
      "Würzig",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Terpinolen"
    ]
  },
  "cookies-and-cream": {
    "description": "Eine gut ausbalancierte Hybride, die 2014 den Hybrid-Pokal beim Denver Cannabis Cup gewann. Sie hat einen süßen Vanille- und Nussgeschmack. Das High ist glücklich und entspannend und bietet langanhaltende Linderung von Stress und Schmerzen.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Starfighter x ein unbekannter GSC-Phänotyp",
    "aromas": [
      "Süß",
      "Vanille",
      "Nussig",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "dance-world": {
    "description": "Eine CBD-reiche Sorte von Royal Queen Seeds mit einem nahezu perfekten 1:1-Verhältnis von THC zu CBD. Die Wirkung ist erhebend, kreativ und funktional, ohne starke psychoaktive Effekte. Ideal für den therapeutischen Gebrauch während des Tages. Das Aroma ist eine komplexe Mischung aus würzigen, erdigen und fruchtigen Noten.",
    "typeDetails": "Sativa 75% / Indica 25%",
    "genetics": "Dancehall 20 x Juanita la Lagrimosa",
    "aromas": [
      "Würzig",
      "Erdig",
      "Fruchtig",
      "Kiefer"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "darth-vader-og": {
    "description": "Eine potente Indica-Sorte mit tief entspannenden, fast sedierenden Effekten. Ideal zur Linderung von Schmerzen und Schlaflosigkeit. Das Aroma ist erdig und süß mit Noten von Traube und Kiefer.",
    "typeDetails": "Indica 100%",
    "genetics": "SFV OG x Larry OG",
    "aromas": [
      "Traube",
      "Erdig",
      "Süß",
      "Kiefer"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Limonen"
    ]
  },
  "deadhead-og": {
    "description": "Eine potente, sativa-dominante Hybride mit einem komplexen, scharfen Aroma von Kiefer, Diesel und Erde. Die Wirkung ist stark zerebral, euphorisch und energetisierend, ideal für erfahrene Konsumenten, die ein starkes Kopf-High suchen.",
    "typeDetails": "Sativa 60% / Indica 40%",
    "genetics": "Chemdawg 91 x SFV OG Kush",
    "aromas": [
      "Kiefer",
      "Scharf",
      "Erdig",
      "Diesel",
      "Zitrus"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Myrcen",
      "Limonen"
    ]
  },
  "death-bubba": {
    "description": "Ein Nachkomme des beliebten Bubba Kush. Diese potente Indica ist bekannt für ihre starken sedierenden Effekte, die zu einem tiefen, fast komatösen Schlaf führen können. Ideal bei chronischen Schmerzen und Schlaflosigkeit. Das Aroma ist erdig, skunkig und süß.",
    "typeDetails": "Indica 70% / Sativa 30%",
    "genetics": "Bubba Kush",
    "aromas": [
      "Erdig",
      "Skunk",
      "Süß",
      "Kiefer"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Myrcen",
      "Limonen"
    ]
  },
  "death-star": {
    "description": "Eine potente indica-dominante Hybride, die eine ausgewogene Mischung aus zerebraler Euphorie und tiefer Körperentspannung bietet. Das Aroma ist eine scharfe Mischung aus Skunk, Diesel und süßer Erde. Die Effekte sind schleichend und können zu starker Sedierung führen.",
    "typeDetails": "Indica 75% / Sativa 25%",
    "genetics": "Sensi Star x Sour Diesel",
    "aromas": [
      "Diesel",
      "Skunk",
      "Erdig",
      "Scharf"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Myrcen",
      "Limonen"
    ]
  },
  "diablo-og": {
    "description": "Eine sativa-dominante Hybride mit einem süßen, würzigen und zitrusartigen Aroma. Die Wirkung ist erhebend und energetisierend, fördert Kreativität und Geselligkeit und bietet gleichzeitig eine sanfte körperliche Entspannung. Ideal für den Tagesgebrauch.",
    "typeDetails": "Sativa 60% / Indica 40%",
    "genetics": "Diablo x OG Kush",
    "aromas": [
      "Würzig",
      "Zitrus",
      "Süß",
      "Grapefruit"
    ],
    "dominantTerpenes": [
      "Terpinolen",
      "Myrcen",
      "Pinen"
    ]
  },
  "diamond-og": {
    "description": "Eine Indica-Sorte, bekannt für ihre potenten, langanhaltenden und entspannenden Effekte. Sie hat ein klassisches OG-Aroma mit Noten von Zitrus, Diesel und Kiefer. Die Wirkung beginnt mit einem zerebralen Rausch, der schnell in tiefe körperliche Ruhe übergeht.",
    "typeDetails": "Indica 100%",
    "genetics": "OG Kush Phänotyp",
    "aromas": [
      "Zitrus",
      "Kiefer",
      "Diesel",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Myrcen",
      "Limonen"
    ]
  },
  "divine-gelato": {
    "description": "Eine indica-dominante Hybride, die das Beste der Gelato-Linie mit OG Kush kombiniert. Das Aroma ist eine köstliche Mischung aus fruchtigen, cremigen und gasigen Noten. Die Wirkung ist stark entspannend und euphorisch, ideal zum Entspannen am Abend.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Gelato #33 x OG Kush",
    "aromas": [
      "Fruchtig",
      "Cremig",
      "Gasig",
      "Süß"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "do-si-dos": {
    "description": "Eine potente indica-dominante Hybride mit einem süßen, erdigen und blumigen Aroma. Die Wirkung ist stark, beginnt mit einem warmen Körpergefühl, das sich im ganzen Körper ausbreitet und in einen tief entspannten, fast meditativen Zustand übergeht. Ideal für den Abend.",
    "typeDetails": "Indica 70% / Sativa 30%",
    "genetics": "OGKB (ein GSC-Phänotyp) x Face Off OG",
    "aromas": [
      "Süß",
      "Erdig",
      "Blumig",
      "Scharf"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Caryophyllen",
      "Linalool"
    ]
  },
  "do-si-woah": {
    "description": "Eine extrem potente indica-dominante Sorte, die für ihre starken, sedierenden Effekte bekannt ist. Sie hat ein komplexes Aroma von Erde, Gas und süßem Gebäck. Die Wirkung ist schwer und körperlich, ideal zur Linderung von starken Schmerzen und Schlaflosigkeit.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Do-Si-Dos x RBx4",
    "aromas": [
      "Erdig",
      "Gasig",
      "Süß",
      "Scharf"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Limonen"
    ]
  },
  "dogwalker-og": {
    "description": "Eine ausgewogene Hybride mit einem einzigartigen, scharfen Aroma von 'nassem Hund', Skunk und Erde. Die Wirkung ist stark zerebral und konzentriert, während sie den Körper entspannt, was sie überraschend funktional für erfahrene Konsumenten macht.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Albert Walker OG x Chemdawg 91",
    "aromas": [
      "Scharf",
      "Erdig",
      "Skunk",
      "Holzig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "donkey-butter": {
    "description": "Eine potente indica-dominante Sorte mit einem extrem scharfen Aroma von Diesel und erdigem Skunk. Die Wirkung ist tief sedierend und entspannend, führt oft zum Couch-Lock und ist am besten für den Abendgebrauch bei Schmerzen und Schlaflosigkeit geeignet.",
    "typeDetails": "Indica 70% / Sativa 30%",
    "genetics": "Grease Monkey x Triple OG",
    "aromas": [
      "Diesel",
      "Scharf",
      "Erdig",
      "Skunk"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "donny-burger": {
    "description": "Eine potente indica-dominante Hybride mit einem einzigartigen, herzhaften Aroma von Käse, Zwiebeln und einem Hauch Zitrone. Die Wirkung ist anfangs erhebend und euphorisch und geht dann in eine tief entspannende und beruhigende Körperwirkung über.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "GMO Cookies x Han-Solo Burger",
    "aromas": [
      "Käse",
      "Zwiebel",
      "Zitrus",
      "Scharf"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "dosi-cake": {
    "description": "Eine indica-dominante Hybride, die den süßen, erdigen Geschmack von Do-Si-Dos mit der cremigen Süße von Wedding Cake kombiniert. Die Wirkung ist stark entspannend und beruhigend, ideal zum Stressabbau und zur Linderung von Schmerzen am Abend.",
    "typeDetails": "Indica 70% / Sativa 30%",
    "genetics": "Do-Si-Dos x Wedding Cake",
    "aromas": [
      "Süß",
      "Erdig",
      "Vanille",
      "Blumig"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Caryophyllen"
    ]
  },
  "double-dream": {
    "description": "Eine sativa-dominante Hybride, die für ihre verträumte, sanfte und funktionale Wirkung bekannt ist. Sie bietet Schmerzlinderung und Entspannung ohne starke Sedierung, was sie zu einer guten Wahl für den Tagesgebrauch macht. Das Aroma ist süß und blumig.",
    "typeDetails": "Sativa 70% / Indica 30%",
    "genetics": "Blue Dream x Dream Star",
    "aromas": [
      "Süß",
      "Blumig",
      "Beere",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "dr-grinspoon": {
    "description": "Eine reine Sativa-Erbstücksorte, benannt nach dem Cannabis-Forscher Dr. Lester Grinspoon. Sie hat eine einzigartige, perlenartige Knospenstruktur. Die Wirkung ist rein zerebral, langanhaltend, energetisch und fördert die Konzentration. Eine Sorte für Kenner.",
    "typeDetails": "Sativa 100%",
    "genetics": "Unbekannte Erbstück-Sativa",
    "aromas": [
      "Zitrone",
      "Kiefer",
      "Würzig",
      "Tropisch"
    ],
    "dominantTerpenes": [
      "Terpinolen",
      "Limonen"
    ]
  },
  "dream-star": {
    "description": "Eine ausgewogene Hybride mit einem süßen Beeren- und Skunk-Aroma. Sie bietet eine entspannende und dennoch erhebende Wirkung, die ideal ist, um Stress abzubauen, während man geistig klar und funktionsfähig bleibt. Gut für den Nachmittags- oder Abendgebrauch.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Blue Dream x Stardawg",
    "aromas": [
      "Beere",
      "Süß",
      "Skunk",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "ducksfoot": {
    "description": "Eine einzigartige Sativa, benannt nach ihren ungewöhnlichen Blättern, die Schwimmhäuten ähneln und sie unauffällig machen. Die Wirkung ist erhebend und zerebral, aber nicht übermäßig stark. Das Aroma ist eine ungewöhnliche Mischung aus Pfeffer und Weihrauch.",
    "typeDetails": "Sativa 100%",
    "genetics": "Australische Sativa-Landrasse",
    "aromas": [
      "Pfeffer",
      "Weihrauch",
      "Erdig",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Myrcen"
    ]
  },
  "durban-poison": {
    "description": "Eine berühmte reine Sativa-Landrasse aus Südafrika. Sie ist bekannt für ihre extrem energetisierende, erhebende und konzentrationsfördernde Wirkung, was sie zu einer der beliebtesten Tagessorten macht. Das Aroma ist süß und würzig mit Noten von Anis.",
    "typeDetails": "Sativa 100%",
    "genetics": "Südafrikanische Landrasse",
    "aromas": [
      "Süß",
      "Würzig",
      "Anis",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Terpinolen",
      "Myrcen",
      "Ocimen"
    ]
  },
  "early-maroc": {
    "description": "Eine sehr schnell blühende Sativa, die speziell für den Outdoor-Anbau in kühleren Klimazonen gezüchtet wurde. Sie bietet eine klare, erhebende Wirkung und ein süßes, erdiges Aroma. Ideal für Züchter, die eine frühe Ernte anstreben.",
    "typeDetails": "Sativa 100%",
    "genetics": "Marokkanische Landrasse",
    "aromas": [
      "Süß",
      "Erdig",
      "Würzig",
      "Blumig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "early-pearl": {
    "description": "Eine klassische Outdoor-Sativa von Sensi Seeds, die für ihre Widerstandsfähigkeit gegen Schimmel und kühles Klima bekannt ist. Sie bietet ein erhebendes, klares Kopf-High mit einem Hauch von Körperentspannung. Das Aroma ist süß und skunkig.",
    "typeDetails": "Sativa 75% / Indica 25%",
    "genetics": "Early Girl x Pollyanna",
    "aromas": [
      "Süß",
      "Skunk",
      "Kiefer",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Terpinolen",
      "Myrcen"
    ]
  },
  "early-skunk": {
    "description": "Eine robuste und zuverlässige Sorte, die die schnelle Blüte und Widerstandsfähigkeit von Early Pearl mit der Potenz und dem Ertrag von Skunk #1 kombiniert. Ideal für Outdoor-Anbauer in kürzeren Sommern. Die Wirkung ist entspannend und glücklich.",
    "typeDetails": "Indica 65% / Sativa 35%",
    "genetics": "Skunk #1 x Early Pearl",
    "aromas": [
      "Skunk",
      "Süß",
      "Erdig",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinene"
    ]
  },
  "ed-rosenthal-super-bud": {
    "description": "Benannt nach dem legendären Cannabis-Anbauautor. Diese Hybride ist bekannt für ihre extrem dichten, harzigen Knospen und einen hohen Ertrag. Die Wirkung ist eine ausgewogene Mischung aus zerebraler Euphorie und entspannender Körperwirkung.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Unbekannte Afghani/Kush x (Haze x Sativa)",
    "aromas": [
      "Süß",
      "Fruchtig",
      "Ananas",
      "Skunk"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Terpinolene"
    ]
  },
  "el-chapo-og": {
    "description": "Eine potente indica-dominante Sorte, die für ihre starken, sedierenden Effekte bekannt ist. Sie hat ein scharfes Aroma von Kiefer, Diesel und Zitrone. Die Wirkung ist stark körperlich und ideal zur Linderung von Schmerzen und Schlaflosigkeit.",
    "typeDetails": "Indica 70% / Sativa 30%",
    "genetics": "Face Off OG x SFV OG x OG Kush",
    "aromas": [
      "Kiefer",
      "Diesel",
      "Zitrone",
      "Scharf"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonene",
      "Caryophyllen"
    ]
  },
  "electric-lemon-g": {
    "description": "Eine energetisierende sativa-dominante Sorte mit einem intensiven, scharfen Zitronenaroma. Die Wirkung ist stark zerebral, kreativ und erhebend, was sie zu einer ausgezeichneten Wahl für den Tagesgebrauch und soziale Aktivitäten macht.",
    "typeDetails": "Sativa 80% / Indica 20%",
    "genetics": "G13 x Northern Lights #5",
    "aromas": [
      "Zitrone",
      "Zitrus",
      "Scharf",
      "Sauer"
    ],
    "dominantTerpenes": [
      "Terpinolene",
      "Myrcen"
    ]
  },
  "eleven-roses": {
    "description": "Eine reine Indica von Delicious Seeds, bekannt für ihre schnelle Blütezeit und ihre beeindruckende Harzproduktion. Die Wirkung ist extrem stark, narkotisch und sedierend. Das Aroma ist eine komplexe Mischung aus süßen Früchten und feuchter Erde.",
    "typeDetails": "Indica 100%",
    "genetics": "Appalachian Kush x Sugar Black Rose",
    "aromas": [
      "Süß",
      "Fruchtig",
      "Metallisch",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonene",
      "Caryophyllen"
    ]
  },
  "elmers-glue": {
    "description": "Eine extrem klebrige und potente Hybride, benannt nach dem berühmten Klebstoff. Sie bietet ein starkes, euphorisches Kopf-High, das in eine schwere, entspannende Körperwirkung übergeht. Das Aroma ist scharf, mit Noten von Kiefer, Diesel und Schokolade.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Gorilla Glue #4 x White Widow",
    "aromas": [
      "Kiefer",
      "Diesel",
      "Schokolade",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Myrcen",
      "Limonene"
    ]
  },
  "emergen-c": {
    "description": "Eine sativa-dominante Sorte mit einem intensiven, süßen Orangen- und Zitrusaroma. Die Wirkung ist erhebend, energetisch und konzentrationsfördernd, was sie zu einer perfekten Wahl für den Morgen oder einen kreativen Schub am Nachmittag macht.",
    "typeDetails": "Sativa 70% / Indica 30%",
    "genetics": "Orange Push Pop x Sunset Sherbet",
    "aromas": [
      "Orange",
      "Zitrus",
      "Süß",
      "Diesel"
    ],
    "dominantTerpenes": [
      "Limonene",
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "emperor-cookies": {
    "description": "Eine potente indica-dominante Sorte, die für ihre extrem frostigen Knospen und ihre starke, entspannende Wirkung bekannt ist. Sie hat ein süßes, erdiges Keksaroma. Die Wirkung ist stark körperlich und ideal zur Linderung von Schmerzen und Stress.",
    "typeDetails": "Indica 70% / Sativa 30%",
    "genetics": "Emperor OG x Girl Scout Cookies",
    "aromas": [
      "Süß",
      "Erdig",
      "Keks",
      "Kiefer"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "ewok": {
    "description": "Eine indica-dominante Sorte, benannt nach den Star Wars-Charakteren. Sie produziert dichte, harzige Knospen mit einem süßen, fruchtigen und erdigen Aroma. Die Wirkung ist stark entspannend und beruhigend, ideal für den Abendgebrauch.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Albert Walker x Tahoe Alien",
    "aromas": [
      "Süß",
      "Fruchtig",
      "Erdig",
      "Kiefer"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Limonen"
    ]
  },
  "exodus-cheese": {
    "description": "Der ursprüngliche Klon, der in den 90er Jahren in Großbritannien berühmt wurde. Bekannt für sein extrem scharfes, einzigartiges Käsearoma. Die Wirkung ist stark, euphorisch und gesellig, mit einer angenehmen Körperentspannung. Eine soziale Sorte.",
    "typeDetails": "Hybrid 60% / Indica 40%",
    "genetics": "Skunk #1 Phänotyp",
    "aromas": [
      "Käse",
      "Scharf",
      "Skunk",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Myrcen",
      "Limonen"
    ]
  },
  "face-off-og": {
    "description": "Eine extrem potente Indica, deren Name von der intensiven Wirkung herrührt, die sich anfühlt, als würde sie einem das Gesicht 'abnehmen'. Bietet eine stark sedierende und entspannende Wirkung, ideal für medizinische Anwender. Das Aroma ist erdig und kiefernartig.",
    "typeDetails": "Indica 70% / Sativa 30%",
    "genetics": "OG Kush Phänotyp",
    "aromas": [
      "Erdig",
      "Kiefer",
      "Scharf",
      "Holzig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "fat-banana": {
    "description": "Eine schnell blühende, indica-dominante Sorte von Royal Queen Seeds mit einem süßen, intensiven Bananenaroma. Die Wirkung ist stark, körperlich entspannend und kann bei höherer Dosierung zu einem starken Couch-Lock führen. Ideal für den Abend.",
    "typeDetails": "Indica 70% / Sativa 30%",
    "genetics": "OG Kush x Chiquita Banana",
    "aromas": [
      "Banane",
      "Süß",
      "Tropisch",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "fire-og": {
    "description": "Gilt als eine der stärksten OG Kush-Hybriden. Der Name kommt von den roten Haaren, die die Knospen bedecken. Die Wirkung ist stark, langanhaltend und beginnt mit einem erhebenden, euphorischen Gefühl, das in eine starke Indica-Entspannung übergeht.",
    "typeDetails": "Indica 70% / Sativa 30%",
    "genetics": "OG Kush x SFV OG Kush",
    "aromas": [
      "Zitrone",
      "Kiefer",
      "Scharf",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "forbidden-fruit": {
    "description": "Eine indica-dominante Sorte mit einem unglaublich verlockenden Aroma von tropischen Früchten, Kirschen und Zitrus. Die Wirkung ist tief entspannend und beruhigend für Körper und Geist, ohne völlig zu sedieren. Ideal für den Abend.",
    "typeDetails": "Indica 70% / Sativa 30%",
    "genetics": "Cherry Pie x Tangie",
    "aromas": [
      "Fruchtig",
      "Kirsche",
      "Zitrus",
      "Tropisch",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "freakshow": {
    "description": "Eine einzigartige Sativa-Sorte, die für ihre ungewöhnliche farnartige Blattstruktur bekannt ist, die sie unauffällig macht. Die Wirkung ist erhebend, zerebral und kreativ. Das Aroma ist eine komplexe Mischung aus Kiefer, Gewürzen und Diesel.",
    "typeDetails": "Sativa 90% / Indica 10%",
    "genetics": "Unbekannte Sativa-Mutation",
    "aromas": [
      "Kiefer",
      "Würzig",
      "Diesel",
      "Holzig"
    ],
    "dominantTerpenes": [
      "Pinen",
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "french-toast": {
    "description": "Eine indica-dominante Sorte mit einem süßen, butterartigen und sirupartigen Aroma. Die Wirkung ist entspannend und beruhigend, ideal für einen gemütlichen Morgen oder Abend. Sie hilft, Stress abzubauen und die Stimmung zu heben.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Paris OG x Face Off OG",
    "aromas": [
      "Süß",
      "Butter",
      "Sirup",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "frisian-dew": {
    "description": "Eine preisgekrönte Outdoor-Sorte von Dutch Passion, bekannt für ihre hohe Schimmelresistenz und ihre schönen violetten Farben. Die Wirkung ist ausgewogen, mit einem erhebenden Sativa-High und einer sanften Indica-Entspannung. Ideal für kühlere Klimazonen.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Super Skunk x Purple Star",
    "aromas": [
      "Erdig",
      "Kiefer",
      "Zitrus",
      "Fruchtig"
    ],
    "dominantTerpenes": [
      "Pinen",
      "Myrcen",
      "Limonen"
    ]
  },
  "frisian-duck": {
    "description": "Eine weitere 'Stealth'-Sorte, die die einzigartige Entenfuß-Blattform mit der Robustheit von Frisian Dew kombiniert. Sie ist sehr unauffällig und ideal für den Guerilla-Anbau. Die Wirkung ist ausgewogen und das Aroma würzig und kiefernartig.",
    "typeDetails": "Sativa 50% / Indica 50%",
    "genetics": "DucksFoot x Frisian Dew",
    "aromas": [
      "Kiefer",
      "Würzig",
      "Zitrus",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Pinen",
      "Terpinolen",
      "Ocimen"
    ]
  },
  "frosted-guava": {
    "description": "Eine potente, indica-dominante Hybride mit einem süßen, tropischen und fruchtigen Geschmacksprofil. Die Wirkung ist stark entspannend und euphorisch, ideal zum Stressabbau und zur Förderung der Kreativität, bevor eine tiefe Entspannung einsetzt.",
    "typeDetails": "Indica 70% / Sativa 30%",
    "genetics": "Guava x Frosted Skywalker",
    "aromas": [
      "Guave",
      "Tropisch",
      "Fruchtig",
      "Süß"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "fruity-pebbles-og": {
    "description": "Eine limitierte Hybride, bekannt für ihren extrem süßen und fruchtigen Geschmack, der an die gleichnamigen Frühstücksflocken erinnert. Die Wirkung ist stark, euphorisch und entspannend, oft kichernd und glücklich machend. Ideal für den Abend.",
    "typeDetails": "Indica 55% / Sativa 45%",
    "genetics": "Green Ribbon x Granddaddy Purple x Tahoe Alien",
    "aromas": [
      "Fruchtig",
      "Süß",
      "Beere",
      "Tropisch"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Caryophyllen",
      "Myrcen"
    ]
  },
  "future": {
    "description": "Eine extrem potente Sorte von Anesia Seeds, die für ihren außergewöhnlich hohen THC-Gehalt bekannt ist. Die Wirkung ist intensiv, psychedelisch und langanhaltend, mit einem starken zerebralen Rausch und einer tiefen Körperentspannung. Nur für erfahrene Konsumenten.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Gorilla Glue #4 x Starfighter F2",
    "aromas": [
      "Ananas",
      "Mango",
      "Zitrus",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  }
}