// This file is generated by the translation script. Do not edit manually.
export const strainsData = {
  "acdc": {
    "description": "Eine berühmte CBD-dominante Sorte, gezüchtet für therapeutische Zwecke ohne starke psychoaktive Wirkung. Der Name steht für 'Alternative Cannabinoid Dietary Cannabis'. Wirkt entspannend und angstlösend, während der Geist klar bleibt. Ideal bei Schmerzen und Angstzuständen.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Cannatonic x Ruderalis",
    "aromas": [
      "Erdig",
      "Süß",
      "Holzig",
      "Kiefer",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "acapulco-gold": {
    "description": "Eine legendäre Landrassen-Sorte aus Acapulco, Mexiko, berühmt seit den 1960ern. Bekannt für ihre gold-braunen Knospen und eine energetisierende, euphorische und motivierende Wirkung. Der Geschmack erinnert an süßes, erdiges Toffee. Eine klassische 'Wake-and-Bake'-Sorte.",
    "typeDetails": "Sativa 80% / Indica 20%",
    "genetics": "Mexikanische Landrasse",
    "aromas": [
      "Erdig",
      "Süß",
      "Zitrus",
      "Kiefer",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Myrcen",
      "Limonen"
    ]
  },
  "acid-dough": {
    "description": "Eine preisgekrönte sativa-dominante Sorte von Ripper Seeds. Bietet einen schnell einsetzenden, euphorischen und kichernden Rausch, der den Geist beflügelt und den Körper leicht entspannt. Die Knospen sind dicht, dunkelgrün mit orangefarbenen Haaren und violetten Trichomen.",
    "typeDetails": "Sativa 80% / Indica 20%",
    "genetics": "Lilly (Queen Mother x Congo) x OG Badazz",
    "aromas": [
      "Süß-sauer",
      "Tropisch",
      "Ananas",
      "Erdig",
      "Bonbon"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Limonen"
    ]
  },
  "afghan-kush": {
    "description": "Eine Indica-Landrasse aus dem Hindukusch-Gebirge. Bekannt für ihre starke, fast narkotische Körperwirkung und hohe Harzproduktion, was sie ideal für die Haschischherstellung macht. Wirkt tief entspannend und sedierend. Ideal für den Abend und bei Schmerzen oder Schlaflosigkeit.",
    "typeDetails": "Indica 100%",
    "genetics": "Hindukusch Landrasse",
    "aromas": [
      "Erdig",
      "Würzig",
      "Kiefer",
      "Holzig",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "afghan-skunk": {
    "description": "Eine klassische indica-dominante Hybride, die die robuste Natur und die entspannende Wirkung von Afghani mit dem hohen Ertrag und dem scharfen Aroma von Skunk #1 kombiniert. Sie bietet eine tief entspannende Körperwirkung und ist bekannt für ihre einfache Handhabung und Widerstandsfähigkeit.",
    "typeDetails": "Indica 85% / Sativa 15%",
    "genetics": "Afghani x Skunk #1",
    "aromas": [
      "Skunk",
      "Erdig",
      "Süß",
      "Scharf"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "afghani": {
    "description": "Eine fundamentale Landrasse aus Afghanistan, die die genetische Grundlage für viele moderne Indicas bildet. Bietet eine tief entspannende und sedierende Wirkung, die Stress abbaut und bei Schlaflosigkeit hilft. Das Aroma ist erdig, süß und skunkig.",
    "typeDetails": "Indica 100%",
    "genetics": "Afghanische Landrasse",
    "aromas": [
      "Erdig",
      "Süß",
      "Skunk",
      "Würzig",
      "Kiefer"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "afgoo": {
    "description": "Auch bekannt als Afgooey. Eine potente indica-dominante Sorte, die für ihre extrem harzigen, klebrigen Knospen bekannt ist. Die Wirkung ist stark körperlich entspannend, fast sedierend, und führt zu einem euphorischen, glücklichen Zustand. Ideal für den Abendgebrauch bei Stress und Schlaflosigkeit.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Afghani x Maui Haze",
    "aromas": [
      "Erdig",
      "Kiefer",
      "Süß",
      "Würzig",
      "Holzig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen",
      "Ocimen"
    ]
  },
  "agent-orange": {
    "description": "Gezüchtet von MzJill Genetics. Bekannt für ihr intensives Zitrus- und Orangenaroma. Die Wirkung ist energetisierend, erhebend und kreativ, was sie zu einer ausgezeichneten Wahl für den Tag und soziale Anlässe macht. Hilft bei Müdigkeit und Depressionen.",
    "typeDetails": "Sativa 75% / Indica 25%",
    "genetics": "Orange Velvet x Jack The Ripper",
    "aromas": [
      "Orange",
      "Zitrus",
      "Süß",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Terpinolen",
      "Caryophyllen"
    ]
  },
  "agent-x": {
    "description": "Eine moderne, ausgewogene Hybride von Alien Labs (2022). Bietet ein komplexes Aroma von Apfel, Käse und Asphalt mit blumigen Noten. Die Wirkung ist stark, aber ausgewogen, mit einem erhebenden Kopf-High und einem entspannten Körpergefühl. Ideal für erfahrene Konsumenten.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Atomic Apple x Xeno #1",
    "aromas": [
      "Apfel",
      "Käse",
      "Diesel",
      "Blumig",
      "Minze"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Linalool"
    ]
  },
  "ak-47": {
    "description": "Eine legendäre, preisgekrönte Sorte von Serious Seeds (1992). Trotz des Namens ist die Wirkung sanft, erhebend und zerebral, gefolgt von einer milden Körperentspannung. Ideal für kreative und soziale Aktivitäten. Das Aroma ist erdig, süß und blumig.",
    "typeDetails": "Sativa 65% / Indica 35%",
    "genetics": "Kolumbianisch x Mexikanisch x Thailändisch x Afghanisch",
    "aromas": [
      "Erdig",
      "Süß",
      "Blumig",
      "Holzig",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "alaskan-ice": {
    "description": "Eine extrem potente sativa-dominante Sorte von Greenhouse Seed Co. Bietet einen sofortigen, erhebenden und euphorischen Rausch, der langsam in eine entspannende Körperwirkung übergeht. Bekannt für ihre hohe Harzproduktion, ideal für Extrakte.",
    "typeDetails": "Sativa 70% / Indica 30%",
    "genetics": "White Widow x Haze",
    "aromas": [
      "Würzig",
      "Holzig",
      "Erdig",
      "Pfeffer",
      "Sandelholz"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Limonen",
      "Pinen"
    ]
  },
  "alaskan-purple": {
    "description": "Eine robuste und ertragreiche Sorte, die bei kühleren Temperaturen schöne violette Farben entwickelt. Die indica-dominante Wirkung ist körperlich entspannend (Kush-Einfluss) mit einer zerebralen, erhebenden Note (Sativa-Einfluss). Das Aroma ist süß und beerig mit blumigen Noten.",
    "typeDetails": "Indica 70% / Sativa 30%",
    "genetics": "(Purple Alaskan x Kush) x Brasilianische Sativa",
    "aromas": [
      "Beere",
      "Süß",
      "Blumig",
      "Erdig",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Linalool"
    ]
  },
  "alaskan-thunder-fuck": {
    "description": "Alias: ATF. Eine legendäre Sativa aus dem Matanuska Valley in Alaska. Bekannt für einen intensiven, euphorischen und energetisierenden Rausch, der die Kreativität fördert. Das Aroma ist eine komplexe Mischung aus Kiefer, Zitrone, Menthol und Skunk.",
    "typeDetails": "Sativa 70% / Indica 30%",
    "genetics": "(Nordkalifornische Sativa x Russische Ruderalis) x Afghanisch",
    "aromas": [
      "Kiefer",
      "Zitrone",
      "Menthol",
      "Erdig",
      "Skunk"
    ],
    "dominantTerpenes": [
      "Pinen",
      "Linalool",
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "alien-dawg": {
    "description": "Eine reine Indica, die für ihr saures, dieselartiges Aroma und ihre potente, entspannende Wirkung bekannt ist. Sie ist eine der Elternsorten von Alien Kush und bietet eine starke zerebrale Wirkung, die in eine tiefe Körperentspannung übergeht.",
    "typeDetails": "Indica 100%",
    "genetics": "Chemdawg x Alien Technology",
    "aromas": [
      "Sauer",
      "Diesel",
      "Erdig",
      "Scharf",
      "Kiefer"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "alien-kush": {
    "description": "Eine ausgewogene Hybride mit einem würzigen, erdigen und kiefernartigen Aroma. Sie bietet eine klare, zerebrale Wirkung, die in eine sanfte Körperentspannung übergeht. Bekannt für ihre 'außerirdische' anmutende Wirkung, die die Wahrnehmung leicht verändern kann.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Las Vegas Purple Kush x Alien Dawg",
    "aromas": [
      "Würzig",
      "Erdig",
      "Kiefer",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "alien-og": {
    "description": "Auch bekannt als Alien OG Kush. Eine hochpotente Hybride, die für ihren intensiven, fast psychedelischen zerebralen Rausch in Kombination mit einer schweren Körperwirkung bekannt ist. Ideal für erfahrene Konsumenten. Das Aroma ist eine klassische OG-Mischung aus Zitrone, Kiefer und Erde.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Tahoe OG x Alien Kush",
    "aromas": [
      "Kiefer",
      "Zitrone",
      "Erdig",
      "Süß",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "alien-rock-candy": {
    "description": "Eine potente indica-dominante Sorte mit einem süßen, bonbonartigen Geschmacksprofil, das durch saure und erdige Noten ergänzt wird. Die Wirkung ist stark entspannend und sedierend, ideal zur Linderung von Schmerzen, Stress und Schlaflosigkeit am Ende des Tages.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Sour Dubble x Tahoe Alien",
    "aromas": [
      "Süß",
      "Beere",
      "Zitrus",
      "Sauer",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen",
      "Nerolidol"
    ]
  },
  "american-dream": {
    "description": "Eine schnell blühende, ertragreiche Sorte von Sensi Seeds. Bietet eine euphorische, gesellige und entspannende Wirkung ohne starken 'Couch-Lock'. Das Aroma ist erdig und skunkig mit frischen, tropisch-fruchtigen Noten. Ideal für kommerzielle Züchter und Anfänger.",
    "typeDetails": "Indica 75% / Sativa 25%",
    "genetics": "Afghan Skunk x (Jamaikanisch x Hawaiianisch)",
    "aromas": [
      "Erdig",
      "Skunk",
      "Kiefer",
      "Fruchtig",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen",
      "Limonen"
    ]
  },
  "amnesia": {
    "description": "Eine legendäre Sorte, die in den Amsterdamer Coffeeshops berühmt wurde. Bekannt für einen starken, zerebralen, euphorischen und energetisierenden Rausch. Trotz des Namens fördert sie die Kreativität und Geselligkeit. Das Aroma ist erdig mit süßen Zitrusnoten.",
    "typeDetails": "Sativa 70% / Indica 30%",
    "genetics": "Unbekannt (oft mit Skunk, Cinderella 99, Jack Herer assoziiert)",
    "aromas": [
      "Zitrus",
      "Erdig",
      "Süß",
      "Blumig",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Humulen",
      "Ocimen",
      "Terpinolen"
    ]
  },
  "amnesia-haze": {
    "description": "Eine mehrfache Cannabis-Cup-Gewinnerin, berühmt für ihre potente, langanhaltende und fast psychedelische zerebrale Wirkung. Fördert Energie, Euphorie und Kreativität. Das Aroma ist eine komplexe Mischung aus Zitrone, Zitrusfrüchten, Erde und Gewürzen.",
    "typeDetails": "Sativa 80% / Indica 20%",
    "genetics": "Diverse Landrassen (Südasiatisch, Jamaikanisch, etc.)",
    "aromas": [
      "Zitrus",
      "Zitrone",
      "Erdig",
      "Würzig",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "amnesia-lemon": {
    "description": "Eine preisgekrönte Sorte (Cannabis Cup 2004), die für ihren intensiven Zitrus- und Zitronengeschmack bekannt ist. Die Wirkung ist erhebend, zerebral und energetisierend, typisch für eine Sativa, aber mit einer entspannenden körperlichen Komponente. Ideal für den Tagesgebrauch.",
    "typeDetails": "Sativa 60% / Indica 40%",
    "genetics": "Amnesia Haze x Lemon Skunk",
    "aromas": [
      "Zitrone",
      "Zitrus",
      "Süß",
      "Würzig",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Ocimen",
      "Terpinolen",
      "Limonen"
    ]
  },
  "animal-cookies": {
    "description": "Eine potente, indica-dominante Hybride, die eine schwere Ganzkörperentspannung bietet, die ideal zur Linderung von Schmerzen und Schlaflosigkeit ist. Sie hat ein süßes, saures Aroma mit schweren, erdigen Noten.",
    "typeDetails": "Indica 75% / Sativa 25%",
    "genetics": "GSC x Fire OG",
    "aromas": [
      "Süß",
      "Sauer",
      "Erdig",
      "Nussig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "animal-mints": {
    "description": "Gezüchtet von Seed Junky Genetics. Eine hochpotente Hybride mit einem komplexen Aroma von Minze, Keksteig, Vanille und einem Hauch Diesel. Die Wirkung ist stark und ausgewogen, beginnend mit einem euphorischen Kopf-High, das in eine tiefe, sedierende Körperentspannung übergeht.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Animal Cookies x SinMint Cookies (oder andere GSC-Kreuzungen)",
    "aromas": [
      "Minze",
      "Süß",
      "Keksteig",
      "Erdig",
      "Diesel"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen",
      "Pinen"
    ]
  },
  "appalachian-kush": {
    "description": "Eine potente Hybride mit einem erdigen, süßen und leicht würzigen Aroma. Sie bietet eine ausgewogene Wirkung, die mit einem zerebralen, energetischen Schub beginnt und in eine entspannende Körperwirkung übergeht. Ideal zur Linderung von Stress und Schmerzen, ohne völlig zu sedieren.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Green Crack x Tres Dawg",
    "aromas": [
      "Erdig",
      "Süß",
      "Würzig",
      "Kiefer"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Limonen"
    ]
  },
  "apple-betty": {
    "description": "Eine potente Hybride mit einem köstlichen Geschmacksprofil, das an gebackenen Apfelkuchen mit Zimt- und Schokoladennoten erinnert. Die Wirkung ist schnell einsetzend, euphorisch und kichernd, fast psychedelisch, gefolgt von einer tiefen Körperentspannung.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Sour Apple x Animal Cookies (oder Chem's Sister x Sour Apple x Chocolate Diesel)",
    "aromas": [
      "Apfel",
      "Süß",
      "Erdig",
      "Gebäck",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Humulen"
    ]
  },
  "apple-cobbler": {
    "description": "Eine ausgewogene Hybride mit einem fruchtigen, säuerlichen Geschmacksprofil von Apfel und Erde. Die Wirkung setzt langsam ein, beginnend mit einem zerebralen Auftrieb, der die Stimmung und Kreativität fördert, und geht in eine beruhigende Körperentspannung über. Ideal für Stress- und Schmerzabbau.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Blueberry Moonshine x Sour Apple (oder Sour Apple x Animal Cookies)",
    "aromas": [
      "Apfel",
      "Süß",
      "Erdig",
      "Kiefer",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Linalool"
    ]
  },
  "apple-fritter": {
    "description": "Eine extrem potente Hybride, die für ihren hohen THC-Gehalt und ihren köstlichen Geschmack nach süßem Apfelgebäck bekannt ist. Die Wirkung ist stark und ausgewogen, beginnend mit einem euphorischen und kreativen Rausch, der in eine tief entspannende Körperwirkung übergeht.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Sour Apple x Animal Cookies",
    "aromas": [
      "Apfel",
      "Süß",
      "Erdig",
      "Gebäck",
      "Vanille"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Humulen",
      "Pinen"
    ]
  },
  "apple-jack": {
    "description": "Eine potente Hybride, die erhebende und beruhigende Effekte bietet. Ideal zur Behandlung von chronischen Schmerzen oder Übelkeit. Das Geschmacksprofil ist skunkig und erdig mit Untertönen von geschnittenem Apfel. Die sativa-dominante Wirkung ist energetisierend und kreativ.",
    "typeDetails": "Sativa 70% / Indica 30%",
    "genetics": "Jack Herer x White Widow",
    "aromas": [
      "Apfel",
      "Süß",
      "Erdig",
      "Skunk",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Myrcen",
      "Limonen",
      "Pinen"
    ]
  },
  "apples-and-bananas": {
    "description": "Gezüchtet von Compound Genetics & Cookies. Bietet ein komplexes Fruchtaroma von Äpfeln, Bananen, Kirschen und Gewürzen. Die Wirkung ist ausgewogen und potent, was zu einem glücklichen und entspannten Gefühl führt, das den Körper beruhigt, aber den Geist aktiv hält. Perfekt für den Nachmittag.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "[(Platinum Cookies x Granddaddy Purple) x Blue Power] x Gelatti",
    "aromas": [
      "Apfel",
      "Banane",
      "Fruchtig",
      "Süß",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen",
      "Linalool"
    ]
  },
  "atomic-apple": {
    "description": "Eine ausgewogene Hybride von Alien Labs. Sie kombiniert den minzigen, erdigen Geschmack von Triangle Mints mit dem süßen Apfelgebäck von Apple Fritter. Die Wirkung ist stark, euphorisch und entspannend, geeignet für den ganzen Tag.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Triangle Mints x Apple Fritter",
    "aromas": [
      "Apfel",
      "Süß",
      "Minze",
      "Erdig",
      "Vanille"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "aurora-indica": {
    "description": "Gezüchtet von Nirvana Seeds. Eine potente F1-Hybride, die schwere Ganzkörpereffekte und eine sedierende zerebrale Ruhe erzeugt. Ideal für die abendliche Behandlung von Schlaflosigkeit und Schmerzen. Die Pflanzen sind kurz, robust und produzieren dichte, harzige Knospen.",
    "typeDetails": "Indica 90% / Sativa 10%",
    "genetics": "Afghan x Northern Lights",
    "aromas": [
      "Erdig",
      "Würzig",
      "Holzig",
      "Süß",
      "Blumig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "auto-duck": {
    "description": "Eine einzigartige 'Stealth'-Sorte von Dutch Passion mit einer natürlichen Blattmutation (Entenfußform), die sie unauffällig macht. Der Geruch ist subtil. Die Wirkung ist ausgewogen und moderat, ideal für den Tagesgebrauch. Sehr robust und einfach anzubauen.",
    "typeDetails": "Sativa 50% / Indica 50% (Autoflower)",
    "genetics": "Frisian Duck x Auto White Widow",
    "aromas": [
      "Erdig",
      "Blumig",
      "Fruchtig",
      "Minze",
      "Kiefer"
    ],
    "dominantTerpenes": [
      "Terpinolen",
      "Caryophyllen",
      "Myrcen"
    ]
  },
  "auto-white-widow": {
    "description": "Die autoflowering Version der legendären White Widow. Sie behält die potente, ausgewogene Wirkung und das würzig-erdige Aroma des Originals bei, wächst aber schneller und einfacher. Ideal für Anfänger.",
    "typeDetails": "Hybrid 50% / 50% (Autoflower)",
    "genetics": "White Widow x Ruderalis",
    "aromas": [
      "Erdig",
      "Würzig",
      "Kiefer",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "ayahuasca-purple": {
    "description": "Eine reine Indica von Barney's Farm, bekannt für ihre atemberaubenden violetten und rubinroten Farben. Die Wirkung ist tief entspannend, beruhigend und kann psychedelische Züge annehmen. Das Aroma ist exotisch mit Noten von Haselnuss und Papaya. Sehr ertragreich.",
    "typeDetails": "Indica 100%",
    "genetics": "Red River Delta x Master Kush",
    "aromas": [
      "Papaya",
      "Haselnuss",
      "Tropisch",
      "Erdig",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "b-52": {
    "description": "Eine indica-dominante Hybride, die für ihre entspannende und dennoch erhebende Wirkung bekannt ist. Sie sorgt für eine sanfte zerebrale Stimulation, die Stress abbaut, gefolgt von einer warmen, beruhigenden Körperwirkung. Ideal für den späten Nachmittag oder Abend.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Skunk #1 x Big Bud",
    "aromas": [
      "Süß",
      "Erdig",
      "Skunk",
      "Blumig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "banana-kush": {
    "description": "Eine indica-dominante Hybride, berühmt für ihr starkes Bananenaroma und ihren Geschmack. Sie liefert einen sanften, euphorischen Rausch, der Kreativität und soziale Interaktion fördert und gleichzeitig eine tiefe körperliche Entspannung bietet. Hervorragend zum Stressabbau.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Ghost OG x Skunk Haze",
    "aromas": [
      "Banane",
      "Süß",
      "Tropisch",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "banana-og": {
    "description": "Eine potente indica-dominante Hybride mit einem ausgeprägten Aroma von überreifen Bananen. Die Wirkung ist schleichend und stark, was zu tiefer Entspannung und oft zu Schläfrigkeit führt. Am besten für den Abendgebrauch geeignet, um Schlaflosigkeit und Schmerzen zu bekämpfen.",
    "typeDetails": "Indica 70% / Sativa 30%",
    "genetics": "OG Kush x Banana",
    "aromas": [
      "Banane",
      "Süß",
      "Erdig",
      "Scharf"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "bay-platinum-cookies": {
    "description": "Eine Hybridsorte, die ein Phänotyp von Girl Scout Cookies ist. Sie bietet ein ausgewogenes High, das mit einem zerebralen Rausch beginnt und in eine angenehme Körperentspannung übergeht. Das Aroma ist süß und erdig mit würzigen Noten.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Bay 11 x Platinum Cookies",
    "aromas": [
      "Süß",
      "Erdig",
      "Würzig",
      "Kräuterartig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "bc-bud": {
    "description": "Ein allgemeiner Begriff für hochwertiges Cannabis aus British Columbia, Kanada. Wenn er sich auf eine bestimmte Sorte bezieht, handelt es sich oft um eine potente indica-dominante Hybride, die für ein starkes, entspannendes Körper-High bekannt ist. Das Aroma ist typischerweise skunkig und erdig.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Variiert, oft ein Skunk-Phänotyp",
    "aromas": [
      "Erdig",
      "Skunk",
      "Süß",
      "Kiefer"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "bedica-talea": {
    "description": "Eine medizinische Cannabissorte von Bedrocan, standardisiert für Konsistenz. Es ist eine starke Indica, die für ihre sedierenden und schmerzlindernden Eigenschaften bekannt ist und häufig bei Schlafstörungen, chronischen Schmerzen und Übelkeit eingesetzt wird.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Proprietär",
    "aromas": [
      "Erdig",
      "Würzig",
      "Kräuterartig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "bediol-elida": {
    "description": "Eine ausgewogene THC:CBD-Medizinalsorte von Bedrocan. Der hohe CBD-Gehalt mildert die psychoaktiven Effekte von THC, was sie für Patienten geeignet macht, die Linderung bei Entzündungen, Angst und Schmerzen ohne ein starkes 'High' suchen.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Proprietär",
    "aromas": [
      "Erdig",
      "Süß",
      "Zitrus"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Terpinolen"
    ]
  },
  "bedrocan-afina": {
    "description": "Die Flaggschiff-Medizinal-Sativa von Bedrocan, bekannt für ihren hohen THC-Gehalt und ihre standardisierte Qualität. Sie bietet eine erhebende, energetische und klar-köpfige Wirkung, die oft bei ADHS, Depressionen und Müdigkeit eingesetzt wird.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Jack Herer Phänotyp",
    "aromas": [
      "Würzig",
      "Haze",
      "Erdig",
      "Zitrus"
    ],
    "dominantTerpenes": [
      "Terpinolen",
      "Myrcen"
    ]
  },
  "bedrolite-rensina": {
    "description": "Eine CBD-dominante Medizinalsorte von Bedrocan mit minimalem THC. Sie ist für Patienten, einschließlich Kindern, konzipiert, die die therapeutischen Vorteile von CBD für Erkrankungen wie Epilepsie und Entzündungen ohne psychoaktive Effekte benötigen.",
    "typeDetails": "CBD-dominante Hybride",
    "genetics": "Proprietär",
    "aromas": [
      "Erdig",
      "Kräuterartig",
      "Dezent"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Bisabolol"
    ]
  },
  "big-bud": {
    "description": "Eine indica-dominante Hybride, berühmt für ihre massiven Erträge. Wie der Name schon sagt, produziert sie außergewöhnlich große und schwere Blüten. Die Wirkung ist tief entspannend und sedierend, perfekt zur Bekämpfung von Stress und Schlaflosigkeit.",
    "typeDetails": "Indica 85% / Sativa 15%",
    "genetics": "Afghani x Northern Lights x Skunk #1",
    "aromas": [
      "Süß",
      "Erdig",
      "Skunk",
      "Fruchtig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "birthday-cake-kush": {
    "description": "Eine indica-dominante Hybride mit einem köstlichen süßen, kuchenartigen Geschmack. Sie bietet ein starkes Körper-High, das tief entspannend und euphorisch ist, was sie ideal macht, um das Ende eines langen Tages zu feiern. Hilft bei Schmerzen, Angst und Schlaflosigkeit.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Girl Scout Cookies x Cherry Pie",
    "aromas": [
      "Süß",
      "Vanille",
      "Erdig",
      "Nussig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "biscotti": {
    "description": "Eine potente indica-dominante Hybride, bekannt für ihr köstliches Geschmacksprofil aus süßen Keksen mit Diesel-Untertönen. Das High ist zerebral und glückselig, schnell gefolgt von einem entspannenden Körper-Buzz, der sich von Kopf bis Fuß ausbreitet.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Gelato #25 x Girl Scout Cookies x South Florida OG",
    "aromas": [
      "Süß",
      "Keks",
      "Diesel",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "biscotti-mintz": {
    "description": "Eine optisch auffällige, potente indica-dominante Sorte von Barney's Farm. Sie zeichnet sich durch tiefviolette Farbtöne und ein komplexes Aroma von Minz-Schokoladenkeksen und Gewürzen aus. Die Wirkung ist anfangs kreativ und fokussiert und geht dann in ein beruhigendes und entspannendes Körper-High über.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Biscotti x Kush Mints",
    "aromas": [
      "Minze",
      "Schokolade",
      "Würzig",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Caryophyllen",
      "Eukalyptol"
    ]
  },
  "black-beauty": {
    "description": "Eine seltene Sativa-Sorte, die für ihr außergewöhnlich dunkles, fast schwarzes Laub und ihre Blüten bekannt ist. Sie enthält THCV, das dafür bekannt ist, ein klar-köpfiges, anregendes und kürzer anhaltendes High im Vergleich zu THC zu erzeugen. Das Aroma ist blumig und süß.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Unbekannt",
    "aromas": [
      "Blumig",
      "Süß",
      "Kräuterartig"
    ],
    "dominantTerpenes": [
      "Terpinolen"
    ]
  },
  "black-cherry-soda": {
    "description": "Eine gut ausbalancierte Hybride, benannt nach ihrer dunklen Färbung und ihrem fruchtigen, soda-artigen Geschmack. Sie bietet eine ausgewogene Wirkung, die mit zerebraler Stimulation beginnt und in einen ruhigen, entspannten Zustand übergeht, was sie für den Tagesgebrauch geeignet macht.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Unbekannt",
    "aromas": [
      "Kirsche",
      "Beere",
      "Süß",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Limonen"
    ]
  },
  "black-dahlia": {
    "description": "Eine indica-dominante Hybride mit schönen dunkelvioletten Blüten. Das Aroma ist süß und blumig mit erdigen Untertönen. Sie bietet ein entspannendes und euphorisches High, das perfekt zum Entspannen ohne starke Sedierung ist.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Black Cherry Soda x Querkle",
    "aromas": [
      "Blumig",
      "Süß",
      "Beere",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "black-domina": {
    "description": "Eine potente, schnell blühende indica-dominante Hybride. Sie produziert dunkle, dichte und harzige Blüten. Die Wirkung ist stark sedierend und narkotisch, was sie zu einem Favoriten für den nächtlichen Gebrauch zur Bekämpfung von Schmerzen und Schlaflosigkeit macht. Das Aroma ist pfeffrig und erdig.",
    "typeDetails": "Indica 95% / Sativa 5%",
    "genetics": "Afghani x Ortega x Northern Lights x Hash Plant",
    "aromas": [
      "Pfeffer",
      "Erdig",
      "Würzig",
      "Kiefer"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "black-jack": {
    "description": "Eine Hybridsorte, die die erhebende Wirkung von Jack Herer mit der starken Harzproduktion von Black Domina kombiniert. Sie bietet ein langanhaltendes, glückseliges und kreatives High, das sowohl zerebral stimulierend als auch körperlich entspannend ist.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Black Domina x Jack Herer",
    "aromas": [
      "Erdig",
      "Kiefer",
      "Holzig",
      "Süß"
    ],
    "dominantTerpenes": [
      "Terpinolen",
      "Myrcen",
      "Ocimen"
    ]
  },
  "black-runtz": {
    "description": "Ein Phänotyp der berühmten Runtz-Sorte, der sich durch seine außergewöhnlich dunklen, fast schwarzen Blüten auszeichnet. Er teilt das gleiche süße, bonbonartige Geschmacksprofil und bietet ein euphorisches, langanhaltendes High, das den Körper entspannt und den Geist erhebt.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Zkittlez x Gelato",
    "aromas": [
      "Süß",
      "Fruchtig",
      "Bonbon",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "black-tuna": {
    "description": "Eine potente indica-dominante Hybride, die von kanadischen Züchtern erschaffen wurde. Sie ist bekannt für ihr extrem scharfes, fischiges und skunkiges Aroma. Das High ist stark und sedierend, führt oft zu einem 'Couch-Lock' und ist ideal bei starken Schmerzen und Schlaflosigkeit.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Herijuana x Lamb's Bread",
    "aromas": [
      "Scharf",
      "Skunk",
      "Erdig",
      "Diesel"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "blackberry": {
    "description": "Eine gut ausbalancierte Hybride, bekannt für ihren köstlichen Geschmack nach frischen Brombeeren. Das High ist entspannend und euphorisch und vermittelt ein Gefühl von Glück und Wohlbefinden. Sie ist wirksam bei der Behandlung von Schmerzen und Stress, während der Konsument funktionsfähig bleibt.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Black Domina x Raspberry Cough",
    "aromas": [
      "Brombeere",
      "Süß",
      "Fruchtig",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Limonen"
    ]
  },
  "blackberry-kush": {
    "description": "Eine starke indica-dominante Sorte mit einem süßen Brombeeraroma, gemischt mit dem klassischen Kraftstoffgeruch von Kush. Sie bietet ein potentes, entspannendes Körper-High, das sich hervorragend zur Schmerzlinderung, Stressreduktion und zum Schlafen eignet.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Afghani x Blackberry",
    "aromas": [
      "Brombeere",
      "Süß",
      "Erdig",
      "Diesel"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Limonen"
    ]
  },
  "blackwater": {
    "description": "Eine Indica-Sorte mit tiefvioletten Blüten und einem süßen Traubenaroma. Sie beginnt mit einem euphorischen Kopfrausch, der in einen beruhigenden, Ganzkörper-Buzz übergeht. Sie ist sehr wirksam bei Schmerzen, Appetitanregung und Schlaf.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Mendo Purps x San Fernando Valley OG Kush",
    "aromas": [
      "Traube",
      "Süß",
      "Erdig",
      "Kiefer"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "blue-cheese": {
    "description": "Eine indica-dominante Hybride, berühmt für ihr einzigartiges Geschmacksprofil, das die süßen, fruchtigen Noten von Blueberry mit dem herzhaften, käsigen Aroma von UK Cheese kombiniert. Die Wirkung ist tief entspannend und beruhigend, perfekt zum Entspannen am Ende des Tages.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Blueberry x UK Cheese",
    "aromas": [
      "Käse",
      "Blaubeere",
      "Süß",
      "Scharf"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Myrcen",
      "Limonen"
    ]
  },
  "blue-cookies": {
    "description": "Eine potente indica-dominante Hybride, die eine erdrückende Welle der Euphorie gefolgt von tiefer Körperentspannung liefert. Sie hat einen süßen Beeren- und Kirschgeschmack mit erdigen Untertönen. Hervorragend zur Schmerzlinderung und Entspannung.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Girl Scout Cookies x Blueberry",
    "aromas": [
      "Beere",
      "Kirsche",
      "Süß",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Humulen"
    ]
  },
  "blue-diamond": {
    "description": "Eine potente indica-dominante Hybride, die mit einer dicken Schicht Trichome glänzt. Sie bietet ein starkes, langanhaltendes High, das sowohl zerebral erhebend als auch körperlich entspannend ist. Das Aroma ist eine Mischung aus erdigem Kiefer und süßer Beere.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Diamond OG x Blue Dream",
    "aromas": [
      "Erdig",
      "Kiefer",
      "Beere",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "blue-dream": {
    "description": "Eine legendäre sativa-dominante Hybride aus Kalifornien. Sie bietet ein ausgewogenes High mit sanfter zerebraler Stimulation und Ganzkörperentspannung. Ihr süßes Beerenaroma macht sie zu einem Favoriten für Anfänger und erfahrene Konsumenten. Ideal für die Schmerzlinderung am Tag.",
    "typeDetails": "Sativa 60% / Indica 40%",
    "genetics": "Blueberry x Haze",
    "aromas": [
      "Blaubeere",
      "Süß",
      "Erdig",
      "Kräuterartig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "blue-dream-cbd": {
    "description": "Eine CBD-reiche Version der klassischen Blue Dream. Sie bietet das gleiche süße Beerenaroma und sanfte Erhebung, aber mit deutlich reduzierter Psychoaktivität aufgrund des ausgewogenen 1:1 THC:CBD-Verhältnisses. Ideal für therapeutische Anwender, die Linderung ohne ein starkes High suchen.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Blue Dream x California Orange CBD",
    "aromas": [
      "Blaubeere",
      "Süß",
      "Zitrus",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "blue-dream-matic": {
    "description": "Eine autoflowering Version von Blue Dream, die die gleichen beliebten Effekte und Geschmäcker in einem schnelleren, einfacher anzubauenden Paket bietet. Das High ist euphorisch und erhebend, perfekt für kreative Tätigkeiten und den Tagesgebrauch.",
    "typeDetails": "Sativa-dominante Hybride (Autoflower)",
    "genetics": "Blue Dream x Ruderalis",
    "aromas": [
      "Beere",
      "Süß",
      "Erdig",
      "Zitrus"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "blue-gelato-41": {
    "description": "Eine potente indica-dominante Hybride von Barney's Farm. Sie kombiniert die fruchtigen Aromen von Blueberry mit der cremigen Süße von Gelato. Die Wirkung ist anfangs klar-köpfig und energetisch, gefolgt von einer angenehmen Körperentspannung. Außergewöhnlich ertragreich im Freien.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Blueberry x Thin Mint GSC x Sunset Sherbet",
    "aromas": [
      "Beere",
      "Zitrus",
      "Süß",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "blue-hawaiian": {
    "description": "Eine sativa-dominante Hybride mit einem tropischen, fruchtigen Geschmack, der an Ananas und Beeren erinnert. Sie bietet ein fröhliches, euphorisches High, das perfekt für soziale Situationen und kreative Unternehmungen ist. Das High ist ausgewogen mit einer leichten Körperentspannung.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Blueberry x Hawaiian Sativa",
    "aromas": [
      "Tropisch",
      "Ananas",
      "Beere",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Terpinolen"
    ]
  },
  "blue-magoo": {
    "description": "Eine indica-dominante Hybride, bekannt für ihr komplexes Geschmacksprofil aus Beeren-, Frucht- und Blumennoten. Sie liefert ein entspannendes und euphorisches High, das funktional genug für den Tagesgebrauch ist, aber in größeren Dosen sedierend wirken kann.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "DJ Short Blueberry x Major League Bud (Williams Wonder)",
    "aromas": [
      "Beere",
      "Fruchtig",
      "Blumig",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "blue-power": {
    "description": "Eine potente indica-dominante Hybride, die dichte, trichom-bedeckte Blüten produziert. Das Aroma ist eine süß-saure Mischung aus Beeren und Zitrone. Das High ist stark, beginnt mit einer euphorischen Erhebung und endet in tiefer Entspannung.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "The Power x Master Kush x Blue Moonshine x Sour Double",
    "aromas": [
      "Beere",
      "Zitrone",
      "Süß",
      "Sauer"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "blue-walker": {
    "description": "Eine potente sativa-dominante Hybride mit einem einzigartigen fruchtigen, süßen und erdigen Aroma. Sie liefert ein starkes, schnell wirkendes zerebrales High, das energetisch und motivierend ist, ideal für Produktivität und kreative Aufgaben.",
    "typeDetails": "Sativa 90% / Indica 10%",
    "genetics": "Blue Dream x Skywalker",
    "aromas": [
      "Fruchtig",
      "Süß",
      "Erdig",
      "Beere"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "blue-zushi": {
    "description": "Eine potente indica-dominante Hybride, bekannt für ihr schönes Aussehen und ihren komplexen Geschmack. Sie kombiniert die fruchtigen Noten von Zkittlez mit der kushigen Erdigkeit von Kush Mints. Das High ist entspannend und euphorisch, perfekt zum Entspannen.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Zkittlez x Kush Mints",
    "aromas": [
      "Fruchtig",
      "Erdig",
      "Würzig",
      "Süß"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Caryophyllen",
      "Linalool"
    ]
  },
  "blueberry": {
    "description": "Eine klassische indica-dominante Sorte, die 2000 den High Times Cannabis Cup gewonnen hat. Sie ist berühmt für ihr unverkennbares frisches Blaubeeraroma und ihren Geschmack. Das High ist langanhaltend, euphorisch und tief entspannend.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Purple Thai x Afghani",
    "aromas": [
      "Blaubeere",
      "Süß",
      "Fruchtig",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "blueberry-haze": {
    "description": "Eine sativa-dominante Hybride, die den süßen Geschmack von Blueberry mit den zerebralen Effekten von Haze kombiniert. Das High ist erhebend, kreativ und energetisch, was sie zu einer großartigen Wahl für den Tagesgebrauch und soziale Aktivitäten macht.",
    "typeDetails": "Sativa 80% / Indica 20%",
    "genetics": "Blueberry x Haze",
    "aromas": [
      "Blaubeere",
      "Süß",
      "Haze",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Terpinolen",
      "Pinen"
    ]
  },
  "blueberry-og": {
    "description": "Eine indica-dominante Hybride, die die süßen Beerenaromen von Blueberry mit dem klassischen erdigen Kiefer von OG Kush verbindet. Sie bietet ein ausgewogenes High, das sowohl zerebral erhebend als auch körperlich entspannend ist, wirksam bei Stress und Schmerzen.",
    "typeDetails": "Indica 70% / Sativa 30%",
    "genetics": "Blueberry x OG Kush",
    "aromas": [
      "Blaubeere",
      "Erdig",
      "Kiefer",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "booger": {
    "description": "Eine sehr potente indica-dominante Hybride mit einem funkigen, scharfen Aroma von Skunk und Diesel. Das High ist schwer und sedierend, führt oft zu einem 'Couch-Lock' und einem starken Heißhunger. Am besten für erfahrene Konsumenten und den nächtlichen Gebrauch.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Bubba Kush x Strawberry Cough",
    "aromas": [
      "Scharf",
      "Skunk",
      "Diesel",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "bruce-banger": {
    "description": "Eine potente sativa-dominante Hybride, die die Kraft von Bruce Banner mit dem klassischen Geschmack von OG Kush kombiniert. Das High ist schnell wirkend, euphorisch und energetisch und regt Kreativität und Konzentration an. Der Geschmack ist eine Mischung aus Diesel und süßer Zitrone.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Bruce Banner x OG Kush",
    "aromas": [
      "Diesel",
      "Süß",
      "Zitrus",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "bruce-banner": {
    "description": "Benannt nach dem Alter Ego des Hulk, ist dies eine kraftvolle sativa-dominante Hybride. Sie ist bekannt für ihren unglaublich hohen THC-Gehalt und ein schnell wirkendes, euphorisches und kreatives High, das sich schließlich in einen Zustand der Entspannung einpendelt. Das Aroma ist eine starke Mischung aus Diesel und süßer Beere.",
    "typeDetails": "Sativa 60% / Indica 40%",
    "genetics": "OG Kush x Strawberry Diesel",
    "aromas": [
      "Diesel",
      "Süß",
      "Beere",
      "Scharf"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "bubba-fett": {
    "description": "Eine potente indica-dominante Hybride, benannt nach dem Star Wars Kopfgeldjäger. Sie bietet ein schweres, entspannendes Körper-High, das dich in einer 'Karbonit-ähnlichen' Entspannung gefangen halten kann. Das Aroma ist erdig und scharf mit süßen Untertönen.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Stardawg x Pre-98 Bubba Kush",
    "aromas": [
      "Erdig",
      "Scharf",
      "Süß",
      "Diesel"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "bubba-kush": {
    "description": "Eine klassische Indica-Sorte, die für ihre stark beruhigende Wirkung bekannt ist. Sie hat einen süßen, haschartigen Geschmack mit Noten von Schokolade und Kaffee. Das High ist tief entspannend und führt oft zu Schläfrigkeit. Ein Favorit zur Schmerz- und Schlaflosigkeitslinderung.",
    "typeDetails": "Indica 90% / Sativa 10%",
    "genetics": "Möglicherweise OG Kush x Northern Lights",
    "aromas": [
      "Erdig",
      "Süß",
      "Kaffee",
      "Schokolade"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "bubble-gum": {
    "description": "Eine preisgekrönte Hybride, berühmt für ihren ausgeprägten süßen Geruch und Geschmack, genau wie klassisches Kaugummi. Sie bietet ein ausgewogenes High, das euphorisch und erhebend ist, gefolgt von einer sanften Körperentspannung. Ideal für kreative Aufgaben und Stressabbau.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Indiana Bubblegum",
    "aromas": [
      "Süß",
      "Kaugummi",
      "Fruchtig",
      "Blumig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "cactus-breath": {
    "description": "Eine potente indica-dominante Hybride mit einem einzigartigen scharfen Aroma, das Diesel, Gewürze und Erde kombiniert. Das High ist stark entspannend und euphorisch, was oft zu einem schweren Körpergefühl und tiefer Ruhe führt. Am besten für erfahrene Konsumenten.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Cactus x Mendo Breath",
    "aromas": [
      "Scharf",
      "Diesel",
      "Würzig",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "cactus-cooler": {
    "description": "Eine sativa-dominante Hybride mit einem hellen, erfrischenden Geschmacksprofil aus Zitrusfrüchten und tropischen Früchten. Das High ist energetisch und erhebend, perfekt für Tagesaktivitäten, zur Steigerung der Kreativität und zur Verbesserung der Stimmung.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Blue Dream x OG Kush",
    "aromas": [
      "Zitrus",
      "Tropisch",
      "Ananas",
      "Süß"
    ],
    "dominantTerpenes": [
      "Terpinolen",
      "Myrcen"
    ]
  },
  "cake-bomb": {
    "description": "Eine indica-dominante Hybride, die dichte, frostige Blüten mit einem süßen, kuchenartigen Aroma produziert. Das High ist tief entspannend und beruhigend, was sie zu einer ausgezeichneten Wahl für den abendlichen Gebrauch zur Linderung von Stress und Schmerzen macht.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Do-Si-Dos x PCS1",
    "aromas": [
      "Süß",
      "Kuchen",
      "Erdig",
      "Vanille"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Caryophyllen",
      "Myrcen"
    ]
  },
  "cali-o": {
    "description": "Eine klassische 50/50-Hybride, auch bekannt als California Orange. Sie ist berühmt für ihr starkes, süßes Orangenaroma. Das High ist klar-köpfig, erhebend und fröhlich, was sie zu einer großartigen Sorte für soziale Anlässe und kreative Arbeit macht.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Kalifornische Landrasse",
    "aromas": [
      "Orange",
      "Zitrus",
      "Süß",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "candy-jack": {
    "description": "Eine sativa-dominante Hybride, die das Beste aus zwei legendären Sorten vereint. Sie hat ein süßes, zitrusartiges Aroma und bietet ein starkes, erhebendes zerebrales High, das energetisch und kreativ ist. Ideal zur Bekämpfung von Müdigkeit und Depressionen.",
    "typeDetails": "Sativa 80% / Indica 20%",
    "genetics": "Jack Herer x Skunk #1",
    "aromas": [
      "Süß",
      "Zitrus",
      "Erdig",
      "Skunk"
    ],
    "dominantTerpenes": [
      "Terpinolen",
      "Myrcen",
      "Pinen"
    ]
  },
  "candyland": {
    "description": "Eine sativa-dominante Hybride mit einem süßen Bonbongeschmack und erdigen Untertönen. Das High ist erhebend und anregend, perfekt für soziale Zusammenkünfte und kreative Aktivitäten. Sie kann auch eine wirksame Schmerzlinderung ohne starke Sedierung bieten.",
    "typeDetails": "Sativa 70% / Indica 30%",
    "genetics": "Granddaddy Purple x Bay Platinum Cookies",
    "aromas": [
      "Süß",
      "Bonbon",
      "Erdig",
      "Würzig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Humulen"
    ]
  },
  "cannatonic": {
    "description": "Eine berühmte CBD-reiche Hybridsorte, oft mit einem nahezu 1:1 THC-zu-CBD-Verhältnis. Sie bietet ein sanftes, entspannendes High, das kurzlebig und hauptsächlich körperlich ist, was sie hervorragend zur Behandlung von Schmerzen, Angst und Muskelkrämpfen ohne intensive Psychoaktivität macht.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "MK Ultra x G13 Haze",
    "aromas": [
      "Erdig",
      "Holzig",
      "Zitrus",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "cap-junky": {
    "description": "Eine hochpotente Hybride, bekannt für ihr intensives, scharfes Aroma von sauren Früchten und Benzin. Das High ist stark und langanhaltend und liefert eine Welle der Euphorie und Kreativität, die sich schließlich in einen Zustand tiefer Entspannung einpendelt. Für erfahrene Konsumenten.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Alien Cookies x Kush Mints #11",
    "aromas": [
      "Scharf",
      "Diesel",
      "Sauer",
      "Fruchtig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "captains-cake": {
    "description": "Eine sativa-dominante Hybride mit einem süßen, fruchtigen und leicht säuerlichen Aroma. Das High ist erhebend und energetisch und sorgt für einen Kreativitäts- und Konzentrationsschub, was sie zu einer großartigen Wahl für den Tagesgebrauch macht.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Girl Scout Cookies x White Fire Alien OG",
    "aromas": [
      "Süß",
      "Fruchtig",
      "Sauer",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Caryophyllen",
      "Myrcen"
    ]
  },
  "carbon-fiber": {
    "description": "Eine potente und seltene indica-dominante Hybride. Sie hat ein komplexes Aromaprofil, das Noten von Trauben, Zitrusfrüchten und Diesel kombiniert. Das High ist tief entspannend und sedierend und führt oft zu einem glückseligen 'Couch-Lock'.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Grape Pie x Biscotti x Cookies and Cream",
    "aromas": [
      "Traube",
      "Diesel",
      "Zitrus",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "casey-jones": {
    "description": "Eine sativa-dominante Hybride, benannt nach dem berühmten Lokführer. Sie ist bekannt für ihr schnell wirkendes, erhebendes und kreatives High. Das Aroma ist erdig und süß mit Noten von Zitrusfrüchten. Eine großartige Sorte für Produktivität und Tagesgenuss.",
    "typeDetails": "Sativa 80% / Indica 20%",
    "genetics": "Trainwreck x Sour Diesel x Thai",
    "aromas": [
      "Erdig",
      "Süß",
      "Zitrus",
      "Diesel"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Limonen"
    ]
  },
  "cat-piss": {
    "description": "Trotz ihres unglücklichen Namens ist dies eine klassische sativa-dominante Sorte mit einem scharfen, skunkigen und ammoniakartigen Aroma. Das High ist energetisch, euphorisch und sehr zerebral, was sie zu einem Favoriten unter Sativa-Liebhabern für ihre klar-köpfigen Effekte macht.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Super Silver Haze Phänotyp",
    "aromas": [
      "Scharf",
      "Ammoniak",
      "Skunk",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Terpinolen",
      "Myrcen"
    ]
  },
  "cataract-kush": {
    "description": "Eine potente indica-dominante Hybride, bekannt für ihre schwere, sedierende Wirkung. Das High ist ein 'Creeper', der sich langsam zu einer starken Ganzkörperentspannung aufbaut, die für Anfänger überwältigend sein kann. Sie hat ein scharfes, fruchtiges und skunkiges Aroma.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "LA Confidential x OG Kush",
    "aromas": [
      "Scharf",
      "Fruchtig",
      "Skunk",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "cbd-critical-cure": {
    "description": "Eine CBD-reiche indica-dominante Sorte, die für den therapeutischen Gebrauch gezüchtet wurde. Sie hat einen süßen, erdigen Geschmack und bietet eine sanfte, beruhigende Wirkung mit minimaler Psychoaktivität. Sie ist sehr wirksam bei der Behandlung von Schmerzen, Entzündungen und Angstzuständen.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Critical Kush x Shanti Babas CBD-angereicherte Sorte",
    "aromas": [
      "Erdig",
      "Süß",
      "Holzig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "cbd-therapy": {
    "description": "Eine bahnbrechende Sorte, die speziell für einen hohen CBD- und niedrigen THC-Gehalt gezüchtet wurde. Sie ist ideal für Patienten, die die medizinischen Vorteile von Cannabis ohne das High benötigen. Die Wirkung ist klar-köpfig und beruhigend. Das Aroma ist eine Mischung aus fruchtigen und erdigen Noten.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Unbekannt",
    "aromas": [
      "Fruchtig",
      "Erdig",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "cereal-a-la-mode": {
    "description": "Eine potente und geschmackvolle Hybride aus der Cookies-Familie. Sie hat ein süßes, cremiges und fruchtiges Aroma, das an eine Schüssel Müsli erinnert. Das High ist gut ausbalanciert und bietet ein euphorisches und kreatives Kopf-High neben einem entspannenden Körper-Buzz.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Cereal Milk x Georgia Pie",
    "aromas": [
      "Süß",
      "Cremig",
      "Fruchtig",
      "Vanille"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen"
    ]
  },
  "cereal-milk": {
    "description": "Eine ausgewogene Hybridsorte von Cookies, bekannt für ihren einzigartigen cremigen und fruchtigen Geschmack, wie die Milch am Boden einer Schüssel mit zuckerhaltigem Müsli. Das High ist glückselig und kreativ, ideal für einen entspannten und dennoch produktiven Tag.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "(Y Life x Snowman) x GSC",
    "aromas": [
      "Süß",
      "Cremig",
      "Beere",
      "Vanille"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen"
    ]
  },
  "charlottes-web": {
    "description": "Eine weltberühmte Sorte mit hohem CBD- und niedrigem THC-Gehalt. Sie wurde bekannt durch ihre Wirksamkeit bei der Behandlung schwerer Epilepsie. Sie erzeugt kein psychoaktives High, was sie zu einer rein medizinischen Sorte für eine Vielzahl von Erkrankungen macht.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Hanf x Unbekannte Sorte",
    "aromas": [
      "Erdig",
      "Kiefer",
      "Blumig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "cheese": {
    "description": "Eine legendäre indica-dominante Hybride, die ihren Ursprung in Großbritannien hat. Sie ist berühmt für ihr scharfes, käsiges und skunkiges Aroma. Das High ist stark und vermittelt ein fröhliches, entspannendes Gefühl, das auch sehr euphorisch und erhebend sein kann.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Skunk #1 Phänotyp",
    "aromas": [
      "Käse",
      "Scharf",
      "Skunk",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Myrcen",
      "Limonen"
    ]
  },
  "cheesecake": {
    "description": "Eine indica-dominante Hybride mit einem süßen, käsigen und cremigen Geschmacksprofil. Das High ist entspannend und euphorisch, perfekt zum Entspannen nach einem langen Tag und zur Appetitanregung. Sie ist wirksam bei Stress, Schmerzen und Appetitlosigkeit.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Cheese x eine unbekannte Indica",
    "aromas": [
      "Käse",
      "Süß",
      "Cremig",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "cheetah-piss": {
    "description": "Eine potente Hybride mit einem sehr scharfen, ammoniakähnlichen Aroma, ähnlich wie Cat Piss, aber mit zusätzlichen Zitrus- und Dieselnoten. Das High ist schnell wirkend und kichernd und sorgt für eine Welle der Euphorie und Kreativität, die sich hervorragend für soziale Anlässe eignet.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Lemonnade x Gelato 42 x London Poundcake 97",
    "aromas": [
      "Scharf",
      "Ammoniak",
      "Zitrus",
      "Diesel"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen"
    ]
  },
  "chem-sis": {
    "description": "Ein sativa-dominanter Phänotyp des legendären Chemdawg. Er ist bekannt für sein scharfes Diesel- und chemisches Aroma. Das High ist stark zerebral, energetisch und kreativ, was ihn zu einem Favoriten unter erfahrenen Sativa-Liebhabern macht.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Chemdawg Phänotyp",
    "aromas": [
      "Diesel",
      "Chemisch",
      "Scharf",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "chemdawg": {
    "description": "Eine legendäre Sorte unbekannter Herkunft, Chemdawg ist die Mutter vieler berühmter Sorten wie OG Kush und Sour Diesel. Sie ist bekannt für ihr ausgeprägtes, scharfes Dieselaroma und ein sehr potentes, zerebrales High, das kreativ und erhebend ist.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Unbekannt",
    "aromas": [
      "Diesel",
      "Chemisch",
      "Scharf",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Myrcen",
      "Limonen"
    ]
  },
  "chemdog-millionaire": {
    "description": "Eine potente indica-dominante Hybride mit einem komplexen Aroma von Erde, Kraftstoff und Zitrusfrüchten. Sie liefert ein starkes, langanhaltendes High, das sowohl zerebral euphorisch als auch tief körperlich entspannend ist. Ideal zur Schmerz- und Stresslinderung.",
    "typeDetails": "Indica-dominante Hybride",
    "genetics": "Chemdawg x Gupta Kush",
    "aromas": [
      "Erdig",
      "Diesel",
      "Zitrus",
      "Scharf"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "cherry-ak-47": {
    "description": "Ein Phänotyp der klassischen AK-47, ausgewählt wegen seines ausgeprägten Kirscharomas. Er behält das ausgewogene, erhebende High des Originals bei, fügt aber eine süße, fruchtige Note hinzu. Die Wirkung ist kreativ, fröhlich und entspannend.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "AK-47 Phänotyp",
    "aromas": [
      "Kirsche",
      "Süß",
      "Erdig",
      "Skunk"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "cherry-pie": {
    "description": "Eine indica-dominante Hybride mit einem köstlichen Aroma von süß-saurem Kirschkuchen. Das High ist gut ausbalanciert, beginnt mit einem erhebenden zerebralen Buzz, der sanft in einen Zustand glücklicher Entspannung übergeht. Ideal zum Stressabbau.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Granddaddy Purple x Durban Poison",
    "aromas": [
      "Kirsche",
      "Süß",
      "Erdig",
      "Beere"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "chiquita-banana": {
    "description": "Eine potente Hybride, bekannt für ihren unglaublich hohen THC-Gehalt und einen starken Bananengeschmack. Das High ist stark und euphorisch, beginnt mit einem zerebralen Rausch, der einer tiefen körperlichen Entspannung weicht. Am besten für erfahrene Konsumenten.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "OG Kush x Banana",
    "aromas": [
      "Banane",
      "Süß",
      "Tropisch",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "cinderella-99": {
    "description": "Auch bekannt als Cindy 99. Eine sativa-dominante Hybride, berühmt für ihre schnelle Blütezeit und ein verträumtes, euphorisches und erhebendes High. Sie hat einen süßen, fruchtigen Geschmack mit tropischen Noten. Eine ausgezeichnete Tagessorte zur Steigerung von Kreativität und Stimmung.",
    "typeDetails": "Sativa 85% / Indica 15%",
    "genetics": "Jack Herer x Shiva Skunk",
    "aromas": [
      "Süß",
      "Fruchtig",
      "Tropisch",
      "Zitrus"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Myrcen",
      "Caryophyllen"
    ]
  },
  "citradelic-sunset": {
    "description": "Eine sativa-dominante Hybride mit einem lebhaften Zitrus- und sauren Aroma. Sie liefert ein starkes, erhebendes und energetisches High, das perfekt für den Tagesgebrauch ist. Sie ist dafür bekannt, die Kreativität zu fördern und ein langanhaltendes euphorisches Erlebnis zu bieten.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Ghost Train Haze x Mandarin Sunset",
    "aromas": [
      "Zitrus",
      "Sauer",
      "Süß",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Terpinolen",
      "Myrcen"
    ]
  },
  "colt-45": {
    "description": "Eine potente sativa-dominante Hybride mit einem komplexen Aroma, das gasige, erdige und blumige Noten kombiniert. Das High ist stark und zerebral und sorgt für einen Energie- und Euphorieschub, der sich hervorragend für kreative Projekte und soziale Anlässe eignet.",
    "typeDetails": "Sativa-dominante Hybride",
    "genetics": "Gelato 45 x Slurricane",
    "aromas": [
      "Gasig",
      "Erdig",
      "Blumig",
      "Scharf"
    ],
    "dominantTerpenes": [
      "Limonen",
      "Caryophyllen"
    ]
  },
  "congo": {
    "description": "Eine reine Sativa-Landrassensorte, die für ihr klares, energetisches und langanhaltendes High bekannt ist. Sie bietet einen anregenden und kreativen Rausch ohne die Angst, die manchmal mit starken Sativas verbunden ist. Das Aroma ist eine süße und fruchtige Mischung.",
    "typeDetails": "Sativa 100%",
    "genetics": "Kongo Landrasse",
    "aromas": [
      "Süß",
      "Fruchtig",
      "Würzig",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Terpinolen"
    ]
  },
  "cookies-and-cream": {
    "description": "Eine gut ausbalancierte Hybride, die die Hybrid-Kategorie des Denver Cannabis Cup 2014 gewonnen hat. Sie hat einen süßen Vanille- und Nussgeschmack. Das High ist fröhlich und entspannend und bietet langanhaltende Linderung bei Stress und Schmerzen.",
    "typeDetails": "Hybrid 50% / 50%",
    "genetics": "Starfighter x ein unbekannter GSC Phänotyp",
    "aromas": [
      "Süß",
      "Vanille",
      "Nussig",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "1024": {
    "description": "Eine sehr potente und ertragreiche Sativa von Medical Seeds mit einem komplexen süß-sauren, fruchtigen Aroma. Die Wirkung ist stark zerebral, fast psychedelisch und sehr langanhaltend. Fördert Kreativität und Euphorie.",
    "typeDetails": "Sativa 70% / Indica 30%",
    "genetics": "Geheime Genetik",
    "aromas": [
      "Süß",
      "Fruchtig",
      "Würzig",
      "Weihrauch"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "24k-gold": {
    "description": "Auch bekannt als Kosher Tangie. Eine indica-dominante Hybride, die den süßen Zitrusgeschmack von Tangie mit der entspannenden Kraft von Kosher Kush kombiniert. Wirkt fröhlich und entspannend, ideal bei Stress und Schmerzen. Die Pflanzen entwickeln oft schöne goldene Farbtöne.",
    "typeDetails": "Indica 60% / Sativa 40%",
    "genetics": "Kosher Kush x Tangie",
    "aromas": [
      "Zitrus",
      "Orange",
      "Skunk",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Limonen",
      "Caryophyllen"
    ]
  },
  "303-og": {
    "description": "Als Favorit aus Colorado liefert 303 OG ein klassisches OG-Erlebnis mit einem potenten, sauren Diesel-Aroma. Die Wirkung ist ausgewogen, beginnt mit einem starken zerebralen Rausch, der in eine sanfte, entspannende Körperwirkung übergeht. Ideal zum Entspannen am Nachmittag oder Abend ohne vollständige Sedierung.",
    "typeDetails": "Indica 70% / Sativa 30%",
    "genetics": "Pre-98 Bubba Kush x Chemdawg",
    "aromas": [
      "Diesel",
      "Sauer",
      "Erdig",
      "Scharf"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Limonen"
    ]
  },
  "501st-og": {
    "description": "Eine potente Indica-Hybride mit einem erdigen, kiefernartigen Aroma und Noten von Traube. Die Wirkung ist stark körperlich und zerebral entspannend, fast sedierend. Ideal zur Linderung von Schmerzen, Stress und Schlaflosigkeit.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Skywalker OG x Rare Dankness #1",
    "aromas": [
      "Traube",
      "Erdig",
      "Kiefer",
      "Süß"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  },
  "707-headband": {
    "description": "Eine populäre kalifornische Hybride mit einem sauren, zitronigen Aroma und erdigen Untertönen. Die Wirkung ist schnell einsetzend, zerebral und euphorisch, oft begleitet von einem merklichen Druck um den Kopf, daher der Name 'Headband'. Sehr wirksam bei Schmerzen und Stress.",
    "typeDetails": "Sativa 70% / Indica 30%",
    "genetics": "Sour Diesel x OG Kush x Master Kush",
    "aromas": [
      "Zitrone",
      "Diesel",
      "Erdig",
      "Sauer",
      "Kiefer"
    ],
    "dominantTerpenes": [
      "Caryophyllen",
      "Limonen",
      "Myrcen"
    ]
  },
  "8-ball-kush": {
    "description": "Eine reine Indica aus dem Hindukusch-Gebirge, gezüchtet von Barney's Farm. Sie bietet eine tief entspannende, fast narkotische Wirkung. Das Aroma ist erdig und würzig. Ideal für den Abendgebrauch und zur Schmerzlinderung.",
    "typeDetails": "Indica 100%",
    "genetics": "Afghanische Landrasse",
    "aromas": [
      "Erdig",
      "Würzig",
      "Kräuterartig",
      "Holzig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Caryophyllen",
      "Pinen"
    ]
  },
  "9-pound-hammer": {
    "description": "Eine schwere Indica-Hybride mit einem fruchtigen, limettenartigen Geschmack. Die Wirkung ist sehr potent und langanhaltend, führt zu tiefer körperlicher Entspannung und oft zu Schläfrigkeit. Gut geeignet bei Schmerzen und Schlaflosigkeit.",
    "typeDetails": "Indica 80% / Sativa 20%",
    "genetics": "Gooberry x Hells OG x Jack the Ripper",
    "aromas": [
      "Traube",
      "Limette",
      "Süß",
      "Erdig"
    ],
    "dominantTerpenes": [
      "Myrcen",
      "Pinen",
      "Caryophyllen"
    ]
  }
}
