// ---------------------------------------------------------------------------
// dailyStrainsService.ts -- Daily Strain Discovery Feed
//
// Manages the in-app strain news feed. Sources:
//   1. Pending strains from the daily GH Actions bot (static JSON import)
//   2. AI-powered strain lookup (replaces dead SeedFinder API)
//   3. RSS-like discovery feed rendering
// ---------------------------------------------------------------------------

import { isLocalOnlyMode } from '@/services/localOnlyModeService'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface DiscoveredStrain {
    id: string
    name: string
    breeder: string
    type: 'Indica' | 'Sativa' | 'Hybrid'
    floweringType: 'Photoperiod' | 'Autoflower'
    thc: number
    cbd: number
    description: string
    genetics: string
    source: string
    sourceUrl: string
    discoveredAt: string
    discoverySource?: string
    updateType?: string
}

export interface DailyStrainsFeed {
    version: number
    generatedAt: string
    stats: {
        newStrains: number
        updatedStrains: number
        errors: number
        existingCatalogSize: number
    }
    discoveries: DiscoveredStrain[]
    updates: DiscoveredStrain[]
}

export type FeedStatus = 'idle' | 'loading' | 'loaded' | 'error'

// ---------------------------------------------------------------------------
// In-memory cache
// ---------------------------------------------------------------------------

const CACHE_TTL_MS = 30 * 60 * 1000 // 30 minutes
const STORAGE_KEY = 'cg.daily-strains.feed'
const DISMISSED_KEY = 'cg.daily-strains.dismissed'

let cachedFeed: DailyStrainsFeed | null = null
let cacheTimestamp = 0

// ---------------------------------------------------------------------------
// Local storage persistence
// ---------------------------------------------------------------------------

function saveFeedToStorage(feed: DailyStrainsFeed): void {
    try {
        localStorage.setItem(STORAGE_KEY, JSON.stringify(feed))
    } catch {
        // Storage full -- ignore
    }
}

function loadFeedFromStorage(): DailyStrainsFeed | null {
    try {
        const raw = localStorage.getItem(STORAGE_KEY)
        if (!raw) return null
        return JSON.parse(raw) as DailyStrainsFeed
    } catch {
        return null
    }
}

function getDismissedIds(): Set<string> {
    try {
        const raw = localStorage.getItem(DISMISSED_KEY)
        if (!raw) return new Set()
        const arr = JSON.parse(raw) as string[]
        return new Set(arr)
    } catch {
        return new Set()
    }
}

function dismissStrainId(id: string): void {
    const dismissed = getDismissedIds()
    dismissed.add(id)
    // Keep only last 500 dismissals
    const arr = [...dismissed].slice(-500)
    try {
        localStorage.setItem(DISMISSED_KEY, JSON.stringify(arr))
    } catch {
        /* ignore */
    }
}

// ---------------------------------------------------------------------------
// Pending strains loader (from GH Actions bot output)
// ---------------------------------------------------------------------------

async function loadPendingStrains(): Promise<DiscoveredStrain[]> {
    try {
        // Dynamic import of the pending strains JSON generated by the daily bot
        const module = await import('@/data/strains/pending/pending-strains.json')
        const data = module.default as unknown
        if (Array.isArray(data)) {
            return data as DiscoveredStrain[]
        }
        return []
    } catch {
        // File may not exist yet if the bot hasn't run
        return []
    }
}

// ---------------------------------------------------------------------------
// AI-powered strain lookup (replaces dead SeedFinder API)
// ---------------------------------------------------------------------------

/**
 * Search for cannabis strains using AI.
 * Uses the AI facade to get structured strain information.
 * Falls back to local catalog search when AI is unavailable.
 */
export async function searchStrainsWithAI(query: string): Promise<DiscoveredStrain[]> {
    if (!query || query.length < 2) return []

    // Always search local catalog first
    const localResults = await searchLocalCatalog(query)

    // In local-only mode, return local results only
    if (isLocalOnlyMode()) return localResults

    // Try AI-powered lookup for additional results
    try {
        const { aiService, getAiMode } = await import('@/services/aiFacade')
        const mode = getAiMode()

        // Skip AI call in eco mode or if no provider configured
        if (mode === 'eco') return localResults

        const lang = (document.documentElement.lang as 'en' | 'de') || 'en'

        // Use a minimal plant stub for the mentor API
        const plantStub = { id: 'strain-lookup', name: query } as Parameters<
            typeof aiService.getMentorResponse
        >[0]
        const response = await aiService.getMentorResponse(
            plantStub,
            buildStrainLookupPrompt(query, lang),
            lang,
        )

        if (response?.content) {
            const aiStrains = parseAIStrainResponse(response.content)
            // Merge: local results first, then AI results (deduplicated)
            const seenIds = new Set(localResults.map((s) => s.id))
            const merged = [...localResults]
            for (const strain of aiStrains) {
                if (!seenIds.has(strain.id)) {
                    seenIds.add(strain.id)
                    merged.push(strain)
                }
            }
            return merged.slice(0, 30)
        }
    } catch {
        // AI unavailable -- return local results
    }

    return localResults
}

function buildStrainLookupPrompt(query: string, lang: string): string {
    const isDE = lang === 'de'
    return isDE
        ? `Ich suche Informationen ueber die Cannabis-Sorte "${query}". ` +
              'Bitte gib mir fuer jede passende Sorte (maximal 5) folgende Daten im JSON-Array-Format: ' +
              '[{"name": "...", "breeder": "...", "type": "Indica|Sativa|Hybrid", ' +
              '"floweringType": "Photoperiod|Autoflower", "thc": <number>, "cbd": <number>, ' +
              '"description": "...", "genetics": "Parent1 x Parent2"}]. ' +
              'Nur echte, verifizierte Sorten. Keine erfundenen Daten.'
        : `I am looking for information about the cannabis strain "${query}". ` +
              'Please provide for each matching strain (max 5) the following data in JSON array format: ' +
              '[{"name": "...", "breeder": "...", "type": "Indica|Sativa|Hybrid", ' +
              '"floweringType": "Photoperiod|Autoflower", "thc": <number>, "cbd": <number>, ' +
              '"description": "...", "genetics": "Parent1 x Parent2"}]. ' +
              'Only real, verified strains. No fabricated data.'
}

function parseAIStrainResponse(text: string): DiscoveredStrain[] {
    const results: DiscoveredStrain[] = []

    // Try to extract JSON array from AI response
    const jsonMatch = text.match(/\[[\s\S]*?\]/)?.[0]
    if (!jsonMatch) return results

    try {
        const parsed = JSON.parse(jsonMatch) as Array<Record<string, unknown>>
        if (!Array.isArray(parsed)) return results

        for (const item of parsed) {
            if (!item || typeof item !== 'object') continue
            const name = String(item.name ?? '').trim()
            if (!name) continue

            const id = `ai-${name
                .toLowerCase()
                .replace(/[^a-z0-9]+/g, '-')
                .replace(/-+$/, '')}`
            results.push({
                id,
                name,
                breeder: String(item.breeder ?? 'Unknown'),
                type: normalizeType(item.type),
                floweringType:
                    String(item.floweringType ?? '') === 'Autoflower'
                        ? 'Autoflower'
                        : 'Photoperiod',
                thc: parseFloat(String(item.thc ?? 0)) || 0,
                cbd: parseFloat(String(item.cbd ?? 0)) || 0,
                description: String(item.description ?? '').slice(0, 300),
                genetics: String(item.genetics ?? ''),
                source: 'ai-lookup',
                sourceUrl: '',
                discoveredAt: new Date().toISOString(),
                discoverySource: 'ai-search',
            })
        }
    } catch {
        // JSON parse failed -- ignore
    }

    return results
}

/**
 * Search the local strain catalog for matches.
 */
async function searchLocalCatalog(query: string): Promise<DiscoveredStrain[]> {
    try {
        const { allStrainsData } = await import('@/data/strains/index')
        const q = query.toLowerCase()
        const matches = allStrainsData
            .filter(
                (s) =>
                    s.name.toLowerCase().includes(q) ||
                    (s.genetics?.toLowerCase().includes(q) ?? false) ||
                    (s.description?.toLowerCase().includes(q) ?? false),
            )
            .slice(0, 20)
            .map((s) => ({
                id: s.id,
                name: s.name,
                breeder: 'Catalog',
                type: (s.type ?? 'Hybrid') as 'Indica' | 'Sativa' | 'Hybrid',
                floweringType: (s.floweringType ?? 'Photoperiod') as 'Photoperiod' | 'Autoflower',
                thc: s.thc ?? 0,
                cbd: s.cbd ?? 0,
                description: s.description ?? '',
                genetics: s.genetics ?? '',
                source: 'local-catalog',
                sourceUrl: '',
                discoveredAt: new Date().toISOString(),
                discoverySource: 'catalog-search',
            }))
        return matches
    } catch {
        return []
    }
}

function normalizeType(genotype: unknown): 'Indica' | 'Sativa' | 'Hybrid' {
    const s = String(genotype ?? '').toLowerCase()
    if (s.includes('indica')) return 'Indica'
    if (s.includes('sativa')) return 'Sativa'
    return 'Hybrid'
}

// ---------------------------------------------------------------------------
// Recommendation scoring -- rank discoveries by similarity to user library
// ---------------------------------------------------------------------------

export interface ScoredStrain extends DiscoveredStrain {
    /** 0-100 relevance score based on user preferences. */
    relevanceScore: number
}

export interface UserStrainProfile {
    favoriteTypes: Record<string, number>
    avgThc: number
    avgCbd: number
    strainCount: number
}

/**
 * Build a preference profile from the user's favorite/library strains.
 */
export function buildUserProfile(
    strains: Array<{ type?: string; thc?: number; cbd?: number }>,
): UserStrainProfile {
    const favoriteTypes: Record<string, number> = {}
    let thcSum = 0
    let cbdSum = 0
    let count = 0

    for (const s of strains) {
        if (s.type) {
            favoriteTypes[s.type] = (favoriteTypes[s.type] ?? 0) + 1
        }
        thcSum += s.thc ?? 0
        cbdSum += s.cbd ?? 0
        count++
    }

    return {
        favoriteTypes,
        avgThc: count > 0 ? thcSum / count : 15,
        avgCbd: count > 0 ? cbdSum / count : 0.5,
        strainCount: count,
    }
}

/**
 * Score a discovered strain against the user's preference profile.
 * Returns 0-100 relevance score.
 */
function scoreStrain(strain: DiscoveredStrain, profile: UserStrainProfile): number {
    if (profile.strainCount === 0) return 50 // No data -- neutral score

    let score = 50

    // Type preference match (max +25)
    const totalTyped = Object.values(profile.favoriteTypes).reduce((a, b) => a + b, 0)
    if (totalTyped > 0) {
        const typeRatio = (profile.favoriteTypes[strain.type] ?? 0) / totalTyped
        score += typeRatio * 25
    }

    // THC similarity (max +15) -- closer to user's avg = higher score
    if (strain.thc > 0 && profile.avgThc > 0) {
        const thcDiff = Math.abs(strain.thc - profile.avgThc)
        score += Math.max(0, 15 - thcDiff)
    }

    // CBD match bonus (max +10)
    if (strain.cbd > 0 && profile.avgCbd > 0) {
        const cbdDiff = Math.abs(strain.cbd - profile.avgCbd)
        score += Math.max(0, 10 - cbdDiff * 5)
    }

    return Math.min(100, Math.max(0, Math.round(score)))
}

/**
 * Rank discovered strains by relevance to user preferences.
 * Strains are sorted by score descending.
 */
export function rankStrainsByRelevance(
    strains: DiscoveredStrain[],
    profile: UserStrainProfile,
): ScoredStrain[] {
    return strains
        .map((s) => ({ ...s, relevanceScore: scoreStrain(s, profile) }))
        .sort((a, b) => b.relevanceScore - a.relevanceScore)
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export const dailyStrainsService = {
    /** Load the daily feed (pending bot discoveries + cached searches). */
    async loadFeed(): Promise<DailyStrainsFeed> {
        // Return cached if fresh
        if (cachedFeed && Date.now() - cacheTimestamp < CACHE_TTL_MS) {
            return cachedFeed
        }

        // Try localStorage first
        const stored = loadFeedFromStorage()
        const pending = await loadPendingStrains()

        const feed: DailyStrainsFeed = stored ?? {
            version: 1,
            generatedAt: new Date().toISOString(),
            stats: {
                newStrains: 0,
                updatedStrains: 0,
                errors: 0,
                existingCatalogSize: 0,
            },
            discoveries: [],
            updates: [],
        }

        // Merge pending strains into discoveries (deduplicate)
        if (pending.length > 0) {
            const existingIds = new Set(feed.discoveries.map((d) => d.id))
            for (const strain of pending) {
                if (!existingIds.has(strain.id)) {
                    feed.discoveries.push(strain)
                    existingIds.add(strain.id)
                }
            }
            feed.stats.newStrains = feed.discoveries.length
        }

        cachedFeed = feed
        cacheTimestamp = Date.now()
        saveFeedToStorage(feed)

        return feed
    },

    /** Get only non-dismissed discoveries. */
    async getNewDiscoveries(): Promise<DiscoveredStrain[]> {
        const feed = await this.loadFeed()
        const dismissed = getDismissedIds()
        return feed.discoveries.filter((d) => !dismissed.has(d.id))
    },

    /** Get count of new (non-dismissed) discoveries for badge display. */
    async getNewCount(): Promise<number> {
        const discoveries = await this.getNewDiscoveries()
        return discoveries.length
    },

    /** Dismiss a strain (user reviewed it). */
    dismiss(strainId: string): void {
        dismissStrainId(strainId)
    },

    /** AI-powered strain search (replaces SeedFinder). */
    search: searchStrainsWithAI,

    /** Invalidate cache to force re-fetch. */
    invalidate(): void {
        cachedFeed = null
        cacheTimestamp = 0
    },
}
