// ---------------------------------------------------------------------------
// growBibleExportService -- "Grow Bible" Export for CannaGuide 2025
//
// Generates a comprehensive, personal grow report as downloadable Markdown
// containing plant data, journal entries, strain info, environment history,
// analytics, and knowledge graph references.
//
// The export is a self-contained document that serves as a complete
// grow session record -- useful for sharing, archiving, or printing.
// ---------------------------------------------------------------------------

import type { Plant, AppSettings } from '@/types'
import { getT } from '@/i18n'
import { analyticsService } from './analyticsService'
import { knowledgeGraph, type CrossModuleLink } from './knowledgeGraphService'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface GrowBibleOptions {
    /** Include journal entries */
    readonly includeJournal: boolean
    /** Include environment data */
    readonly includeEnvironment: boolean
    /** Include analytics */
    readonly includeAnalytics: boolean
    /** Include related knowledge links */
    readonly includeKnowledge: boolean
    /** Maximum journal entries per plant */
    readonly maxJournalEntries: number
    /** Export language */
    readonly language: string
}

const DEFAULT_OPTIONS: GrowBibleOptions = {
    includeJournal: true,
    includeEnvironment: true,
    includeAnalytics: true,
    includeKnowledge: true,
    maxJournalEntries: 50,
    language: 'en',
}

// ---------------------------------------------------------------------------
// Export Engine
// ---------------------------------------------------------------------------

class GrowBibleExporter {
    /**
     * Generate the full Grow Bible as a Markdown string.
     */
    generate(plants: Plant[], _settings: AppSettings, options?: Partial<GrowBibleOptions>): string {
        const opts: GrowBibleOptions = { ...DEFAULT_OPTIONS, ...options }
        const t = getT()
        const lines: string[] = []

        // Header
        lines.push(`# ${t('growBible.title', 'CannaGuide Grow Bible')}`)
        lines.push('')
        lines.push(
            `**${t('growBible.generated', 'Generated')}:** ${new Date().toISOString().split('T')[0]}`,
        )
        lines.push(`**${t('growBible.plants', 'Plants')}:** ${plants.length}`)
        lines.push(`**${t('growBible.appVersion', 'App Version')}:** CannaGuide 2025 v1.3.0`)
        lines.push('')
        lines.push('---')
        lines.push('')

        // Table of Contents
        lines.push(`## ${t('growBible.toc', 'Table of Contents')}`)
        lines.push('')
        let tocIdx = 1
        for (const plant of plants) {
            lines.push(`${tocIdx}. [${plant.name}](#${slugify(plant.name)})`)
            tocIdx++
        }
        if (opts.includeAnalytics) {
            lines.push(
                `${tocIdx}. [${t('growBible.analyticsSummary', 'Analytics Summary')}](#analytics-summary)`,
            )
            tocIdx++
        }
        if (opts.includeKnowledge) {
            lines.push(
                `${tocIdx}. [${t('growBible.relatedKnowledge', 'Related Knowledge')}](#related-knowledge)`,
            )
        }
        lines.push('')
        lines.push('---')
        lines.push('')

        // Plant Sections
        for (const plant of plants) {
            lines.push(...this.generatePlantSection(plant, opts))
            lines.push('')
            lines.push('---')
            lines.push('')
        }

        // Analytics Section
        if (opts.includeAnalytics && plants.length > 0) {
            lines.push(...this.generateAnalyticsSection(plants))
            lines.push('')
            lines.push('---')
            lines.push('')
        }

        // Knowledge Section
        if (opts.includeKnowledge) {
            lines.push(...this.generateKnowledgeSection(plants))
            lines.push('')
        }

        // Footer
        lines.push('---')
        lines.push('')
        lines.push(
            `*${t('growBible.footer', 'Generated by CannaGuide 2025')} -- https://qnbs.github.io/CannaGuide-2025/*`,
        )

        return lines.join('\n')
    }

    /**
     * Download the Grow Bible as a .md file.
     */
    download(plants: Plant[], settings: AppSettings, options?: Partial<GrowBibleOptions>): void {
        const markdown = this.generate(plants, settings, options)
        const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' })
        const url = URL.createObjectURL(blob)
        const date = new Date().toISOString().split('T')[0]
        const filename = `CannaGuide-GrowBible-${date}.md`

        const a = document.createElement('a')
        a.href = url
        a.download = filename
        a.style.display = 'none'
        document.body.appendChild(a)
        a.click()

        // Cleanup
        setTimeout(() => {
            document.body.removeChild(a)
            URL.revokeObjectURL(url)
        }, 100)
    }

    // -- Section generators -------------------------------------------------

    private generatePlantSection(plant: Plant, opts: GrowBibleOptions): string[] {
        const t = getT()
        const lines: string[] = []

        lines.push(`## ${plant.name}`)
        lines.push('')

        // Basic info table
        lines.push(`| ${t('growBible.property', 'Property')} | ${t('growBible.value', 'Value')} |`)
        lines.push('|----------|-------|')
        lines.push(
            `| **${t('growBible.strain', 'Strain')}** | ${plant.strain?.name ?? t('common.unknown', 'Unknown')} |`,
        )
        lines.push(`| **${t('growBible.stage', 'Stage')}** | ${plant.stage} |`)
        lines.push(
            `| **${t('growBible.age', 'Age')}** | ${plant.age ?? 0} ${t('growBible.days', 'days')} |`,
        )
        lines.push(`| **${t('growBible.health', 'Health')}** | ${plant.health}/100 |`)
        if (plant.environment.vpd !== undefined) {
            lines.push(`| **VPD** | ${plant.environment.vpd.toFixed(2)} kPa |`)
        }
        if (plant.environment.internalTemperature !== undefined) {
            lines.push(
                `| **${t('growBible.temperature', 'Temperature')}** | ${plant.environment.internalTemperature.toFixed(1)} C |`,
            )
        }
        if (plant.environment.internalHumidity !== undefined) {
            lines.push(
                `| **${t('growBible.humidity', 'Humidity')}** | ${plant.environment.internalHumidity.toFixed(1)}% |`,
            )
        }
        lines.push('')

        // Environment details
        if (opts.includeEnvironment) {
            lines.push(`### ${t('growBible.environment', 'Environment')}`)
            lines.push('')
            if (plant.medium) {
                lines.push(`- **pH:** ${plant.medium.ph?.toFixed(1) ?? 'N/A'}`)
                lines.push(`- **EC:** ${plant.medium.ec?.toFixed(2) ?? 'N/A'} mS/cm`)
                lines.push(
                    `- **${t('growBible.moisture', 'Moisture')}:** ${plant.medium.moisture?.toFixed(0) ?? 'N/A'}%`,
                )
            }
            lines.push('')
        }

        // Active problems
        if (plant.problems && plant.problems.length > 0) {
            lines.push(`### ${t('growBible.activeProblems', 'Active Problems')}`)
            lines.push('')
            for (const prob of plant.problems) {
                lines.push(
                    `- **${prob.type}** (${t('growBible.severity', 'severity')}: ${prob.severity}/10)`,
                )
            }
            lines.push('')
        }

        // Journal
        if (opts.includeJournal && plant.journal && plant.journal.length > 0) {
            lines.push(`### ${t('growBible.journal', 'Journal')}`)
            lines.push('')
            const entries = plant.journal.slice(-opts.maxJournalEntries)
            for (const entry of entries) {
                const date = new Date(entry.createdAt).toISOString().split('T')[0]
                lines.push(
                    `- **${date}** [${entry.type}]: ${entry.notes ?? t('growBible.noNotes', 'No notes')}`,
                )
            }
            lines.push('')
        }

        // Harvest data
        if (plant.harvestData) {
            lines.push(`### ${t('growBible.harvestData', 'Harvest Data')}`)
            lines.push('')
            const hd = plant.harvestData
            if (hd.wetWeight !== undefined)
                lines.push(`- **${t('growBible.wetWeight', 'Wet Weight')}:** ${hd.wetWeight}g`)
            if (hd.dryWeight !== undefined)
                lines.push(`- **${t('growBible.dryWeight', 'Dry Weight')}:** ${hd.dryWeight}g`)
            if (hd.finalQuality !== undefined)
                lines.push(`- **${t('growBible.quality', 'Quality')}:** ${hd.finalQuality}/100`)
            lines.push('')
        }

        return lines
    }

    private generateAnalyticsSection(plants: Plant[]): string[] {
        const t = getT()
        const lines: string[] = []
        const analytics = analyticsService.compute(plants)

        lines.push(`## ${t('growBible.analyticsSummary', 'Analytics Summary')}`)
        lines.push('')
        lines.push(
            `- **${t('analytics.gardenScore', 'Garden Score')}:** ${analytics.gardenScore}/100`,
        )
        lines.push(
            `- **${t('analytics.avgHealth', 'Average Health')}:** ${analytics.avgHealth}/100`,
        )
        lines.push(
            `- **${t('analytics.envStability', 'Environment Stability')}:** ${analytics.environmentStability}/100`,
        )
        lines.push('')

        // Stage distribution
        if (Object.keys(analytics.stageDistribution).length > 0) {
            lines.push(`### ${t('analytics.stageDistribution', 'Stage Distribution')}`)
            lines.push('')
            lines.push(`| ${t('growBible.stage', 'Stage')} | ${t('growBible.count', 'Count')} |`)
            lines.push('|-------|-------|')
            for (const [stage, count] of Object.entries(analytics.stageDistribution)) {
                lines.push(`| ${stage} | ${count} |`)
            }
            lines.push('')
        }

        // Risk factors
        if (analytics.riskFactors.length > 0) {
            lines.push(`### ${t('analytics.riskFactors', 'Risk Factors')}`)
            lines.push('')
            for (const risk of analytics.riskFactors) {
                const icon =
                    risk.severity === 'high' ? '[!]' : risk.severity === 'medium' ? '[~]' : '[-]'
                lines.push(
                    `- ${icon} **${t(`analytics.riskType.${risk.type}`, risk.type)}**: ${t(risk.descriptionKey, risk.descriptionParams ?? {})}`,
                )
            }
            lines.push('')
        }

        // Strain performance
        if (analytics.strainPerformance.length > 0) {
            lines.push(`### ${t('analytics.strainPerformance', 'Strain Performance')}`)
            lines.push('')
            lines.push(
                `| ${t('analytics.strain', 'Strain')} | ${t('analytics.avgHealth', 'Avg Health')} | ${t('analytics.plants', 'Plants')} | ${t('analytics.avgAge', 'Avg Age')} |`,
            )
            lines.push('|--------|-----------|--------|---------|')
            for (const sp of analytics.strainPerformance) {
                lines.push(
                    `| ${sp.strainName} | ${sp.avgHealth} | ${sp.plantCount} | ${sp.avgAge}d |`,
                )
            }
            lines.push('')
        }

        return lines
    }

    private generateKnowledgeSection(plants: Plant[]): string[] {
        const lines: string[] = []

        knowledgeGraph.initialize()
        if (plants.length > 0) {
            knowledgeGraph.injectPlants(plants)
        }

        const links: CrossModuleLink[] = []
        for (const plant of plants) {
            const plantLinks = knowledgeGraph.getRelatedLinks({
                plantId: plant.id,
                currentStage: plant.stage,
                maxResults: 5,
            })
            for (const link of plantLinks) {
                if (!links.some((l) => l.id === link.id)) {
                    links.push(link)
                }
            }
        }

        if (links.length === 0) return lines

        const t = getT()
        lines.push(`## ${t('growBible.relatedKnowledge', 'Related Knowledge')}`)
        lines.push('')
        lines.push(t('growBible.relatedKnowledgeDesc', 'Based on your current grow, these knowledge topics are most relevant:'))
        lines.push('')

        for (const link of links.slice(0, 15)) {
            lines.push(
                `- **[${link.nodeType}]** ${link.label} (relevance: ${Math.round(link.relevanceScore * 100)}%)`,
            )
        }
        lines.push('')

        return lines
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function slugify(text: string): string {
    return text
        .toLowerCase()
        .replace(/[^\w\s-]/g, '')
        .replace(/\s+/g, '-')
        .replace(/-+/g, '-')
        .trim()
}

// ---------------------------------------------------------------------------
// Singleton
// ---------------------------------------------------------------------------

export const growBibleExporter = new GrowBibleExporter()
