// ---------------------------------------------------------------------------
// growBibleExportService.test.ts -- Unit tests for Grow Bible Export
// ---------------------------------------------------------------------------

import { describe, it, expect } from 'vitest'
import { growBibleExporter } from '@/services/growBibleExportService'
import { PlantStage } from '@/types'
import type { Plant, AppSettings } from '@/types'

function makePlant(overrides: Partial<Plant> = {}): Plant {
    return {
        id: 'p1',
        name: 'Test Plant',
        stage: PlantStage.Flowering,
        age: 45,
        health: 75,
        strain: { name: 'Northern Lights' } as never,
        environment: {
            internalTemperature: 25,
            internalHumidity: 50,
            vpd: 1.2,
            lightPpfd: 800,
            co2Ppm: 400,
        },
        medium: {
            ph: 6.0,
            ec: 1.8,
            moisture: 55,
            type: 'soil',
        },
        problems: [{ type: 'nutrient_burn', severity: 5, onsetDay: 10, status: 'active' }],
        tasks: [],
        journal: [
            {
                id: 'j1',
                type: 'watering',
                createdAt: Date.now(),
                notes: 'Watered 500ml',
            },
        ],
        notes: [],
        harvestData: undefined,
        ...overrides,
    } as unknown as Plant
}

const mockSettings = {
    general: { language: 'en' },
} as unknown as AppSettings

describe('growBibleExportService', () => {
    it('should generate a markdown string', () => {
        const plants = [makePlant()]
        const md = growBibleExporter.generate(plants, mockSettings)
        expect(md).toContain('# CannaGuide Grow Bible')
        expect(md).toContain('Test Plant')
    })

    it('should include plant details', () => {
        const plants = [makePlant()]
        const md = growBibleExporter.generate(plants, mockSettings)
        expect(md).toContain('Northern Lights')
        expect(md).toContain('FLOWERING')
        expect(md).toContain('75/100')
    })

    it('should include journal entries', () => {
        const plants = [makePlant()]
        const md = growBibleExporter.generate(plants, mockSettings, { includeJournal: true })
        expect(md).toContain('watering')
        expect(md).toContain('Watered 500ml')
    })

    it('should skip journal when disabled', () => {
        const plants = [makePlant()]
        const md = growBibleExporter.generate(plants, mockSettings, { includeJournal: false })
        expect(md).not.toContain('### Journal')
    })

    it('should include active problems', () => {
        const plants = [makePlant()]
        const md = growBibleExporter.generate(plants, mockSettings)
        expect(md).toContain('nutrient_burn')
        expect(md).toContain('severity')
    })

    it('should generate table of contents', () => {
        const plants = [makePlant(), makePlant({ id: 'p2', name: 'Plant Two' })]
        const md = growBibleExporter.generate(plants, mockSettings)
        expect(md).toContain('## Table of Contents')
        expect(md).toContain('Test Plant')
        expect(md).toContain('Plant Two')
    })

    it('should handle empty plant list', () => {
        const md = growBibleExporter.generate([], mockSettings)
        expect(md).toContain('# CannaGuide Grow Bible')
        expect(md).toContain('**Plants:** 0')
    })

    it('should include footer', () => {
        const md = growBibleExporter.generate([], mockSettings)
        expect(md).toContain('Generated by CannaGuide 2025')
    })
})
