// ---------------------------------------------------------------------------
// Zustand Smart Alerts Store -- transient UI state for proactive coach alerts
//
// Alerts are ephemeral (not persisted to IndexedDB). They are generated by
// the proactiveCoachService when IoT sensor readings exceed safe thresholds
// and dismissed by the user via the ProactiveAlertBanner component.
// ---------------------------------------------------------------------------

import { create } from 'zustand'
import { subscribeWithSelector, devtools } from 'zustand/middleware'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type AlertMetric = 'temperature' | 'humidity' | 'vpd' | 'ph' | 'ec' | 'co2' | 'moisture'

export interface SmartAlert {
    id: string
    timestamp: number
    triggerValue: number
    metric: AlertMetric
    aiAdvice: string
    isDismissed: boolean
    plantId: string
    plantName: string
}

interface AlertsState {
    alerts: SmartAlert[]
    addAlert: (alert: SmartAlert) => void
    dismissAlert: (id: string) => void
    clearAlerts: () => void
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Maximum number of alerts kept in memory (FIFO). */
const MAX_ALERTS = 50

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

export const useAlertsStore = create<AlertsState>()(
    devtools(
        subscribeWithSelector((set) => ({
        alerts: [],

        addAlert: (alert: SmartAlert) =>
            set((state) => {
                const next = [...state.alerts, alert]
                if (next.length > MAX_ALERTS) {
                    next.splice(0, next.length - MAX_ALERTS)
                }
                return { alerts: next }
            }),

        dismissAlert: (id: string) =>
            set((state) => ({
                alerts: state.alerts.map((a) => (a.id === id ? { ...a, isDismissed: true } : a)),
            })),

        clearAlerts: () => set({ alerts: [] }),
    })),
        { name: 'alerts', enabled: import.meta.env.DEV },
    ),
)
