name: Labeler

on:
    pull_request_target:
        types: [opened, synchronize, reopened]

concurrency:
    group: labeler-${{ github.event.pull_request.number }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    label:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Harden runner
              uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
              with:
                  egress-policy: audit

            - name: Apply labels
              uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
