name: Renovate

on:
    schedule:
        - cron: '0 4 * * 1' # Every Monday at 04:00 UTC
    workflow_dispatch:

permissions:
    contents: read

jobs:
    renovate:
        name: Renovate Dependency Updates
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
              with:
                  egress-policy: audit

            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Self-hosted Renovate
              uses: renovatebot/github-action@531c6786d6cf05ef148c4cfe251745c2c6de442c # v41.0.9
              with:
                  configurationFile: .renovaterc.json
                  token: ${{ secrets.RENOVATE_TOKEN }}
